### ISSUE TITLE
How can we freeze all the weights of backbone and RPN together in Detectron2

### ISSUE THREAD

**Issue by kuzhang** [facebookresearch/detectron2#2240] opened 2020-11-08 10:09 UTC
How can we freeze all the weights of backbone and RPN together in Detectron2, only leaving the BoxHead trainable,  i.e. using Faster RCNN 50.  Thank you.

**Comment by ppwwyyxx** [comment] 2020-11-09 06:51
Duplicate of  #478

**Closed by ppwwyyxx** 2020-11-09 06:51 UTC
