### ISSUE TITLE
Using Detectron2 with c++, instead of python?

### ISSUE THREAD

**Issue by antithing** [facebookresearch/detectron2#613] opened 2020-01-02 15:39 UTC
Apologies if this has been asked before, i didn't see it in any previously opened issues.

Is it possible to use Detectron with libtorch in c++ only? 
Is there any c++ example code?

Thanks!

**Comment by ppwwyyxx** [comment] 2020-01-02 17:48
duplicate of #46

**Closed by ppwwyyxx** 2020-01-02 17:48 UTC

**Comment by LESSuseLESS** [comment] 2020-09-06 19:13
https://github.com/LESSuseLESS/d2
