### ISSUE TITLE
How to make the EventWriter log more frequently?

### ISSUE THREAD

**Issue by chenwydj** [facebookresearch/detectron2#1006] opened 2020-03-06 19:14 UTC
## ❓ How to make the EventWriter log more frequently?

I find current `class CommonMetricPrinter(EventWriter)` writes a log every 20 iterations during training.

How to make it write logs more frequently? I did not find any related configuration.

Thank you!

**Comment by ppwwyyxx** [comment] 2020-03-06 19:19
Duplicate of #920

**Closed by ppwwyyxx** 2020-03-06 19:19 UTC
