### ISSUE TITLE
Is there a plan to support mix precision training?

### ISSUE THREAD

**Issue by xiaohu2015** [facebookresearch/detectron2#1953] opened 2020-08-25 02:08 UTC
## 🚀 Feature
A clear and concise description of the feature proposal.

## Motivation & Examples

Tell us why the feature is useful.

Describe what the feature would look like, if it is implemented.
Best demonstrated using **code examples** in addition to words.

## Note

We only consider adding new features if they are relevant to many users.

If you request implementation of research papers -- we only consider papers that have enough significance and prevalance in the object detection field.

We do not take requests for most projects in the `projects/` directory, because they are research code release that is mainly for other researchers to reproduce results.

"Make X faster/accurate" is not a valid feature request. "Implement a concrete feature that can make X faster/accurate" can be a valid feature request.

Instead of adding features inside detectron2,
you can implement many features by [extending detectron2](https://detectron2.readthedocs.io/tutorials/extend.html).
The [projects/](https://github.com/facebookresearch/detectron2/tree/master/projects/) directory contains many of such examples.

**Comment by ppwwyyxx** [comment] 2020-08-25 04:59
duplicate of #72

**Closed by ppwwyyxx** 2020-08-25 04:59 UTC
