### ISSUE TITLE
how to remove tools module from site-packages after install detectron2

### ISSUE THREAD

**Issue by thanhtu98** [facebookresearch/detectron2#4392] opened 2022-07-11 02:19 UTC
- After i install detector2 by command: python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'. A module named tools is spawned in site-packages. it conflict when i install PaddleOCR. 
- I finded solution in https://github.com/PaddlePaddle/PaddleOCR/issues/1024#issuecomment-1105946934 but I don't want modify code in liblary.
- Is there any way when I install detectron2 that the module tools doesn't spawn at site-packages.
- Thanks ALL.

**Comment by ppwwyyxx** [comment] 2022-08-03 15:36
Duplicate of https://github.com/facebookresearch/detectron2/issues/3934

**Closed by ppwwyyxx** 2022-08-03 15:36 UTC
