### ISSUE TITLE
Are there any pre-trained model files available for Trident Net? 

### ISSUE THREAD

**Issue by kira0992** [facebookresearch/detectron2#208] opened 2019-10-31 14:17 UTC
## ❓ Questions and Help

Are there plans to release pre-trained model files for "projects" too. It would be really helpful to have Dense Pose and Trident Net models too if they are available.

**Comment by lyttonhao** [comment] 2019-11-02 08:54
Thanks for your interest. We will release the pretrained TridentNet models soon.

**Comment by ppwwyyxx** [comment] 2019-11-02 12:58
duplicate of #65

**Closed by ppwwyyxx** 2019-11-02 12:58 UTC
