### ISSUE TITLE
problem about  torch.randperm when device is cuda

### ISSUE THREAD

**Issue by XiongUp** [facebookresearch/detectron2#3008] opened 2021-05-06 05:37 UTC
Hello, I'm new to deep learning and used detectron2 for the first time. 

## Instructions To Reproduce the Issue:
- I followed the instructions in the documentation, but an error was encountered, which said that **RuntimeError: CUDA error: device-side assert triggered**. 

- Then I try to debug project and find an unexpected behavior that torch.randperm gave incorrect results（The question is on line 50 of the detectron2/detectron2/modeling/sampling.py）

 ```    # randomly select positive and negative examples
    perm1 = torch.randperm(positive.numel(), device=positive.device)[:num_pos]
    perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]

    pos_idx = positive[perm1]
    neg_idx = negative[perm2]
 ```

- It looks like the code is ok, but perm2 may include some really big numbers that out of range of array when negative.numel() is big number.

## What exact command I run:
I didn't make any changes to Detectron2 and execute the following command.
```
train_net.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml --num-gpus 1 SOLVER.IMS_PER_BATCH 1 SOLVER.BASE_LR 0.0025
 ```
## __Full logs__ or other relevant observations:
```
ERROR [05/06 12:27:35 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/xjun/xjun-bistu/detectron2/detectron2/engine/train_loop.py", line 150, in train
    self.run_step()
  File "/home/xjun/xjun-bistu/detectron2/detectron2/engine/defaults.py", line 495, in run_step
    self._trainer.run_step()
  File "/home/xjun/xjun-bistu/detectron2/detectron2/engine/train_loop.py", line 274, in run_step
    loss_dict = self.model(data)
  File "/home/xjun/anaconda3/envs/cvlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xjun/xjun-bistu/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 157, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/xjun/anaconda3/envs/cvlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xjun/xjun-bistu/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 471, in forward
    gt_labels, gt_boxes = self.label_and_sample_anchors(anchors, gt_instances)
  File "/home/xjun/anaconda3/envs/cvlab/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xjun/xjun-bistu/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 352, in label_and_sample_anchors
    gt_labels_i = self._subsample_labels(gt_labels_i)
  File "/home/xjun/xjun-bistu/detectron2/detectron2/modeling/proposal_generator/rpn.py", line 297, in _subsample_labels
    label, self.batch_size_per_image, self.positive_fraction, 0
  File "/home/xjun/xjun-bistu/detectron2/detectron2/modeling/sampling.py", line 53, in subsample_labels
    neg_idx = negative[perm2]
RuntimeError: CUDA error: device-side assert triggered
```
## Environment:
```
sys.platform            linux
Python                  3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
numpy                   1.20.1
detectron2              0.4 @/home/xjun/xjun-bistu/detectron2/detectron2
Compiler                GCC 9.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   5.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu111 @/home/xjun/anaconda3/envs/cvlab/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   GeForce GTX 950M (arch=5.0)
CUDA_HOME               /usr/local/cuda-11.1
Pillow                  8.2.0
torchvision             0.9.1+cu111 @/home/xjun/anaconda3/envs/cvlab/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20210423
iopath                  0.1.8
cv2                     4.5.1
```
```
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
 ```
## My solution

- Torch.randperm will give correct result after I changed `perm2 = torch.randperm(negative.numel(), device=negative.device)[:num_neg]` to `perm2 = torch.randperm(negative.numel(), device='cpu')[:num_neg]`
- I don't know if it's pytorch's problem or detectron's problem.

**Comment by ppwwyyxx** [comment] 2021-05-06 06:42
Duplicate of #2837 .

**Closed by ppwwyyxx** 2021-05-06 06:42 UTC
