### ISSUE TITLE
Running caffe2 model on batched inputs (list[{"image:",img1_tensor},{"image":img2_tensor}])

### ISSUE THREAD

**Issue by satheeshkatipomu** [facebookresearch/detectron2#1787] opened 2020-07-17 08:38 UTC
Issue: Could not infere on batched inputs(list[{"image:",img1_tensor},{"image":img2_tensor}]), but working fine on single image.
## Instructions To Reproduce the Issue:

1. full code you wrote or full changes you made (`git diff`)
```
img1 = cv2.imread("img1.jpg")
img1 = torch.as_tensor(img1.astype("float32").transpose(2, 0, 1))
img2 = cv2.imread("img2.jpg")
img2 = torch.as_tensor(img2.astype("float32").transpose(2, 0, 1))
inputs = [{"image":img1,"height":512,"width":512},{"image":img2,"height":512,"width":512}]


from detectron2.export.caffe2_inference import ProtobufDetectionModel

predict_net = caffe2_pb2.NetDef()
with open("frcnn_model.pb", "rb") as f:
    predict_net.ParseFromString(f.read())

init_net = caffe2_pb2.NetDef()
with open("frcnn_model_init.pb", "rb") as f:
    init_net.ParseFromString(f.read())

predictor = ProtobufDetectionModel(predict_net,init_net)

predictor(inputs)
```
## Error:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-803747310275> in <module>
----> 1 predictor(inputs)

~/opt/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/Documents/EV_Assess/detectron2/detectron2/export/caffe2_inference.py in forward(self, batched_inputs)
    134         }
    135 
--> 136         return self._convert_outputs(batched_inputs, c2_inputs, c2_results)

~/Documents/EV_Assess/detectron2/detectron2/export/caffe2_modeling.py in f(batched_inputs, c2_inputs, c2_results)
    277         def f(batched_inputs, c2_inputs, c2_results):
    278             image_sizes = [[int(im[0]), int(im[1])] for im in c2_inputs["im_info"]]
--> 279             results = assemble_rcnn_outputs_by_name(image_sizes, c2_results)
    280             return meta_arch.GeneralizedRCNN._postprocess(results, batched_inputs, image_sizes)
    281 

~/Documents/EV_Assess/detectron2/detectron2/export/caffe2_modeling.py in assemble_rcnn_outputs_by_name(image_sizes, tensor_outputs, force_mask_on)
     47     if batch_splits:
     48         raise NotImplementedError()
---> 49     assert len(image_sizes) == 1
     50     result = results[0]
     51 

AssertionError:
```

## Expected behavior:

I am expecting output as ```[{instances:Instances, scores:, pred_classes:},{instances:Instances, scores:, pred_classes:}]``` . Confused why there assertion on image_sizes, if I comment it, its failing in postprocessing.

## Environment:

```
---------------------  --------------------------------------------------------------------------------------------------------------------
sys.platform           darwin
Python                 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 23:06:31) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy                  1.18.1
detectron2             0.1.3 @/Users/user/detectron2/detectron2
Compiler               clang 11.0.3
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.5.1 @/Users/opt/anaconda3/envs/detectron2/lib/python3.6/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 7.2.0
torchvision            0.6.1 @/Users/opt/anaconda3/envs/detectron2/lib/python3.6/site-packages/torchvision
fvcore                 0.1.1.post20200704
cv2                    4.2.0
---------------------  --------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 9.1.0
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -faligned-new -fno-math-errno -fno-trapping-math -Werror=format -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, USE_STATIC_DISPATCH=OFF,

```

**Comment by ppwwyyxx** [comment] 2020-07-17 20:51
Duplicate of https://github.com/facebookresearch/detectron2/issues/1030

**Closed by ppwwyyxx** 2020-07-17 20:51 UTC

**Comment by satheeshkatipomu** [comment] 2020-07-18 05:22
@ppwwyyxx , I see it is actually same issue. Can you provide more hints on how to fix this?
