### ISSUE TITLE
Error when deploy to azure

### ISSUE THREAD

**Issue by jamil-z** [facebookresearch/detectron2#4774] opened 2023-02-03 15:31 UTC
the problem is that when trying to deploy my application with detectron2 in azure in an app service, it fails to deploy
This failure occurs when from the provided requirements.txt file, in the detectron2 version:
detectron2==0.4
-f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.6/index.html

in the middle of installing pycocotools (more details below)
locally everything works fine with the same requirements.txt file (omitted code from app.py to avoid having to upload the whole model .pth, but still gets exactly the same error)

## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:

https://github.com/jamil-z/detectron

2. What exact command you run:

deploy to azure in a app service for the VS extension

3. __Full logs__ or other relevant observations:

full error file is in git, error deploy Azure: https://github.com/jamil-z/detectron
This happens when you try to install the version of detectron2==0.4, which has the requirements.txt
This is the first error that appears on line 190

3:03:15 PM detector-structure-mouth: [15:03:03+0000] Building wheels for collected packages: pycocotools
3:03:15 PM detector-structure-mouth: [15:03:03+0000] Building wheel for pycocotools (pyproject.toml): started
3:03:15 PM detector-structure-mouth: [15:03:11+0000] Building wheel for pycocotools (pyproject.toml): finished with status 'error'
3:03:15 PM detector-structure-mouth: error: subprocess-exited-with-error
3:03:15 PM detector-structure-mouth:
3:03:15 PM detector-structure-mouth: × Building wheel for pycocotools (pyproject.toml) did not run successfully.
3:03:16 PM detector-structure-mouth: │ exit code: 1
3:03:16 PM detector-structure-mouth: ╰─> [62 lines of output]
3:03:16 PM detector-structure-mouth: running bdist_wheel

4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

Deployment to Azure is expected (the base application has already been deployed, so Azure works)

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/main/detectron2/utils/collect_env.py && python collect_env.py
```
---------------------  --------------------------------------------------------------------------------------------------------------
sys.platform           linux
Python                 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
numpy                  1.19.3
detectron2             0.4 @/home/jamil/moodbit/detectron2/sample-flask-app-master/venv/lib/python3.8/site-packages/detectron2
Compiler               GCC 7.3
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.6.0+cpu @/home/jamil/moodbit/detectron2/sample-flask-app-master/venv/lib/python3.8/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 8.0.1
torchvision            0.7.0+cpu @/home/jamil/moodbit/detectron2/sample-flask-app-master/venv/lib/python3.8/site-packages/torchvision
fvcore                 0.1.3.post20210317
cv2                    4.7.0
---------------------  --------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment] 2023-02-11 01:47
Since the issue doesn't reproduce locally, it would require an environment to reproduce the issue for others to debug. That's not provided, hence closing.

**Closed by ppwwyyxx** 2023-02-11 01:47 UTC
