### ISSUE TITLE
Installation Failed on My Window 10 with A New Anaconda Env

### ISSUE THREAD

**Issue by FrankXinqi** [facebookresearch/detectron2#137] opened 2019-10-22 09:33 UTC
## Problem

I have tested on Colab, the detectron2 works very good. Now I would like to move it to my PC.

## Original
The first two lines, I have changed to these:
originally,
'!pip install -U torch torchvision'
'pip install git+https://github.com/facebookresearch/fvcore.git'

## Changed to
I run it from my terminal,
'conda install pytorch torchvision cpuonly -c pytorch' All good.

'pip install git+https://github.com/facebookresearch/fvcore.git' 
I got ERROR

## Error message
termcolor-1.1.0.tar.gz
Collecting shapely
  Using cached https://files.pythonhosted.org/packages/a2/fb/7a7af9ef7a35d16fa23b127abee272cfc483ca89029b73e92e93cdf36e6b/
Shapely-1.6.4.post2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'D:\Program\Anaconda3\envs\pytorch_1_3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'
C:\\Users\\USER~1\\AppData\\Local\\Temp\\pip-install-yc7fv6nu\\shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER~1
\\AppData\\Local\\Temp\\pip-install-yc7fv6nu\\shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);c
ode=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg
-base 'C:\Users\USER~1\AppData\Local\Temp\pip-install-yc7fv6nu\shapely\pip-egg-info'
         cwd: C:\Users\USER~1\AppData\Local\Temp\pip-install-yc7fv6nu\shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER~1\AppData\Local\Temp\pip-install-yc7fv6nu\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\USER~1\AppData\Local\Temp\pip-install-yc7fv6nu\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "D:\Program\Anaconda3\envs\pytorch_1_3\lib\ctypes\__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Environment

I created a new environment Python 3.7 with Anaconda. And configure PyCharm to use it.

**Comment by ppwwyyxx** [comment] 2019-10-22 09:35
duplicate of #124

**Closed by ppwwyyxx** 2019-10-22 09:35 UTC
