### ISSUE TITLE
Addition of samplers like OHEM

### ISSUE THREAD

**Issue by rush2406** [facebookresearch/detectron2#3379] opened 2021-08-18 10:59 UTC
## 🚀 Feature
Addition of samplers like OHEM

## Motivation & Examples

Currently, a random sampler is being used in RoIHeads. However, other samplers have been shown to perform better than random sampling and heuristics. Thus, this motivates the need to introduce other samplers for example OHEM.

There can be flag/option introduced to use a particular sampler. Based on the flag, the corresponding sampler would be used.

**Comment by ppwwyyxx** [comment] 2021-08-21 11:12
Duplicate of #354

**Closed by ppwwyyxx** 2021-08-21 11:12 UTC
Labels: enhancement
