### ISSUE TITLE
Any plan for supporting Cascade RCNN/MASKRCNN pth to caffe2 pb?

### ISSUE THREAD

**Issue by congjianting** [facebookresearch/detectron2#1450] opened 2020-05-19 03:20 UTC
Hi, "cascaderoiheads" works well in our research interest, but .pth don't be suitable for deployment. any plan for supporting "export to caffe2 pb"? Thanks.

**Comment by ppwwyyxx** [comment] 2020-05-19 07:38
No plans. Duplicate of #988

**Closed by ppwwyyxx** 2020-05-19 07:38 UTC
