### ISSUE TITLE
Unable to install detectron2 on ubuntu 20.04

### ISSUE THREAD

**Issue by alishibli97** [facebookresearch/detectron2#2296] opened 2020-11-21 15:53 UTC
I am using Pytorch 1.7, Cuda10.1, python3.6. 
I am following the [installation instructions](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md).
However, I fail to build it from source through the 2 mentioned methods for Linux.
The main error I get is:
_cublas_v2.h: No such file or directory_
I tried to go around by reinstalling pytorch itself, but it didn't help.
Any idea?

**Comment by ppwwyyxx** [comment] 2020-11-21 20:29
Duplicate of #2292

**Closed by ppwwyyxx** 2020-11-21 20:29 UTC
