### ISSUE TITLE
the yacs issue 

### ISSUE THREAD

**Issue by zhao-yiqun** [facebookresearch/detectron2#3833] opened 2021-12-28 03:15 UTC
## Instructions To Reproduce the 🐛 Bug:
Hi, Following the method mentioned by https://github.com/facebookresearch/detectron2/issues/3649, I have updated yacs to 0.1.8,

However, when I run the code

from detectron2.config import get_cfg

there are still assertion error
AssertionError: Invalid type <class 'NoneType'> for key WEIGHT_DECAY_BIAS; valid types = {<class 'list'>, <class 'tuple'>, <class 'int'>, <class 'bool'>, <class 'str'>, <class 'float'>}

As I used the the conda to monitor my environments, when I use the conda list to check the version of yacs, it's version is 0.1.8
However, when I use the anaconda search -t conda yacs, it is still 0.1.6. Have you ever meet the same issue? many thanks to you~
## Expected behavior:

I hope anyone can help me, many thanks~

## Environment:
My environments is CUDA 11.4 and the pytorch version is '1.10.1+cu113', and the detectron2 is 0.6, I believe that is not the environments error

**Comment by ppwwyyxx** [comment] 2021-12-28 03:56
Duplicate of https://github.com/facebookresearch/detectron2/issues/3649. I believe you have not correctly installed yacs>=0.1.8. 

https://ppwwyyxx.com/blog/2019/On-Environment-Packaging-in-Python/ has some helpful information about managing python packages.

**Closed by ppwwyyxx** 2021-12-28 03:56 UTC
