### ISSUE TITLE
How to store the validation set loss?

### ISSUE THREAD

**Issue by Zy1013921842** [facebookresearch/detectron2#569] opened 2019-12-23 10:46 UTC
Hello!
I want to draw a validation set loss curve as iteration goes on, just like the training loss curve in tensorboard. How can I store these losses into the tf file?
Thanks very much!

**Comment by ppwwyyxx** [comment] 2019-12-23 14:03
The model outputs the losses: https://detectron2.readthedocs.io/tutorials/models.html#model-output-format 
So you can run `losses = model(data)` where `data` is validation data.

You may need a custom hook if you need to do it with `DefaultTrainer`, because `DefaultTrainer` is only made to support standard training workflow.

**Comment by Zy1013921842** [comment] 2019-12-25 04:08
@ppwwyyxx 
Can I set cfg.TEST.EVAL_PERIOD =20 to periodically evaluate the model during training and write the evaluation results to tensorboard file? Btw, this evaluation is done on the test_set, right?

**Comment by ppwwyyxx** [comment] 2019-12-25 09:24
`EVAL_PERIOD` is already used and it does something else. It controls the period to runs the model in evaluation mode and there is no definition of "loss" in evaluation mode (unless you implement your own model that has such definition).

This is in fact a duplicate of #499 .

**Closed by ppwwyyxx** 2019-12-25 09:24 UTC

**Comment by ortegatron** [comment] 2020-03-22 16:58
I've written a custom trainer to see the validation loss curve, please check it here:
Hi, I have written it and commented the code, you can see it here:
https://medium.com/@apofeniaco/training-on-detectron2-with-a-validation-set-and-plot-loss-on-it-to-avoid-overfitting-6449418fbf4e

**Comment by dangmanhtruong1995** [comment] 2020-05-30 09:21
> I've written a custom trainer to see the validation loss curve, please check it here:
> Hi, I have written it and commented the code, you can see it here:
> https://medium.com/@apofeniaco/training-on-detectron2-with-a-validation-set-and-plot-loss-on-it-to-avoid-overfitting-6449418fbf4e

Hi I tried your code but after running validation it just hangs and does not run anything else. Please help me. Thank you very much. After a while, an error popped up: RuntimeError: [/opt/conda/conda-bld/pytorch_1587428207430/work/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete
