### ISSUE TITLE
How to do evaluation while training

### ISSUE THREAD

**Issue by Prabakaran-Chandran** [facebookresearch/detectron2#1487] opened 2020-05-28 14:05 UTC
## ❓ How to evaluate the validation data while training 

Describe what you want to do, including:
1. I have 2000 images for training , 500 images for validation and 500 for testing .. 
2.how to use that 500 images and do the validation while training itself ..

**Comment by ppwwyyxx** [comment] 2020-05-28 17:22
duplicate of #676

**Closed by ppwwyyxx** 2020-05-28 17:22 UTC
