### ISSUE TITLE
Cannot find operator schema for GivenTensorFill on Windows

### ISSUE THREAD

**Issue by liuqibj** [facebookresearch/detectron2#1138] opened 2020-04-02 03:37 UTC
#323  Instructions To Reproduce the Issue:

1. what changes you made (`git diff`) or what code you wrote
```
na
```
2. what exact command you run:
faild on p = workspace.Predictor(init_net, predict_net)

3. what you observed (including __full logs__):
```
C:\ProgramData\Anaconda3\python.exe F:/detectron2-deploy/detectron2.py
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
[E ..\caffe2\core\operator.cc:203] Cannot find operator schema for GivenTensorFill. Will skip schema checking.
Traceback (most recent call last):
  File "F:/detectron2-deploy/detectron2.py", line 52, in <module>
    p = workspace.Predictor(init_net, predict_net)
  File "C:\ProgramData\Anaconda3\lib\site-packages\caffe2\python\workspace.py", line 187, in Predictor
    return C.Predictor(StringifyProto(init_net), StringifyProto(predict_net))
RuntimeError: [enforce fail at ..\caffe2\core\operator.cc:273] op. Cannot create operator of type 'GivenTensorFill' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: output: "_wrapped_model.roi_heads.mask_head.deconv.bias" name: "" type: "GivenTensorFill" arg { name: "values" floats: -0.0133463955 floats: -0.00451810285 floats: -0.00233685179 floats: -0.00512876036 floats: -3.89804154e-05 floats: -0.00522633409 floats: -0.002094266 floats: 0.00425540796 floats: -0.00202779332 floats: -0.00452422164 floats: -0.00494699087 floats: 0.00888893567 floats: 0.000628064154 floats: 0.00554875843 floats: -0.000729904626 floats: -0.00689219125 floats: -0.00435591443 floats: -0.00177043607 floats: 0.00603152579 floats: 0.00248198095 floats: -0.00236232206 floats: 0.00210060831 floats: 0.00264757848 floats: -0.000766509678 floats: -0.00892050657 floats: -0.00285720127 floats: -0.00527871493 floats: -0.00197225506 floats: -0.0130366078 floats: 0.0457181185 floats: 0.00207639835 floats: 0.00383780641 floats: 0.00585558824 floats: -0.00640401104 floats: -0.00286261854 floats: -0.00410347758 floats: 0.00543660484 floats: -0.00434046332 floats: 0.0195315387 floats: 1.27268631e-05 floats: -0.00686306274 floats: 0.00122344948 floats: -0.0023904962 floats: 0.0185162816 floats: -0.00347617106 floats: -0.00204608496 floats: -0.00644181948 floats: -0.00431578653 floats: -0.0070042382 floats: -9.29903308e-06 floats: -0.00610245205 floats: 0.00453285407 floats: 0.0128202764 floats: -0.00274957833 floats: -0.0098316092 floats: -0.000953428098 floats: 0.00127127254 floats: 0.00196527457 floats: -0.00112321088 floats: -0.00347023504 floats: 0.00306781754 floats: -0.00647735875 floats: 0.00115113973 floats: -0.00183584937 floats: -0.0022683125 floats: 6.422359e-05 floats: -0.00422474556 floats: -0.00385058345 floats: 0.00152697507 floats: -0.00264847046 floats: -0.00290166843 floats: 0.000123733451 floats: 0.00885537174 floats: -0.00472532725 floats: 0.00408285158 floats: 0.00591197144 floats: 0.00177600398 floats: -0.00585387787 floats: 0.00948924851 floats: -0.00498422515 floats: -5.47085292e-05 floats: -0.000678259588 floats: -0.00567928376 floats: -0.00537253823 floats: -0.00433486 floats: 0.0128758838 floats: 0.00353097869 floats: -0.00177739887 floats: 0.00951001 floats: 0.00609118212 floats: -0.00756523153 floats: 0.00118487224 floats: -0.0036944598 floats: -0.00182979635 floats: -0.0049654413 floats: 0.0107105607 floats: -0.0063000638 floats: -0.00093799422 floats: 0.0012816 floats: -0.00191840134 floats: 0.00331371301 floats: 0.0038416048 floats: 0.0172487721 floats: 0.00815760344 floats: -0.00359685253 floats: 0.00944180507 floats: -0.00666287122 floats: -0.0085797878 floats: -0.00199870486 floats: 0.022758102 floats: -0.00131991459 floats: -0.00450740382 floats: -0.00318096951 floats: -0.00023713331 floats: -0.00503370818 floats: 0.0122581972 floats: 0.00667853886 floats: -0.00386638776 floats: 0.00641735969 floats: -0.00458998093 floats: 0.000107689972 floats: -0.00438639196 floats: -0.00433755061 floats: -0.00241363351 floats: -0.0100678829 floats: -0.000734080386 floats: 0.00304426881 floats: 0.00365702761 floats: -0.00589147815 floats: -0.00572600216 floats: 0.00595175149 floats: 0.000568681455 floats: -0.000788536563 floats: -0.00454648 floats: 0.000920958759 floats: 0.00427800557 floats: 0.000859911437 floats: 0.00380735495 floats: 0.0119522875 floats: -0.00151786464 floats: -0.00615171529 floats: -0.00528152427 floats: -0.00295557687 floats: 0.023088932 floats: 0.00150240376 floats: -0.00263289525 floats: -0.00673608854 floats: -0.000681171077 floats: -0.00717083225 floats: 0.00455912761 floats: 0.00316433259 floats: 0.000161236167 floats: 0.00566338608 floats: 0.009991033 floats: -0.00267546671 floats: 0.00939404592 floats: 0.00247722049 floats: 0.00139171048 floats: -0.00598011538 floats: -0.00303286337 floats: 0.0197357349 floats: 0.0333247632 floats: -0.00167901348 floats: -0.00330767408 floats: -0.00504392339 floats: -0.0011615071 floats: 0.000214857617 floats: 0.0029784923 floats: 0.000832818507 floats: 0.00498089194 floats: 0.00487433746 floats: 0.0110022547 floats: -0.00424086628 floats: 0.00899052247 floats: 0.0164586939 floats: 0.00287862332 floats: -0.00264235586 floats: -0.00887512229 floats: -0.0018972205 floats: 0.00679051 floats: -0.000307731418 floats: 2.45072479e-05 floats: 0.00816998631 floats: -0.00278886594 floats: -0.00630555 floats: -0.00331548927 floats: 0.00134936185 floats: -0.00250257785 floats: 0.00687917601 floats: 0.0100089954 floats: -0.0074177268 floats: -6.68023786e-05 floats: 0.0174464751 floats: -0.000393663766 floats: -0.00130914547 floats: -0.00155922968 floats: -0.00322099729 floats: 0.00297813 floats: -0.00287037203 floats: -0.0118008517 floats: -0.00732119242 floats: 0.00596023351 floats: 0.00331998593 floats: -0.00147248071 floats: -0.00817350764 floats: -0.00300547574 floats: -0.00479339808 floats: 0.000172466709 floats: -0.0146297375 floats: -0.00458431849 floats: -0.00555927539 floats: -0.0020990693 floats: -0.00807808526 floats: -0.00559028797 floats: -0.00812955666 floats: -0.0026507827 floats: 0.00939083192 floats: -0.00738777919 floats: -0.00828738697 floats: -0.00179705455 floats: 0.0062642917 floats: -0.00237952708 floats: -0.00764051219 floats: 0.0278734509 floats: -0.0137160514 floats: -0.00418039784 floats: -0.00337893772 floats: -0.00657159509 floats: 0.011035962 floats: 0.00229364354 floats: -0.00680769142 floats: 0.0017056705 floats: -0.0044108 floats: 0.0080696512 floats: -0.00305814017 floats: -0.00849655923 floats: -0.00768750301 floats: 0.0121126 floats: 0.00298131746 floats: 0.0117565263 floats: -0.00909942854 floats: 0.00626193872 floats: 0.00104942953 floats: 0.00558419898 floats: -0.00177347963 floats: 0.00779137341 floats: 0.000686824089 floats: -0.00412656041 floats: -0.00158432696 floats: -0.00195238751 floats: -0.0151727404 floats: -0.00118577352 floats: -0.0065637161 floats: -0.00444359193 floats: -0.00191132678 floats: -0.00198358414 } arg { name: "shape" ints: 256 } device_option { }
(no backtrace available)

Process finished with exit code 1

```
4. please also simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

train custom model and export it to pb format
load the pb and run it. 
expect it works on windows (work well on ubuntu)

## Environment:

Provide your environment information using the following command:
```
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
---------------------  ------------------------------------------------------------------
sys.platform           win32
Python                 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
numpy                  1.17.3
detectron2             failed to import
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.4.0+cpu @C:\ProgramData\Anaconda3\lib\site-packages\torch
PyTorch debug build    False
CUDA available         False
Pillow                 6.2.0
torchvision            0.5.0+cpu @C:\ProgramData\Anaconda3\lib\site-packages\torchvision
cv2                    4.1.1
---------------------  ------------------------------------------------------------------
PyTorch built with:
  - MSVC 191125547
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - OpenMP 200203
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=/DWIN32 /D_WINDOWS  /GR  /w /EHa /MP /bigobj -openmp, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

```

**Comment by ppwwyyxx** [comment] 2020-04-02 03:39
Duplicate of #1051

**Closed by ppwwyyxx** 2020-04-02 03:39 UTC

**Comment by liuqibj** [comment] 2020-04-05 08:57
@ppwwyyxx I tried to build the caffe2 from the pytorch and then installed it.  It also met the issue so I think it's a bug


    p = workspace.Predictor(init_net, predict_net)
  File "C:\ProgramData\Anaconda3\lib\site-packages\caffe2\python\workspace.py", line 186, in Predictor
    return C.Predictor(StringifyProto(init_net), StringifyProto(predict_net))
RuntimeError: [enforce fail at ..\caffe2\core\operator.cc:273] op. Cannot create operator of type 'GivenTensorFill' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: output: "_wrapped_model.roi_heads.mask_head.deconv.bias" name: "" type: "GivenTensorFill" arg { name: "values" floats: -0.0133463955 floats: -0.00451810285 floats: -0.00233685179 floats: -0.00512876036 floats: -3.89804154e-05 floats: -0.00522633409 floats: -0.002094266 floats: 0.00425540796 floats: -0.00202779332 floats: -0.00452422164 floats: -0.00494699087 floats: 0.00888893567 floats: 0.000628064154 floats: 0.00554875843 floats: -0.000729904626 floats: -0.00689219125 floats: -0.00435591443 floats: -0.00177043607 floats: 0.00603152579 floats: 0.00248198095 floats: -0.00236232206 floats: 0.00210060831 floats: 0.00264757848 floats: -0.000766509678 floats: -0.00892050657 floats: -0.00285720127 floats: -0.00527871493 floats: -0.00197225506 floats: -0.0130366078 floats: 0.0457181185 floats: 0.00207639835 floats: 0.00383780641 floats: 0.00585558824 floats: -0.00640401104 floats: -0.00286261854 floats: -0.00410347758 floats: 0.00543660484 floats: -0.00434046332 floats: 0.0195315387 floats: 1.27268631e-05 floats: -0.00686306274 floats: 0.00122344948 floats: -0.0023904962 floats: 0.0185162816 floats: -0.00347617106 floats: -0.00204608496 floats: -0.00644181948 floats: -0.00431578653 floats: -0.0070042382 floats: -9.29903308e-06 floats: -0.00610245205 floats: 0.00453285407 floats: 0.0128202764 floats: -0.00274957833 floats: -0.0098316092 floats: -0.000953428098 floats: 0.00127127254 floats: 0.00196527457 floats: -0.00112321088 floats: -0.00347023504 floats: 0.00306781754 floats: -0.00647735875 floats: 0.00115113973 floats: -0.00183584937 floats: -0.0022683125 floats: 6.422359e-05 floats: -0.00422474556 floats: -0.00385058345 floats: 0.00152697507 floats: -0.00264847046 floats: -0.00290166843 floats: 0.000123733451 floats: 0.00885537174 floats: -0.00472532725 floats: 0.00408285158 floats: 0.00591197144 floats: 0.00177600398 floats: -0.00585387787 floats: 0.00948924851 floats: -0.00498422515 floats: -5.47085292e-05 floats: -0.000678259588 floats: -0.00567928376 floats: -0.00537253823 floats: -0.00433486 floats: 0.0128758838 floats: 0.00353097869 floats: -0.00177739887 floats: 0.00951001 floats: 0.00609118212 floats: -0.00756523153 floats: 0.00118487224 floats: -0.0036944598 floats: -0.00182979635 floats: -0.0049654413 floats: 0.0107105607 floats: -0.0063000638 floats: -0.00093799422 floats: 0.0012816 floats: -0.00191840134 floats: 0.00331371301 floats: 0.0038416048 floats: 0.0172487721 floats: 0.00815760344 floats: -0.00359685253 floats: 0.00944180507 floats: -0.00666287122 floats: -0.0085797878 floats: -0.00199870486 floats: 0.022758102 floats: -0.00131991459 floats: -0.00450740382 floats: -0.00318096951 floats: -0.00023713331 floats: -0.00503370818 floats: 0.0122581972 floats: 0.00667853886 floats: -0.00386638776 floats: 0.00641735969 floats: -0.00458998093 floats: 0.000107689972 floats: -0.00438639196 floats: -0.00433755061 floats: -0.00241363351 floats: -0.0100678829 floats: -0.000734080386 floats: 0.00304426881 floats: 0.00365702761 floats: -0.00589147815 floats: -0.00572600216 floats: 0.00595175149 floats: 0.000568681455 floats: -0.000788536563 floats: -0.00454648 floats: 0.000920958759 floats: 0.00427800557 floats: 0.000859911437 floats: 0.00380735495 floats: 0.0119522875 floats: -0.00151786464 floats: -0.00615171529 floats: -0.00528152427 floats: -0.00295557687 floats: 0.023088932 floats: 0.00150240376 floats: -0.00263289525 floats: -0.00673608854 floats: -0.000681171077 floats: -0.00717083225 floats: 0.00455912761 floats: 0.00316433259 floats: 0.000161236167 floats: 0.00566338608 floats: 0.009991033 floats: -0.00267546671 floats: 0.00939404592 floats: 0.00247722049 floats: 0.00139171048 floats: -0.00598011538 floats: -0.00303286337 floats: 0.0197357349 floats: 0.0333247632 floats: -0.00167901348 floats: -0.00330767408 floats: -0.00504392339 floats: -0.0011615071 floats: 0.000214857617 floats: 0.0029784923 floats: 0.000832818507 floats: 0.00498089194 floats: 0.00487433746 floats: 0.0110022547 floats: -0.00424086628 floats: 0.00899052247 floats: 0.0164586939 floats: 0.00287862332 floats: -0.00264235586 floats: -0.00887512229 floats: -0.0018972205 floats: 0.00679051 floats: -0.000307731418 floats: 2.45072479e-05 floats: 0.00816998631 floats: -0.00278886594 floats: -0.00630555 floats: -0.00331548927 floats: 0.00134936185 floats: -0.00250257785 floats: 0.00687917601 floats: 0.0100089954 floats: -0.0074177268 floats: -6.68023786e-05 floats: 0.0174464751 floats: -0.000393663766 floats: -0.00130914547 floats: -0.00155922968 floats: -0.00322099729 floats: 0.00297813 floats: -0.00287037203 floats: -0.0118008517 floats: -0.00732119242 floats: 0.00596023351 floats: 0.00331998593 floats: -0.00147248071 floats: -0.00817350764 floats: -0.00300547574 floats: -0.00479339808 floats: 0.000172466709 floats: -0.0146297375 floats: -0.00458431849 floats: -0.00555927539 floats: -0.0020990693 floats: -0.00807808526 floats: -0.00559028797 floats: -0.00812955666 floats: -0.0026507827 floats: 0.00939083192 floats: -0.00738777919 floats: -0.00828738697 floats: -0.00179705455 floats: 0.0062642917 floats: -0.00237952708 floats: -0.00764051219 floats: 0.0278734509 floats: -0.0137160514 floats: -0.00418039784 floats: -0.00337893772 floats: -0.00657159509 floats: 0.011035962 floats: 0.00229364354 floats: -0.00680769142 floats: 0.0017056705 floats: -0.0044108 floats: 0.0080696512 floats: -0.00305814017 floats: -0.00849655923 floats: -0.00768750301 floats: 0.0121126 floats: 0.00298131746 floats: 0.0117565263 floats: -0.00909942854 floats: 0.00626193872 floats: 0.00104942953 floats: 0.00558419898 floats: -0.00177347963 floats: 0.00779137341 floats: 0.000686824089 floats: -0.00412656041 floats: -0.00158432696 floats: -0.00195238751 floats: -0.0151727404 floats: -0.00118577352 floats: -0.0065637161 floats: -0.00444359193 floats: -0.00191132678 floats: -0.00198358414 } arg { name: "shape" ints: 256 } device_option { }
(no backtrace available)
