### ISSUE TITLE
Image balancing between datasets

### ISSUE THREAD

**Issue by ArutyunovG** [facebookresearch/detectron2#837] opened 2020-02-10 13:14 UTC
## 🚀 Feature

Add feature of balancing number of images between datasets.

## Motivation

In production development it is a common situation to combine datasets from different conditions to solve specific task.

The number of images is usually inbalanced between them, which leads to overfit towards datasets (and, therefore, their conditions) which have the biggest number of images presented.

## Pitch

As an example, here is a diff done by my teammate
https://github.com/ArutyunovG/detectron2/commit/18fad78ef9cfd5b8dcff78468a2d7f91c8cb007a

**Comment by ppwwyyxx** [comment] 2020-02-11 03:13
Duplicate of #734 
The given implementation that duplicates the dicts is not very practical because it would increase the memory usage (which is already quite large) by multiple factors. It also could not support cases where the weights are not integers.

**Closed by ppwwyyxx** 2020-02-11 03:13 UTC
