### ISSUE TITLE
How to use "max_to_keep"

### ISSUE THREAD

**Issue by svideloc** [facebookresearch/detectron2#1873] opened 2020-08-07 14:03 UTC
Hello,

I am just a little unclear on how to use "max_to_keep" from detectron2.checkpoint.PeriodicCheckpointer. Is this something that I should be specifying in the cfg?

Thanks,
Sam

**Comment by wangg12** [comment] 2020-08-07 17:07
I think you need to define a config key by yourself or just add `max_to_keep` to where you call `detectron2.checkpoint.PeriodicCheckpointer`.

**Comment by ppwwyyxx** [comment] 2020-08-09 09:34
@wangg12 's suggestions are great. also a duplicate of #1803

**Closed by ppwwyyxx** 2020-08-09 09:34 UTC
