### ISSUE TITLE
Support for feature extraction after roi align

### ISSUE THREAD

**Issue by ggaemo** [facebookresearch/detectron2#108] opened 2019-10-17 14:03 UTC
## 🚀 Feature
Enable to extract features after roi align operation. 

In the code of detectron2/modeling/meta_arch/rcnn.py
```
        features = self.backbone(images.tensor)
        if self.proposal_generator:
            proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
        else:
            assert "proposals" in batched_inputs[0]
            proposals = [x["proposals"].to(self.device) for x in batched_inputs]
            proposal_losses = {}
        _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
```
I would like the **features** part be available in the api.

## Motivation
Such features can be used as object features in solving the task of visual question answering.

pythia seems to support this. Can Detectron2 be implemented in pythia also?

**Comment by ppwwyyxx** [comment] 2019-10-17 15:36
Duplicate of #5 and already doable.

**Closed as completed by ppwwyyxx** 2019-10-17 15:36 UTC
Labels: duplicate
