### ISSUE TITLE
Run Panoptic Segmentation Training in Detectron2

### ISSUE THREAD

**Issue by VavoTK** [facebookresearch/detectron2#1867] opened 2020-08-05 05:38 UTC
## ❓ How to do something using detectron2

Describe what you want to do, including: 
I am trying to run a panoptic segmentation training. 
1. what inputs you will provide, if any:
     I will provide `.jpg` original images as well as semantic `.png` masks for those images, for the semantic segmentation
     I will also provide a json file in COCO format for the instances in order to use the `register_coco_panoptic_separated` function.
2. what outputs you are expecting:
    I expect to be able to successfully run a training using the `COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml` config file and the corresponding model weights.

Additional Questions: 
     Can I run such a training using only stuff classes? I.E. not have instance information, effectively turning it into a semantic segmentation training? 
     What exactly is the `panoptic_json`?  The documentation claims it is "path to the json panoptic annotation file". 
     Should it be in the COCO format for panoptic segmentation? as described in the coco documentation? https://cocodataset.org/#format-data 
     Why do we need it if have already given the `instances_json` and the path to the sematic files?

**Comment by ppwwyyxx** [comment] 2020-08-05 19:21
Duplicate of https://github.com/facebookresearch/detectron2/issues/1691

* you can train semantic segmentation models. There are implementations such as https://github.com/facebookresearch/detectron2/tree/master/projects/PointRend and https://github.com/facebookresearch/detectron2/tree/master/projects/DeepLab

`panoptic_json` is the json file described and available in https://cocodataset.org/#format-data. It defines one label for each pixel which cannot be obtained from instance+semantic annotations.

**Closed by ppwwyyxx** 2020-08-05 19:21 UTC

**Comment by VavoTK** [comment] 2020-08-05 19:56
> `panoptic_json` is the json file described and available in https://cocodataset.org/#format-data. It defines one label for each pixel which cannot be obtained from instance+semantic annotations.

Yes but which one? There are like 6 different types of COCO annotations? Should it be In the panoptic style or in style of instance segmentation.

**Comment by ppwwyyxx** [comment] 2020-08-05 20:00
It's annotation file for panoptic segmentation that can be downloaded at http://images.cocodataset.org/annotations/panoptic_annotations_trainval2017.zip
