### ISSUE TITLE
Can not train Panoptic-FPN model with the builtin cityscapes dataset

### ISSUE THREAD

**Issue by razvanbarbura** [facebookresearch/detectron2#4116] opened 2022-03-31 21:18 UTC
Hi, I'm trying to train a Panoptic-FPN model using the builtin cityscapes dataset. I followed the instructions regarding the dataset preparation from the official documentation.  The dataset was loaded succesfuly but when I  try to train the model on this dataset I've got the following error:

KeyError: 'instances'

Here is my code:

`from google.colab import drive
drive.mount('/content/drive/')

%cd /content/drive/MyDrive/Detectron2/
! git clone https://github.com/facebookresearch/detectron2.git

!pip install pyyaml==5.1

import torch
TORCH_VERSION = ".".join(torch.__version__.split(".")[:2])
CUDA_VERSION = torch.__version__.split("+")[-1]

import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

import numpy as np
import cv2
import random
from google.colab.patches import cv2_imshow
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
from detectron2.modeling import build_model
from detectron2.checkpoint import DetectionCheckpointer
from detectron2 import model_zoo
import os

cfg = get_cfg()
cfg.merge_from_file("./configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml")
cfg.MODEL.WEIGHTS = "./configs/COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml"

cfg.DATASETS.TRAIN = ("cityscapes_fine_panoptic_train")
cfg.DATASETS.TEST = ("cityscapes_fine_panoptic_val")   
cfg.DATALOADER.NUM_WORKERS = 2
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 256   # faster, and good enough for this toy dataset
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
cfg.OUTPUT_DIR = "./content/drive/MyDrive/MyModels/"
trainer = DefaultTrainer(cfg)

#trainer.resume_or_load(resume=False)
cfg.SNAPSHOT_ITERS = 5 # when checkpoint gets created
#cfg.SOLVER.CHECKPOINT_PERIOD = 5000
trainer.train()
`

Here are the logs with the error:

`[03/31 20:58:39 d2.data.datasets.cityscapes_panoptic]: 18 cities found in 'datasets/cityscapes/leftImg8bit/train'.`
[03/31 20:58:40 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[03/31 20:58:40 d2.data.build]: Using training sampler TrainingSampler
[03/31 20:58:40 d2.data.common]: Serializing 2975 elements to byte tensors and concatenating them all ...
[03/31 20:58:40 d2.data.common]: Serialized dataset takes 4.12 MiB
WARNING [03/31 20:58:40 d2.solver.build]: SOLVER.STEPS contains values larger than SOLVER.MAX_ITER. These values will be ignored.
[03/31 20:58:40 d2.engine.train_loop]: Starting training from iteration 0

ERROR [03/31 20:58:43 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/engine/defaults.py", line 494, in run_step
    self._trainer.run_step()
  File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py", line 126, in forward
    gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
  File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py", line 126, in <listcomp>
    gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
KeyError: 'instances'
[03/31 20:58:43 d2.engine.hooks]: Total training time: 0:00:02 (0:00:00 on hooks)
[03/31 20:58:43 d2.utils.events]:  iter: 0    lr: N/A  max_mem: 6437M
--------------------------------------------------------------------------- `
KeyError                                  Traceback (most recent call last)
[<ipython-input-12-7158b37ffcc7>](https://localhost:8080/#) in <module>()
     26 cfg.SNAPSHOT_ITERS = 5 # when checkpoint gets created
     27 #cfg.SOLVER.CHECKPOINT_PERIOD = 5000
---> 28 trainer.train()
     29 

6 frames
[/content/drive/MyDrive/Detectron2/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py](https://localhost:8080/#) in <listcomp>(.0)
    124         sem_seg_results, sem_seg_losses = self.sem_seg_head(features, gt_sem_seg)
    125 
--> 126         gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
    127         proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
    128         detector_results, detector_losses = self.roi_heads(

**Comment by razvanbarbura** [comment] 2022-04-05 15:21
Full Logs:
[03/31 20:58:39 d2.data.datasets.cityscapes_panoptic]: 18 cities found in 'datasets/cityscapes/leftImg8bit/train'
[03/31 20:58:40 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[03/31 20:58:40 d2.data.build]: Using training sampler TrainingSampler
[03/31 20:58:40 d2.data.common]: Serializing 2975 elements to byte tensors and concatenating them all ...
[03/31 20:58:40 d2.data.common]: Serialized dataset takes 4.12 MiB
WARNING [03/31 20:58:40 d2.solver.build]: SOLVER.STEPS contains values larger than SOLVER.MAX_ITER. These values will be ignored.
[03/31 20:58:40 d2.engine.train_loop]: Starting training from iteration 0

ERROR [03/31 20:58:43 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/engine/train_loop.py", line 149, in train
self.run_step()
File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/engine/defaults.py", line 494, in run_step
self._trainer.run_step()
File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/engine/train_loop.py", line 273, in run_step
loss_dict = self.model(data)
File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
return forward_call(*input, **kwargs)
File "[/content/drive/MyDrive/Detectron2/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py](https://localhost:8080/#)", line 126, in forward
gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
File "/content/drive/MyDrive/Detectron2/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py", line 126, in
gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
KeyError: 'instances'
[03/31 20:58:43 d2.engine.hooks]: Total training time: 0:00:02 (0:00:00 on hooks)
[03/31 20:58:43 d2.utils.events]: iter: 0 lr: N/A max_mem: 6437M
--------------------------------------------------------------------------- `
KeyError Traceback (most recent call last)
in ()
26 cfg.SNAPSHOT_ITERS = 5 # when checkpoint gets created
27 #cfg.SOLVER.CHECKPOINT_PERIOD = 5000
---> 28 trainer.train()
29

6 frames
/content/drive/MyDrive/Detectron2/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py in (.0)
124 sem_seg_results, sem_seg_losses = self.sem_seg_head(features, gt_sem_seg)
125
--> 126 gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
127 proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
128 detector_results, detector_losses = self.roi_heads(

**Comment by ppwwyyxx** [comment] 2022-05-28 22:47
Duplicate of #610

**Closed by ppwwyyxx** 2022-05-28 22:47 UTC
