### ISSUE TITLE
retinanet fails to train with custom dataset.

### ISSUE THREAD

**Issue by bhaskar2443053** [facebookresearch/detectron2#417] opened 2019-11-28 03:02 UTC
hi I am using Detectron2 for the first time.

I successfully trained faster rcnn using custom dataset for object detection. without any problem.

but when i try retinanet, I am stuck with this problem,

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/structures/boxes.py in __getitem__(self, item)
    167         if isinstance(item, int):
    168             return Boxes(self.tensor[item].view(1, -1))
--> 169         b = self.tensor[item]
    170         assert b.dim() == 2, "Indexing on Boxes with {} failed to return a matrix!".format(item)
    171         return Boxes(b)

IndexError: index is out of bounds for dimension with size 0

my config :
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml")
cfg.DATASETS.TRAIN = ("text_train",)
cfg.DATASETS.TEST = ("text_val")   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 8
cfg.MODEL.WEIGHTS = "./models/model_final_b796dc.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 24
cfg.SOLVER.BASE_LR = 0.01
cfg.SOLVER.MAX_ITER = 60000    # 300 iterations seems good enough, but you can certainly train longer
cfg.SOLVER.WARMUP_ITERS = 200
cfg.MODEL.RETINANET.NUM_CLASSES = 8
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)

can anyone help me out ?

**Comment by ppwwyyxx** [comment] 2019-11-28 03:32
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by bhaskar2443053** [comment] 2019-11-28 03:49
my code: for custom data

def get_text_dicts(img_dir,mode):
    
    if mode=='train': 
        df=pd.read_json('/work_ssd/basu/storage07/clean_image/data/clean_image_parsed_t.json')
    else:
        df=pd.read_json('/work_ssd/basu/storage07/clean_image/data/clean_image_parsed_v.json')

    dataset_dicts = []
    for i,v in enumerate(df['image_fn']):
        record = {}
        
        filename = os.path.join(img_dir, v)

        try:
            width,height=Image.open(filename).size
        except:
            continue
        
        record["file_name"] = filename
        record["height"] = height
        record["width"] = width
        
        if width==0 or height==0:
            print(filename)
      
        annos = df["coco_bbox"].iloc[i]
        objs = []
        for j,anno in enumerate(annos):

            obj = {
                "bbox": [anno['left'], anno['top'], anno['width'], anno['height']],
                "bbox_mode": BoxMode.XYWH_ABS,
                "category_id": cls_map[df['class'].iloc[i][j]],
                "iscrowd": 0
            }
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    return dataset_dicts

from detectron2.data import DatasetCatalog, MetadataCatalog
for d in ["train", "val"]:
    DatasetCatalog.register("text_" + d, lambda d=d: get_text_dicts(img_dir , d))
    MetadataCatalog.get("text_" + d).thing_classes = ['BGFrame', 'ColorBar', 'DigitalFrameOther', 'DigitalFrameWhite', 'DigitalText', 'NaturalFrame', 'NaturalText', 'Package']

my config code :
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml")
cfg.DATASETS.TRAIN = ("text_train",)
cfg.DATASETS.TEST = ("text_val")   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 8
cfg.MODEL.WEIGHTS = "./models/model_final_b796dc.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 24
cfg.SOLVER.BASE_LR = 0.01
cfg.SOLVER.MAX_ITER = 60000    # 300 iterations seems good enough, but you can certainly train longer
cfg.SOLVER.WARMUP_ITERS = 200
cfg.MODEL.RETINANET.NUM_CLASSES = 8
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)



The error that i get when i execute trainer.train()


[11/28 02:56:09 d2.engine.train_loop]: Starting training from iteration 0
[11/28 02:56:46 d2.utils.events]: eta: 1 day, 3:15:26  iter: 19  total_loss: 1.908  loss_cls: 1.091  loss_box_reg: 0.870  time: 1.7636  data_time: 0.1073  lr: 0.000959  max_mem: 23167M
[11/28 02:57:04 d2.engine.hooks]: Overall training speed: 27 iterations in 0:00:49 (1.8278 s / it)
[11/28 02:57:04 d2.engine.hooks]: Total training time: 0:00:49 (0:00:00 on hooks)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-3435b262f1ae> in <module>
----> 1 trainer.train()

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/engine/defaults.py in train(self)
    352             OrderedDict of results, if evaluation is enabled. Otherwise None.
    353         """
--> 354         super().train(self.start_iter, self.max_iter)
    355         if hasattr(self, "_last_eval_results") and comm.is_main_process():
    356             verify_results(self.cfg, self._last_eval_results)

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    130                 for self.iter in range(start_iter, max_iter):
    131                     self.before_step()
--> 132                     self.run_step()
    133                     self.after_step()
    134             finally:

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/engine/train_loop.py in run_step(self)
    210         If your want to do something with the losses, you can wrap the model.
    211         """
--> 212         loss_dict = self.model(data)
    213         losses = sum(loss for loss in loss_dict.values())
    214         self._detect_anomaly(losses, loss_dict)

/work_ssd/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/modeling/meta_arch/retinanet.py in forward(self, batched_inputs)
    134 
    135         if self.training:
--> 136             gt_classes, gt_anchors_reg_deltas = self.get_ground_truth(anchors, gt_instances)
    137             return self.losses(gt_classes, gt_anchors_reg_deltas, box_cls, box_delta)
    138         else:

/work_ssd/anaconda3/envs/fastai/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_no_grad(*args, **kwargs)
     47         def decorate_no_grad(*args, **kwargs):
     48             with self:
---> 49                 return func(*args, **kwargs)
     50         return decorate_no_grad
     51 

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/modeling/meta_arch/retinanet.py in get_ground_truth(self, anchors, targets)
    235 
    236             # ground truth box regression
--> 237             matched_gt_boxes = targets_per_image[gt_matched_idxs].gt_boxes
    238             gt_anchors_reg_deltas_i = self.box2box_transform.get_deltas(
    239                 anchors_per_image.tensor, matched_gt_boxes.tensor

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/structures/instances.py in __getitem__(self, item)
    124         ret = Instances(self._image_size)
    125         for k, v in self._fields.items():
--> 126             ret.set(k, v[item])
    127         return ret
    128 

/work_ssd/basu/storage07/clean_image/code/detectron2_repo/detectron2/structures/boxes.py in __getitem__(self, item)
    167         if isinstance(item, int):
    168             return Boxes(self.tensor[item].view(1, -1))
--> 169         b = self.tensor[item]
    170         assert b.dim() == 2, "Indexing on Boxes with {} failed to return a matrix!".format(item)
    171         return Boxes(b)

IndexError: index is out of bounds for dimension with size 0



I don't get this error with config code and same data

from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml")
cfg.DATASETS.TRAIN = ("text_train",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.NUM_WORKERS = 8
cfg.MODEL.WEIGHTS = "./model_final_721ade.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 8
cfg.SOLVER.BASE_LR = 0.0025
cfg.SOLVER.MAX_ITER = 3500    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 8  # only has one class (ballon)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)


my env:
sys.platform              linux
Python                    3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Numpy                     1.16.5
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1                   Tesla V100-SXM2-32GB
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.168
Pillow                    6.1.0
cv2                       3.4.2
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment] 2019-11-28 10:01
Did you change `FILTER_EMPTY_ANNOTATIONS` or use a different data loader?

**Comment by bhaskar2443053** [comment] 2019-11-28 10:08
> Did you change `FILTER_EMPTY_ANNOTATIONS` or use a different data loader?

I did not change `FILTER_EMPTY_ANNOTATIONS` 
i use the exact same data as i used for faster RCNN.
even if i change the model cfg to Faster rcnn, and add roi head in the same notebook and same data. it works

**Comment by ppwwyyxx** [comment] 2019-11-28 10:27
>  if width==0 or height==0:
        print(filename)

Did this print anything?
Faster R-CNN have more capabilities than RetinaNet. RetinaNet does not currently work on images with no boxes. If any boxes have non-positive sizes they will be removed and may lead to the error.

**Comment by bhaskar2443053** [comment] 2019-11-28 10:40
> > if width==0 or height==0:
> > print(filename)
> 
> Did this print anything?
> Faster R-CNN have more capabilities than RetinaNet. RetinaNet does not currently work on images with no boxes. If any boxes have non-positive sizes they will be removed and may lead to the error.

i have not check for that, i ll filter such images, and try to re run.
thanks for the help.

**Comment by bhaskar2443053** [comment] 2019-11-29 02:08
> > if width==0 or height==0:
> > print(filename)
> 
> Did this print anything?
> Faster R-CNN have more capabilities than RetinaNet. RetinaNet does not currently work on images with no boxes. If any boxes have non-positive sizes they will be removed and may lead to the error.

I removed all images with no bbox, all the images with zero size.
still the error is same

**Comment by ppwwyyxx** [comment] 2019-11-30 19:53
I still think it's caused by images with no instances, and it should be fixed in f64a1695e586f306a424a0b0d60740c3a1dc122d. Please re-include the details if issues still exist with this commit.

**Comment by bhaskar2443053** [comment] 2019-12-06 09:24
Thank you the problem was solved :)

**Closed** 2019-12-06 17:42 UTC
Labels: enhancement

**Comment by Syorst** [comment] 2020-08-28 07:58
> Thank you the problem was solved :)

HI,could you share you cfg  when you use retinanet_R_50_FPN_1x.yaml?thank you
