### ISSUE TITLE
Error using detectron2.export.TracingAdaptor with torch.jit.trace

### ISSUE THREAD

**Issue by coderAddy** [facebookresearch/detectron2#3234] opened 2021-07-08 22:18 UTC
Using detectron2.export.TracingAdaptor to generate a flattened input/output version of the mode, followed by torch.jit.trace results in the error shown below.

Context: I am trying to convert detectron2's maskrcnn to a flattened input/output version, in order to export the model in training mode using torch.onnx.export() function.

## Instructions To Reproduce the Issue:

Code:
```
modelYaml = "COCO-InstanceSegmentation/mask_rcnn_R_50_C4_3x_.yaml"
model = model_zoo.get(modelYaml, trained=True)
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file(modelYaml))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(modelYaml)

data_loader = detectron2.data.build_detection_train_loader(cfg, DatasetMapper(cfg, is_train=True), num_workers=0,total_batch_size=1)
data = next(iter(data_loader))

adapter = detectron2.export.TracingAdapter(torch_model, first_batch, allow_non_tensor=True)

traced = torch.jit.trace(adapter, adapter.flattened_inputs)
```

Error:

```
/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/detectron2/export/flatten.py:283: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (args != self.flattened_inputs):
Traceback (most recent call last):
  File "/Users/ad/PycharmProjects/maskrcnnExport/exportMask.py", line 75, in <module>
    traced = torch.jit.trace(adapter, adapter.flattened_inputs)
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 966, in trace_module
    _module_class,
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 335, in _check_trace
    _compilation_unit=torch._C.CompilationUnit(),
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/detectron2/export/flatten.py", line 283, in forward
    if (args != self.flattened_inputs):
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

## Expected behavior:
The model should be traced without errors.

## Environment:

```
sys.platform           darwin
Python                 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) [GCC Clang 10.0.0 ]
numpy                  1.19.2
detectron2             0.4.1 @/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/detectron2
Compiler               clang 11.0.0
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.8.0 @/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 8.2.0
torchvision            0.9.0 @/Users/ad/anaconda3/envs/torch18/lib/python3.6/site-packages/torchvision
fvcore                 0.1.5.post20210630
iopath                 0.1.8
cv2                    4.5.2
---------------------  ---------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 4.2
  - C++ Version: 201402
  - clang 12.0.0
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode-12.GM.seed.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=OFF, 
```

**Comment by ppwwyyxx** [comment] 2021-07-08 23:47
Tracing of the model in training mode is not supported, and when I run the above code after fixing imports and wrong variable names, it produces the following error (which is expected):
```
  File "/home/projects/detectron2/detectron2/structures/masks.py", line 408, in <listcomp>
    rasterize_polygons_within_box(poly, box.numpy(), mask_size)
  File "/home/projects/detectron2/detectron2/structures/masks.py", line 77, in rasterize_polygons_within_box
    p[0::2] *= ratio_w
TypeError: unsupported operand type(s) for *=: 'numpy.ndarray' and 'Tensor'
```

The code correcting missing pieces is:
```python
modelYaml = "COCO-InstanceSegmentation/mask_rcnn_R_50_C4_3x.yaml"
model = model_zoo.get(modelYaml, trained=True)
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file(modelYaml))
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(modelYaml)

data_loader = detectron2.data.build_detection_train_loader(cfg, DatasetMapper(cfg, is_train=True), num_workers=0,total_batch_size=1)
data = next(iter(data_loader))

with EventStorage():
    adapter = export.TracingAdapter(model, data, allow_non_tensor=True)
    traced = torch.jit.trace(adapter, adapter.flattened_inputs)
```

Since the outcome is expected, I'm closing the issue unless there is other code to reproduce unexpected outcome. 

I did notice some problems in TracingAdapter that could produce incorrect errors similar to what you report, but not by the above code. This will be fixed in https://github.com/facebookresearch/detectron2/pull/3235 to provide better error messages.

**Closed by ppwwyyxx** 2021-07-08 23:47 UTC

**Comment by coderAddy** [comment] 2021-07-09 12:56
@ppwwyyxx, Thanks for the response. I had 2 clarifications here - 

1. Using the tracer in eval mode (after calling  model.eval()), still gives me an error. Is this the error you're talking about in #3235 ?

```
if (args != self.flattened_inputs):
Traceback (most recent call last):
  File "/Users/anchitdhar/PycharmProjects/maskrcnnExport/exportMask.py", line 76, in <module>
    traced = torch.jit.trace(adapter, adapter.flattened_inputs)
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 966, in trace_module
    _module_class,
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 335, in _check_trace
    _compilation_unit=torch._C.CompilationUnit(),
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/torch/nn/modules/module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/Users/anchitdhar/anaconda3/envs/torch18/lib/python3.6/site-packages/detectron2/export/flatten.py", line 283, in forward
    if (args != self.flattened_inputs):
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

2.  My use case here is to export the maskrcnn network to ONNX(either in train or eval mode) with batchnorm layers retained. All the export options that I've tried(Caffe2Tracer+export_onnx, export_onnx_model) optimize out the batchnorm layer. Is there anything else which I could try?

**Comment by ppwwyyxx** [comment] 2021-07-09 22:40
> Using the tracer in eval mode (after calling model.eval()), still gives me an error

This should be fixed by the linked PR. If not please provide code that reproduces it.

Many of our models don't use BatchNorm (but FrozenBatchNorm) anyway. For models that do contain BatchNorm, using TracingAdapter + torch.jit.trace will probably produce a model with BN layers.
However this doesn't say anything about ONNX as we don't have official support for ONNX.
