### ISSUE TITLE
Detectron2 for Windows 10

### ISSUE THREAD

**Issue by GiovanniPasq** [facebookresearch/detectron2#307] opened 2019-11-12 18:04 UTC
i want to use detectron2 with windows 10. I have gtx 1050 and my setup is:
anaconda 1.9.7
python 3.7
pytorch 1.3.1
torchvision 0.4.2
cuda toolkit 10.1

I have followed the installation guide and after i downloaded the repository when i try to install it with the command pip install -e detectron2_repo i have this big error (I only wrote the final piece because everything didn't fit) :

    C:/Users/iviog/Anaconda3/lib/site-packages/torch/include\torch/csrc/autograd/custom_function.h(129): warning: field of class type without a DLL interface used in a class with a DLL interface

    1 error detected in the compilation of "C:/Users/iviog/AppData/Local/Temp/tmpxft_000023f0_00000000-10_deform_conv_cuda.cpp1.ii".
    deform_conv_cuda.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\iviog\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iviog\\detectron2_repo\\setup.py'"'"'; __file__='"'"'C:\\Users\\iviog\\detectron2_repo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

I have not found nothing on internet, can anyone help me? or i must install it on linux? =(

**Comment by ganmingshunron** [comment] 2019-11-13 01:25
#9 
Tried conansherry's solution and worked well for me.

**Comment by ppwwyyxx** [comment] 2019-11-13 04:35
Closing as a duplicate of #9

**Closed by ppwwyyxx** 2019-11-13 04:35 UTC
