### ISSUE TITLE
Adding new classes to model

### ISSUE THREAD

**Issue by rakesh4real** [facebookresearch/detectron2#2626] opened 2021-02-15 11:05 UTC
## 🚀 Feature

Add new class to a trained model.

## Motivation & Examples

Imagine model has been trained on `25` classes for 10 hrs and then we have to add `5` more classes. Will we have to train for other 10 hrs? It becomes significant if we have to add more classes daily.

How to train new classes with minimal amount of time?

**My solution is:**

> I am trying to build separate models for each category and I will run inference on same image using those model. So, the time taken will be `n_images x n_classes x time_taken_for_single_inference`

Is there a better option that can be added as feature?

**Comment by ppwwyyxx** [comment] 2021-02-16 06:13
Duplicate of #1024, #2124

**Closed by ppwwyyxx** 2021-02-16 06:13 UTC
Labels: enhancement
