### ISSUE TITLE
 Exception during training - NotImplementedError: Caught NotImplementedError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by PurveshChhajed** [facebookresearch/detectron2#2195] opened 2020-10-26 13:21 UTC
**On running following piece of code :** 

from detectron2.engine import DefaultTrainer

cfg = get_cfg()
cfg.INPUT.MASK_FORMAT='bitmask'
#cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x.yaml"))
cfg.merge_from_file(model_zoo.get_config_file("Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml"))
cfg.DATASETS.TRAIN = ("v6",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
#cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_C4_1x.yaml")# Let training initialize from model zoo
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("Misc/cascade_mask_rcnn_X_152_32x8d_FPN_IN5k_gn_dconv.yaml")
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 3500   # 300 iterations seems good enough for this toy dataset; you will need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 300
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

**got the following error :**

[10/26 18:26:00 d2.engine.train_loop]: Starting training from iteration 0
/home/user1/.local/lib/python3.6/site-packages/detectron2/data/detection_utils.py:412: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  torch.stack([torch.from_numpy(np.ascontiguousarray(x)) for x in masks])
ERROR [10/26 18:26:00 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 140, in train
    self.run_step()
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 220, in run_step
    data = next(self._data_loader_iter)
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/data/common.py", line 142, in __iter__
    for d in self.dataset:
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/user1/.local/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
NotImplementedError: Caught NotImplementedError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/data/common.py", line 41, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/data/dataset_mapper.py", line 183, in __call__
    instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/structures/masks.py", line 204, in get_bounding_boxes
    raise NotImplementedError
NotImplementedError

[10/26 18:26:00 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-25-02eb9086db00> in <module>
     18 trainer = DefaultTrainer(cfg)
     19 trainer.resume_or_load(resume=False)
---> 20 trainer.train()

~/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py in train(self)
    397             OrderedDict of results, if evaluation is enabled. Otherwise None.
    398         """
--> 399         super().train(self.start_iter, self.max_iter)
    400         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    401             assert hasattr(

~/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    138                 for self.iter in range(start_iter, max_iter):
    139                     self.before_step()
--> 140                     self.run_step()
    141                     self.after_step()
    142             except Exception:

~/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py in run_step(self)
    218         If you want to do something with the data, you can wrap the dataloader.
    219         """
--> 220         data = next(self._data_loader_iter)
    221         data_time = time.perf_counter() - start
    222 

~/.local/lib/python3.6/site-packages/detectron2/data/common.py in __iter__(self)
    140 
    141     def __iter__(self):
--> 142         for d in self.dataset:
    143             w, h = d["width"], d["height"]
    144             bucket_id = 0 if w > h else 1

~/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    361 
    362     def __next__(self):
--> 363         data = self._next_data()
    364         self._num_yielded += 1
    365         if self._dataset_kind == _DatasetKind.Iterable and \

~/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _next_data(self)
    987             else:
    988                 del self._task_info[idx]
--> 989                 return self._process_data(data)
    990 
    991     def _try_put_index(self):

~/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1012         self._try_put_index()
   1013         if isinstance(data, ExceptionWrapper):
-> 1014             data.reraise()
   1015         return data
   1016 

~/.local/lib/python3.6/site-packages/torch/_utils.py in reraise(self)
    393             # (https://bugs.python.org/issue2651), so we work around it.
    394             msg = KeyErrorMessage(msg)
--> 395         raise self.exc_type(msg)

NotImplementedError: Caught NotImplementedError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user1/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/data/common.py", line 41, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/data/dataset_mapper.py", line 183, in __call__
    instances.gt_boxes = instances.gt_masks.get_bounding_boxes()
  File "/home/user1/.local/lib/python3.6/site-packages/detectron2/structures/masks.py", line 204, in get_bounding_boxes
    raise NotImplementedError
NotImplementedError

**Comment by ppwwyyxx** [comment] 2020-10-27 02:03
Duplicate of #2180

**Closed by ppwwyyxx** 2020-10-27 02:03 UTC
