### ISSUE TITLE
None object error while using DefaultPredictor

### ISSUE THREAD

**Issue by wacimbel** [facebookresearch/detectron2#1280] opened 2020-04-22 08:49 UTC
I've observed an issue when loading a model with a `detectron2.engine.DefaultPredictor` object. 
In the `detectron2.checkpoint.DetectionCheckopinter` class, the output of the `Checkpointer._load_model` method is used and looped on, whereas this method doesn't return anything (such as `output = checkpointer_instance._load_model()`). 

An `AttributeError` error is raised and makes it impossible to use the `DefaultPredictor`.

## Instructions To Reproduce the Issue:

A `DefaultPredictor` is instanciated, to use a pretrained Panoptic Segmentation model. Below is a simplified version of my code.

```python
from dataclasses import dataclass
from enum import Enum

import numpy as np
from detectron2.config import get_cfg
from detectron2.engine import DefaultPredictor
from detectron2.model_zoo import model_zoo

class ModelType(Enum):
    PANOPTIC_SEGMENTATION_LARGE = "COCO-PanopticSegmentation/panoptic_fpn_R_101_3x.yaml"
    PANOPTIC_SEGMENTATION_SMALL = "COCO-PanopticSegmentation/panoptic_fpn_R_50_1x.yaml"
    DETECTION_FASTER_RCNN = "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
    DETECTION_FAST_RCNN = "COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml"
    INSTANCE_SEGMENTATION_MASK_RCNN_SMALL = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
    INSTANCE_SEGMENTATION_MASK_RCNN_LARGE = "COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml"

@dataclass
class ImageExtractor:
    model_type: ModelType = ModelType.PANOPTIC_SEGMENTATION_LARGE
    model_path: str = None

    def __post_init__(self):
        self.config = get_cfg()
        self.config.merge_from_file(model_zoo.get_config_file(self.model_type.value))

        if self.model_path is not None:
            self.config.MODEL.WEIGHTS = self.model_path
        else:
            self.config.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(self.model_type.value)

        self.predictor = DefaultPredictor(self.config)

    def extract(self, image: np.ndarray):
        prediction = self.predictor(image)
        return prediction
```

2. With this code, I ran the following python instructions to try the whole setup: 
```python
extractor = ImageExtractor()
exractor.extract(np.random.rand(100, 100, 3))
```

3. The following is raised.
```
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "<private_path>/panoptic-detection/tests/extractors/test_panoptic_extractor.py", line 25, in test_predictions
    self.predict_panoptic(self.image)
  File "<private_path>/panoptic-detection/tests/extractors/test_panoptic_extractor.py", line 31, in predict_panoptic
    model_type=ModelType.PANOPTIC_SEGMENTATION_SMALL,
  File "<string>", line 6, in __init__
  File "<private_path>/panoptic-detection/panoptic_detection/extractors/image_extractor.py", line 34, in __post_init__
    self.predictor = DefaultPredictor(self.config)
  File "<private_path>/panoptic-detection/venv/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 185, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "<private_path>/panoptic-detection/venv/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 104, in load
    self._load_model(checkpoint)
  File "<private_path>/panoptic-detection/venv/lib/python3.7/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 68, in _load_model
    incompatible.missing_keys.remove(k)
AttributeError: 'NoneType' object has no attribute 'missing_keys'
```

4. Investigation

Deep diving into this issue, the bug seems to come from the following class: 

```python

class DetectionCheckpointer(Checkpointer):
    """
    Same as :class:`Checkpointer`, but is able to handle models in detectron & detectron2
    model zoo, and apply conversions for legacy models.
    """

    def __init__(self, model, save_dir="", *, save_to_disk=None, **checkpointables):
        is_main_process = comm.is_main_process()
        super().__init__(
            model,
            save_dir,
            save_to_disk=is_main_process if save_to_disk is None else save_to_disk,
            **checkpointables,
        )

    def _load_file(self, filename):
        if filename.endswith(".pkl"):
            with PathManager.open(filename, "rb") as f:
                data = pickle.load(f, encoding="latin1")
            if "model" in data and "__author__" in data:
                # file is in Detectron2 model zoo format
                self.logger.info("Reading a file from '{}'".format(data["__author__"]))
                return data
            else:
                # assume file is from Caffe2 / Detectron1 model zoo
                if "blobs" in data:
                    # Detection models have "blobs", but ImageNet models don't
                    data = data["blobs"]
                data = {k: v for k, v in data.items() if not k.endswith("_momentum")}
                return {"model": data, "__author__": "Caffe2", "matching_heuristics": True}

        loaded = super()._load_file(filename)  # load native pth checkpoint
        if "model" not in loaded:
            loaded = {"model": loaded}
        return loaded

    def _load_model(self, checkpoint):
        if checkpoint.get("matching_heuristics", False):
            self._convert_ndarray_to_tensor(checkpoint["model"])
            # convert weights by name-matching heuristics
            model_state_dict = self.model.state_dict()
            align_and_update_state_dicts(
                model_state_dict,
                checkpoint["model"],
                c2_conversion=checkpoint.get("__author__", None) == "Caffe2",
            )
            checkpoint["model"] = model_state_dict
        # for non-caffe2 models, use standard ways to load it
        incompatible = super()._load_model(checkpoint)

        model_buffers = dict(self.model.named_buffers(recurse=False))
        for k in ["pixel_mean", "pixel_std"]:
            # Ignore missing key message about pixel_mean/std.
            # Though they may be missing in old checkpoints, they will be correctly
            # initialized from config anyway.
            if k in model_buffers:
                try:
                    incompatible.missing_keys.remove(k)
                except ValueError:
                    pass
        return incompatible
```

In the code above, in the `_load_model` method, the super class method is called : 
```python
incompatible = super()._load_model(checkpoint)
```

But this method doesn't return anything, so that the `incompatible` variable is None.
This `incompatible` variable is then used in the following lines : 
```python
model_buffers = dict(self.model.named_buffers(recurse=False))
        for k in ["pixel_mean", "pixel_std"]:
            # Ignore missing key message about pixel_mean/std.
            # Though they may be missing in old checkpoints, they will be correctly
            # initialized from config anyway.
            if k in model_buffers:
                try:
                    incompatible.missing_keys.remove(k)
                except ValueError:
                    pass
        return incompatible
```

## Environment:

I'm using the following versions: 
- `detectron2`: 0.1.1
- `pytorch`: 1.4.0

**Comment by ppwwyyxx** [comment] 2020-04-22 09:01
Duplicate of #1267.

**Closed by ppwwyyxx** 2020-04-22 09:01 UTC
