### ISSUE TITLE
Average Recall values not saved

### ISSUE THREAD

**Issue by hazemy** [facebookresearch/detectron2#2143] opened 2020-10-18 15:58 UTC
Hello,
I noticed that the **Average Recall** values from the `COCOEvaluator` are neither logged (through `setup_logger()`), nor written to the `metrics.json`. They are only printed on the terminal during training as such:

> Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.605
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.755
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.675
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.311
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.669
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.490
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.733
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.733
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.585
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.773

Is this the intended behavior? Is there a particular reason why the recall values are not saved?

**Comment by ppwwyyxx** [comment] 2020-10-18 19:21
Duplicate of #1296

**Closed by ppwwyyxx** 2020-10-18 19:21 UTC
