### ISSUE TITLE
How can we use faster-rcnn with rotated bounding boxes?

### ISSUE THREAD

**Issue by UsmannK** [facebookresearch/detectron2#209] opened 2019-10-31 23:10 UTC
## ❓ Questions and Help

General questions about detectron2.

Rotated bounding boxes are mentioned in the README. Are there example configs available that make use of this feature? I can't seem to find any in the current example config set. Thanks!

**Comment by ppwwyyxx** [comment] 2019-11-01 00:12
duplicate of #21

**Closed by ppwwyyxx** 2019-11-01 00:12 UTC
