### ISSUE TITLE
how to get mask for individual segmented parts in DensePose

### ISSUE THREAD

**Issue by SriRamGovardhanam** [facebookresearch/detectron2#1348] opened 2020-05-02 16:17 UTC
If you are aware of Matterports Mask RCNN, there we can generate mask for segmented parts.
Suppose if i need segmented parts individually, without any background how can we get in detectron2?

for reference here is the image:
![download](https://user-images.githubusercontent.com/35695549/80869492-61c1ff00-8cbe-11ea-9947-96b8869e69b5.png)

anyone please let me know if there any way!
@vkhalidov please help me with this!

**Comment by ppwwyyxx** [comment] 2020-05-03 17:51
Duplicate of #924 #681 #356

**Closed by ppwwyyxx** 2020-05-03 17:51 UTC

**Comment by SriRamGovardhanam** [comment] 2020-05-07 21:58
i tried using `outputs['instances'].pred_masks` 
```
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
cfg = get_cfg()
add_densepose_config(cfg)

# add project-specific config (e.g., TensorMask) here if you're not running a model in detectron2's core library
cfg.merge_from_file("/content/detectron2/projects/DensePose/configs/densepose_rcnn_R_101_FPN_s1x.yaml")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
# Find a model from detectron2's model zoo. You can use the https://dl.fbaipublicfiles... url as well
cfg.MODEL.WEIGHTS = "https://dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_101_FPN_s1x/165712084/model_final_c6ab63.pkl"
predictor = DefaultPredictor(cfg)
outputs = predictor(im)
outputs['instances'].pred_masks
#outputs = model(input)
```
it gives me the following error:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-73-a49b1f86d4a4> in <module>()
     12 predictor = DefaultPredictor(cfg)
     13 outputs = predictor(im)
---> 14 outputs['instances'].pred_masks
     15 #outputs = model(input)
     16 

/content/detectron2/detectron2/structures/instances.py in __getattr__(self, name)
     58     def __getattr__(self, name: str) -> Any:
     59         if name == "_fields" or name not in self._fields:
---> 60             raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
     61         return self._fields[name]
     62 

AttributeError: Cannot find field 'pred_masks' in the given Instances!
```

how can i get all the individual 14 parts segmented masks separately
please look into this @ppwwyyxx
