### ISSUE TITLE
RuntimeError: CUDA error: invalid device function 

### ISSUE THREAD

**Issue by ZYN-guy** [facebookresearch/detectron2#281] opened 2019-11-09 03:24 UTC
Run:
 python tools/train_net.py \
> --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
> SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025
information:
sys.platform                                         linux
Python                                                 3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
Numpy                                                1.16.4
Detectron2 Compiler                          GCC 5.4
Detectron2 CUDA Compiler               10.0
DETECTRON2_ENV_MODULE         <not set>
PyTorch                                             1.3.1
PyTorch Debug Build                         False
torchvision                                         0.4.1
CUDA available                                 True
GPU 0                                               GeForce RTX 2080 Ti
CUDA_HOME                                   /usr/local/cuda
NVCC                                                Cuda compilation tools, release 10.0, V10.0.130
Pillow                                                  6.1.0
cv2                                                    4.1.0
Result:
RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at /home/zhangyanan/Desktop/pytorch/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:361)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f0affb93687 in /home/zhangyanan/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)

段错误 (核心已转储)

**Comment by ppwwyyxx** [comment] 2019-11-09 03:27
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ZYN-guy** [comment] 2019-11-09 13:28
> Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

I upgraded pytorch 1.2 to 1.3.1, ‘conda install pytorch torchvision cudatoolkit=10.1 -c pytorch’,There was an error when I ran the code. I don't know how to solve this problem. Can you give me some suggestions？
Thanks

**Comment by ppwwyyxx** [comment] 2019-11-09 13:29
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ZYN-guy** [comment] 2019-11-09 13:35
> Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).
There was an error when I was training the data：RuntimeError: CUDA error: invalid device function with 段错误 (核心已转储)

**Comment by ppwwyyxx** [comment] 2019-11-09 13:36
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

Here is the issue template if you click the link:

If you do not know the root cause of the problem / bug, and wish someone to help you, please
include:

## How To Reproduce the Issue

1. what changes you made (`git diff`) or what code you wrote
2. what exact command you run
3. what you observed (including the full logs):
```
<put logs in a formatted block>
```

## Expected behavior

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to work better, note that we do not help you train your model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in detectron2 model zoo.
(2) It indicates a detectron2 bug.

## Environment

Please paste the output of `python -m detectron2.utils.collect_env`.
If detectron2 hasn't been successfully installed,
use `python detectron2/utils/collect_env.py`.

**Comment by ZYN-guy** [comment] 2019-11-09 14:08
Thanks!
I didn't change any code， I ran the code you provided ——python tools/train_net.py \
	--config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml \
	SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025
Result：RuntimeError: CUDA error: invalid device function .

**Comment by ZYN-guy** [comment] 2019-11-09 14:12
use `python detectron2/utils/collect_env.py`

Result:

PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by ppwwyyxx** [comment] 2019-11-09 14:15
As the issue template says, please include full logs.
The logs for your environment information is also incomplete.

**Comment by SIakovlev** [comment] 2019-11-10 05:49
I had the same error. Rebuilding detectron2 helped:

1) remove `/build` dir from the repository root 
2) Run `python setup.py build develop` 

I did this inside my conda environment.

**Comment by ppwwyyxx** [comment] 2019-11-15 04:55
Closing as the information requested in the issue template is still not provided.

**Closed by ppwwyyxx** 2019-11-15 04:55 UTC
