### ISSUE TITLE
How to extract features?

### ISSUE THREAD

**Issue by fuxiaoaaa** [facebookresearch/detectron2#654] opened 2020-01-09 03:21 UTC
For the instance detection , I want to extract instances features before softmax , not the classficition results , what should I do?
NOTE:
1. I want to use demo.py to extract one picture's instance feature .
2. I tried to change "self.model" to "self.model[:-1]" , but the "self.model" is <class'detectron2.modeling.meta_arch.rcnn.GeneralizedRCNN'>, I can't remove the fn layers .
So, what should I do?

**Comment by ppwwyyxx** [comment] 2020-01-09 03:43
Duplicate of #5 or #628

**Closed by ppwwyyxx** 2020-01-09 03:43 UTC
