### ISSUE TITLE
Different dataset size with register_coco_instance() and DatasetCatalog.register()

### ISSUE THREAD

**Issue by Shobhit20** [facebookresearch/detectron2#1978] opened 2020-08-28 13:29 UTC
I am getting different dataset sizes when loading the dataset with register_coco_instances functionality and the DatasetCatalog.register() when done in a loop as described in multiple blog posts regarding instance segmentation using detectron2. 

```
register_coco_instances_manual("damage_train", {}, "damage/train.json", "")
register_coco_instances_manual("damage_test", {}, "damage/test.json", "")
print(len(DatasetCatalog.get("damage_train")))
```
The output for this comes out to be 10683 which is my train data size. However
```
data_list = ["train", "test"]
for d in data_list]:
     DatasetCatalog.register("damage_"+d, lambda: load_damage_instances("damage/"+d+'.json'))
     MetadataCatalog.get("damage_"+d).set(thing_classes=["x","y", "z"])

print(len(DatasetCatalog.get("damage_train")))
```
executing in this way yields the length to be 1170 which is the size of my test dataset. Is the data registering doing some sort of lazy loading and indexes the data only when an action is called on top of it?

Also when the data_list is replaced with just ["train"] and a the same train data is registered by a different name (say damage_train_1) for some reason both the damage_train, and the damage_train_1 yield data count to be 10683. To put this into perspective - 
```
for d in ["train", "test"]:
    DatasetCatalog.register("damage_"+d, lambda: load_damage_instances("damage/"+d+'.json'))
    MetadataCatalog.get("damage_"+d).set(thing_classes=["x","y", "z"])

print(len(DatasetCatalog.get("damage_train")))
[Output]: 1170

for d in ["train"]:
    DatasetCatalog.register("damage_"+d+"_1", lambda: load_damage_instances("damage/"+d+'.json'))
    MetadataCatalog.get("damage_"+d+"_1").set(thing_classes=["x","y", "z"])

print(len(DatasetCatalog.get("damage_train")))
[Output]: 10683

print(len(DatasetCatalog.get("damage_train_1")))
[Output]: 10683
```

Really confused as to how this is happening. How is the data with the previously registered data getting updated when get is called on top of it?

**Comment by ppwwyyxx** [comment] 2020-08-28 19:12
Duplicate of #611

**Closed by ppwwyyxx** 2020-08-28 19:12 UTC
