### ISSUE TITLE
Augmentations

### ISSUE THREAD

**Issue by LyulinAnton** [facebookresearch/detectron2#392] opened 2019-11-25 13:34 UTC
Hello!
How can I add augmentations?

**Comment by Diyago** [comment] 2019-11-25 13:57
same question. There is option in config for test:

```
TEST:
  AUG:
```

**Comment by LyulinAnton** [comment] 2019-11-25 13:59
Can I add augmentations for train?

**Comment by ppwwyyxx** [comment] 2019-11-25 19:07
seems a duplicate of #244

**Closed by ppwwyyxx** 2019-11-25 19:07 UTC
