### ISSUE TITLE
Adding negative samples for object detection

### ISSUE THREAD

**Issue by ifahim** [facebookresearch/detectron2#1576] opened 2020-06-09 23:43 UTC
I am trying to solve a a pure object detection (No masks) problem using this awesome tool. For my custom task, I see that 90% of the images are removed as these images do not have any bbox.  Is there a way to include these negative samples for detection only tasks?

**Comment by ppwwyyxx** [comment] 2020-06-10 07:54
duplicate of #712

**Closed by ppwwyyxx** 2020-06-10 07:54 UTC
