### ISSUE TITLE
How to load a pre-trained model in torchvision to detectron2

### ISSUE THREAD

**Issue by kaleidoscopical** [facebookresearch/detectron2#1083] opened 2020-03-21 13:01 UTC
https://github.com/facebookresearch/detectron2/blob/60ee6b2c3450f7c4aa7758198429e2ece65d7f03/detectron2/checkpoint/catalog.py#L14-L17

I am confused by above claims when trying to load a torchvision model. Are these claims still true? I found the `forward()` implementation without the grad in `FrozenBatchNorm2d` is same as the implementation in the PyTorch.

If I would like to use a pre-trained model in torchvision, what should I do? Could anyone provide me with some hints? 

BTW, I have tried to use the config `configs/PascalVOC-Detection/faster_rcnn_R_50_C4.yaml` and only change the path of the pre-trained weights. I copied the weights of torchvision to their corresponding names in the `resnet/backbone.py` of detectron2. I have tried to reverse the channels of first conv and set `STRIDE_IN_1X1=False`. What else should I do?

**Comment by ppwwyyxx** [comment] 2020-03-21 19:11
Duplicate of #778

The code you linked to is unrelated to torchvision models.

**Closed by ppwwyyxx** 2020-03-21 19:11 UTC

**Comment by kaleidoscopical** [comment] 2020-03-21 19:53
Still no available solution there.

The code I linked to is related to your pre-trained model. I wonder whether it is still instructive for anyone else who wishes to convert torchvision models to the format used in detectron2.

**Comment by ppwwyyxx** [comment] 2020-03-21 19:54
Those comments do not apply to torchvision models

**Comment by kaleidoscopical** [comment] 2020-03-21 19:58
I am doubting they do not apply to your pre-trained model too. Never mind.

**Comment by XinjieInformatik** [comment] 2020-03-26 12:09
Hi @kaleidoscopical ,
if I understand correctly, you want to directly use pretrained models from torchvision in detectron2. I also did this experiment.

In general, just few codes needed to be changed, you just need to import torchvision pretrained model, get outputs for FPN, frozen first two layer, frozen all bn (if you need). 
In my experiment in my dataset, resnet50 from torchvision and resnet50 used in detectron2 have similar performance.

hope this simple demo helps.

in detectron2.modeling.backbone  fpn.py
```python
@BACKBONE_REGISTRY.register()
def build_retinanet_resnet_fpn_backbone(cfg, input_shape: ShapeSpec):
    """
    Args:
        cfg: a detectron2 CfgNode

    Returns:
        backbone (Backbone): backbone module, must be a subclass of :class:`Backbone`.
    """
    """
    in detectron2 by default:
    1. resnet base and layer1(res2) requires_grad = False
    2. all the bn in resnet converted to Frozen bn
    """
    # bottom_up = build_resnet_backbone(cfg, input_shape)
    # in_channels_p6p7 = bottom_up.output_shape()["res5"].channels

    return_layers = {"layer2": "res3", "layer3": "res4", "layer4": "res5"}

    resnet = models.resnet50(pretrained=True)
    frozen_range = [resnet.conv1, resnet.layer1]
    for module in frozen_range:
        for param in module.parameters():
            param.requires_grad = False
    resnet = FrozenBatchNorm2d.convert_frozen_batchnorm(resnet)

    bottom_up = _utils.IntermediateLayerGetter(resnet, return_layers)
    in_channels_p6p7 = bottom_up[list(return_layers.keys())[-1]][-1].conv3.out_channels  # 2048

    # frozen bn -- this occupies more memory than FrozenBatchNorm2d
    # for module in resnet.modules():
    #     if isinstance(module, nn.BatchNorm2d):
    #         module.eval()
    #         module.weight.requires_grad = False
    #         module.bias.requires_grad = False

    in_features = cfg.MODEL.FPN.IN_FEATURES
    out_channels = cfg.MODEL.FPN.OUT_CHANNELS

    backbone = FPN(
        bottom_up=bottom_up,
        in_features=in_features,
        out_channels=out_channels,
        return_layers=return_layers,
        norm=cfg.MODEL.FPN.NORM,
        top_block=LastLevelP6P7(in_channels_p6p7, out_channels),
        fuse_type=cfg.MODEL.FPN.FUSE_TYPE,
    )
    return backbone
``` 

``` python
class FPN(Backbone):
    """
    This module implements Feature Pyramid Network.
    It creates pyramid features built on top of some input feature maps.
    """
    def __init__(
        self, bottom_up, in_features, out_channels, return_layers, norm="", top_block=None, fuse_type="sum"
    ):
        super(FPN, self).__init__()

        # assert isinstance(bottom_up, Backbone)
        # # Feature map strides and channels from the bottom up network (e.g. ResNet)
        # input_shapes = bottom_up.output_shape()
        # in_strides = [input_shapes[f].stride for f in in_features]
        # in_channels = [input_shapes[f].channels for f in in_features]

        in_strides = [8, 16, 32]
        in_channels = [512, 1024, 2048]  # for resnet50
        # in_channels = [bottom_up[key][-1].conv3.out_channels for key in return_layers]

        _assert_strides_are_log2_contiguous(in_strides)
        lateral_convs = []
        output_convs = []

        use_bias = norm == ""
        for idx, in_channels in enumerate(in_channels):
            lateral_norm = get_norm(norm, out_channels)
            output_norm = get_norm(norm, out_channels)

            lateral_conv = Conv2d(
                in_channels, out_channels, kernel_size=1, bias=use_bias, norm=lateral_norm
            )
            output_conv = Conv2d(
                out_channels,
                out_channels,
                kernel_size=3,
                stride=1,
                padding=1,
                bias=use_bias,
                norm=output_norm,
            )
            weight_init.c2_xavier_fill(lateral_conv)
            weight_init.c2_xavier_fill(output_conv)
            stage = int(math.log2(in_strides[idx]))
            self.add_module("fpn_lateral{}".format(stage), lateral_conv)
            self.add_module("fpn_output{}".format(stage), output_conv)

            lateral_convs.append(lateral_conv)
            output_convs.append(output_conv)
        # Place convs into top-down order (from low to high resolution)
        # to make the top-down computation in forward clearer.
        self.lateral_convs = lateral_convs[::-1]
        self.output_convs = output_convs[::-1]
        self.top_block = top_block
        self.in_features = in_features
        self.bottom_up = bottom_up # resnet
        # Return feature names are "p<stage>", like ["p2", "p3", ..., "p6"]
        self._out_feature_strides = {"p{}".format(int(math.log2(s))): s for s in in_strides}
        # top block output feature maps.
        if self.top_block is not None:
            for s in range(stage, stage + self.top_block.num_levels):
                self._out_feature_strides["p{}".format(s + 1)] = 2 ** (s + 1)

        self._out_features = list(self._out_feature_strides.keys())
        self._out_feature_channels = {k: out_channels for k in self._out_features}
        self._size_divisibility = in_strides[-1]
        assert fuse_type in {"avg", "sum"}
        self._fuse_type = fuse_type
``` 

set MODEL.WEIGHTS in your config file to empty.
``` 
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: ""
```

**Comment by kaleidoscopical** [comment] 2020-03-26 12:40
Hi @XinjieInformatik , thanks a lot. It is a good solution. I am not familiar with the code in Detectron 2, so I don't think it is easy for me to correctly apply such a strategy to faster-rcnn.

**Comment by XinjieInformatik** [comment] 2020-03-26 12:55
seems Faster RCNN backbone is built in
def build_resnet_fpn_backbone(cfg, input_shape: ShapeSpec)

The structure is actually the same like, which I provide above.
def build_retinanet_resnet_fpn_backbone(cfg, input_shape: ShapeSpec)
and they share class FPN.

You can have a look, and just use the same strategy for Faster RCNN in build_resnet_fpn_backbone, I think the code above is enough to solve this.
