### ISSUE TITLE
Something is wrong with SSL on `dl.fbaipublicfiles.com`

### ISSUE THREAD

**Issue by mbergal** [facebookresearch/detectron2#4165] opened 2022-04-18 22:33 UTC
```
wget https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.9/index.html
--2022-04-18 17:31:28--  https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.9/index.html
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 54.192.58.59, 54.192.58.72, 54.192.58.30, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|54.192.58.59|:443... connected.
OpenSSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
Unable to establish SSL connection.
```

**Comment by tateemma** [comment] 2022-04-19 01:19
Hi. Have you found a solution for this?

**Comment by bradezard131** [comment] 2022-04-19 05:01
[This SO post](https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests) shows how to monkey-patch away SSL verification as a temporary fix until they fix the certificate

**Comment by mbergal** [comment] 2022-04-19 05:14
I don't think it is a certificate issue.

**Comment by bradezard131** [comment] 2022-04-19 05:16
Regardless of the source, the monkey-patch works for me

**Comment by davidmezzetti** [comment] 2022-04-19 11:37
This has been happening intermittently for a few days but it's happening every time now. For a GitHub action, I now consistently get this error when downloading files from dl.fbaipublicfiles.com:

requests.exceptions.SSLError: HTTPSConnectionPool(host='dl.fbaipublicfiles.com', port=443): (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')))

This is happening for any files hosted on dl.fbaipublicfiles.com not just detectron files.

**Comment by fernandorovai** [comment] 2022-04-19 14:08
Is there any other mirror to download the whl's?

**Comment by calebho** [comment] 2022-04-20 17:54
I'm in the midst of migrating some stuff on the backend and it seems I misconfigured something. This misconfiguration should be fixed since yesterday. Apologies for the inconvenience

**Comment by ppwwyyxx** [comment] 2022-05-28 22:34
Closing as fixed

**Closed by ppwwyyxx** 2022-05-28 22:34 UTC
Labels: documentation
