### ISSUE TITLE
 How to run panoptic FPN with the Cityscapes dataset?

### ISSUE THREAD

**Issue by emjay73** [facebookresearch/detectron2#1236] opened 2020-04-16 23:57 UTC
## ❓ How to use Detectron2

How to run panoptic FPN with the Cityscapes dataset?

```
python train_net --num-gpus 1 --config-file configs/Cityscapes/mask_rcnn_R_50_FPN.yaml
```

and got theses
```
Exception has occurred: ModuleNotFoundError
No module named 'cityscapesscripts'
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/data/datasets/cityscapes.py", line 64, in load_cityscapes_instances
    ret = pool.map(
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/data/datasets/builtin.py", line 181, in <lambda>
    lambda x=image_dir, y=gt_dir: load_cityscapes_instances(
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/data/catalog.py", line 62, in get
    return f()
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/data/build.py", line 224, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/data/build.py", line 224, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in dataset_names]
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/data/build.py", line 291, in build_detection_train_loader
    dataset_dicts = get_detection_dataset_dicts(
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/engine/defaults.py", line 430, in build_train_loader
    return build_detection_train_loader(cfg)
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/engine/defaults.py", line 253, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/tools/train_net.py", line 155, in main
    trainer = Trainer(cfg)
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/detectron2/engine/launch.py", line 55, in launch
    main_func(*args)
  File "/home/emjay/Documents/Segmentation/Panoptic/detectron2/tools/train_net.py", line 167, in <module>
    launch(
```

**Comment by ppwwyyxx** [comment] 2020-04-17 00:00
It's not yet supported.
Duplicate of #610

**Closed by ppwwyyxx** 2020-04-17 00:00 UTC

**Comment by emjay73** [comment] 2020-04-17 00:17
Well, do you have any plans or timeline for supporting this issue?
