### ISSUE TITLE
Problem training a new detectron2 model due to portrait shaped images

### ISSUE THREAD

**Issue by Philliec459** [facebookresearch/detectron2#1259] opened 2020-04-20 05:59 UTC
In creating a training set of images from Allopart marine images used with MASK RCNN, it became apparent that the images in the portrait shape would not load. Possibly this was due to initial rotation or something. I do not know, but I then eliminated all images that were not landscape and I had no more problems with training.

**Comment by ppwwyyxx** [comment] 2020-04-20 06:02
I think it's a duplicate of #788, so closing. But if you still need help to solve an unexpected issue you observed, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Closed by ppwwyyxx** 2020-04-20 06:02 UTC
