### ISSUE TITLE
Delete text labels for semantically segmented images 

### ISSUE THREAD

**Issue by rakshitagouni** [facebookresearch/detectron2#2344] opened 2020-12-03 21:20 UTC
I'm running COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml to semantically segment my images. Is there any way to delete the black text boxes (and only keep the colors)?

So I have made changes to the _detectron2/utils/visualizer.py file._ Is this the correct file?
I have changed the draw_binary_text function to not take in text as a parameter and made the necessary changes in the rest of the file. Also, in predictor.py I have changed it so that only the **draw_sem_seg** function is called. I am still getting the black text labels to show up.

Also, my command that I'm running is:
`python demo.py --config-file ../configs/COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml --input input1.png input2.png --opts MODEL.WEIGHTS detectron2://COCO-PanopticSegmentation/panoptic_fpn_R_50_3x/139514569/model_final_c10459.pkl MODEL.DEVICE cpu`

Any help would be greatly appreciated!

Thank you!!

**Comment by ppwwyyxx** [comment] 2020-12-04 02:54
Duplicate of #2331

**Closed by ppwwyyxx** 2020-12-04 02:54 UTC
