### ISSUE TITLE
Inference running more slowly than expected on Azure

### ISSUE THREAD

**Issue by jcpayne** [facebookresearch/detectron2#2204] opened 2020-10-28 22:42 UTC
Hello @ppwwyyxx, this is a continuation of Issue 2166, but I couldn't figure out how to reopen that one.  Please allow this issue to stay open until resolved.  I have clearly identified a real problem that has nothing to do with my code.  Detectron2 runs more than 20X slower than it should on Azure's standard NC (version 1) machines, and probably slower than it should on Azure NC_v2 machines as well.  That difference holds no matter whether the environment is containerized or not, whether the code is run on the Azure Machine Learning cluster machine, on a VM running a Jupyter Notebook, or running on the commandline inside a container.  Of course, it could be Microsoft's fault -- I don't know -- but I think that it should be flagged as a problem since Azure is one of the biggest ML platforms in the world.

<pre>

+------------------------------+--------------------------------------------------------------+
|                              |                         Machine type                         |
+------------------------------+-------------------+--------------------+---------------------+
|           Run setup          | Azure NC6 (v1)    | Azure NC6_v2       | Google Colab        |
|                              | Tesla K80 GPU     | Tesla P100 GPU     | Tesla K80 or T4 GPU |
+------------------------------+-------------------+--------------------+---------------------+
| Azure VM (DSVM)              | 3.6 s/image (CPU) |                    |                     |
| run from                     | 0.9 s/image (GPU) |                    |                     |
| Jupyter Notebook             |                   |                    |                     |
+------------------------------+-------------------+--------------------+---------------------+
| Azure VM (DSVM);             |                   |                    |                     |
| Containerized code           | 3.6 s/image (CPU) |                    |                     |
| run from command line        | 0.9 s/image (GPU) |                    |                     |
| inside the running container |                   |                    |                     |
+------------------------------+-------------------+--------------------+---------------------+
| Azure Machine Learning       |                   |                    |                     |
| “cluster” machine,           | 0.9 s/image (GPU) | 0.22 s/image (GPU) |                     |
| containerized environment;   |                   |                    |                     |
| script is run                |                   |                    |                     |
| via Python SDK               |                   |                    |                     |
+------------------------------+-------------------+--------------------+---------------------+
| Google Colab (free tier)     |                   |                    | 0.04 s/image        |
| run via notebook             |                   |                    | (the same result    |
|                              |                   |                    | was obtained by     |
|                              |                   |                    | Detectron2 support  |
|                              |                   |                    | and myself)         |
+------------------------------+-------------------+--------------------+---------------------+

</pre>

All machines were running Linux 18.04; all using only the same small set of imported Python packages; all using the same run script. The model setup was bare-bones and the script just did inference on 10 fake 500x500 images; there was no I/O involved since the script created the test images in memory. The Dockerfile used for the containerized environment included the same set of Python packages as used on the VMs, plus 'azureml-sdk', which is the Python SDK used to communicate with AML cluster machines.

Here is the Dockerfile I used for the Azure cluster machine.  'dev_packages' includes TridentNet (copied from the Facebook website) and the run script.
```bash
FROM mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.1-cudnn7-ubuntu18.04
RUN apt-get update
RUN apt-get install 'ffmpeg' 'libsm6' 'libxext6'  -y
RUN pip install torch==1.6 torchvision==0.7
RUN pip install cython pyyaml==5.1 'pycocotools>=2.0.1'
RUN pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.6/index.html
RUN pip install opencv-python 
RUN pip install pathlib
RUN pip install jupyterlab
RUN pip install --upgrade azureml-sdk
RUN pip install azureml-datadrift
RUN pip install azureml-train-automl
RUN pip install azureml-interpret
COPY ./dev_packages /
```
<put logs here>
```

**Comment by ppwwyyxx** [comment] 2020-10-28 22:52
If the same code runs slower on Azure's machines, you should probably ask Azure. I'm not sure there is anything we could do to help.

**Comment by jcpayne** [comment] 2020-10-28 22:55
I will ask them to investigate it.  But their response so far has been "Other models work fine on Azure, so it could be a problem with Detectron2."

**Comment by ppwwyyxx** [comment] 2020-10-29 01:07
Unless there is any evidence we cannot consider it as a detectron2 issue, so I'm still closing.
Please also note that your original benchmark script in #2166 is incorrect - the time for the first few iterations should be excluded until the time per step stabilizes.

**Closed by ppwwyyxx** 2020-10-29 01:07 UTC

**Comment by jcpayne** [comment] 2020-10-31 05:43
@ppwwyyxx Sorry to bother you yet again, but I have narrowed down the problem and I am finally getting behavior that is reproducible.  The problem is that the model runs about 12X slower when I load trained weights, than when I use random weights.  I have reproduced this in a Colab workbook and on an Azure VM, so it has nothing to do with the platform; I was wrong before. 
 
<img width="1159" alt="Screen Shot 2020-10-30 at 10 30 54 PM" src="https://user-images.githubusercontent.com/22941316/97771996-b32d3880-1aff-11eb-9637-6f4268c45f2f.png">

I would guess that there is nothing wrong with the weights _per se_ because the model works quite well (i.e., it does a good job of identifying the objects we're interested in).  

Is this normal behavior?  I'm happy to share files, but the weights file is big (600 Mb) so I'm not sure what the best way to share it is.  I would welcome any suggestions.  Thanks.

**Comment by ppwwyyxx** [comment] 2020-10-31 06:14
When objects are detected it can take more time. If you compare this with official inference time of a few models in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md, it's still within reasonable range - depending on the GPU / image size you use. If you think something is wrong, we need to be able to reproduce it.

If the config stays unchanged from #2166, it's an equivalent of this model https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/faster_rcnn_R_101_C4_3x.yaml that has a latency of 0.14s on V100s for 800px COCO images.

**Comment by ppwwyyxx** [comment] 2020-10-31 06:21
Using the builtin tools, running `python tools/train_net.py --config-file configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml --eval-only   MODEL.WEIGHTS ""` is 9x faster than `python tools/train_net.py --config-file configs/COCO-Detection/faster_rcnn_R_50_C4_1x.yaml --eval-only `. That's quite surprising to me as well but this should be expected behavior.

Loading a FPN-based config will be more efficient and the speed will not vary this much.

**Comment by jcpayne** [comment] 2020-11-01 06:55
Thanks for your helpful comments.

- Yes, I used exactly the same setup as previously.  Could the "random" weights contain a lot more zeros than the trained weights?  I find it hard to image why else they would be so much faster.

- Surprisingly, I did not observe any difference in inference speed between images containing no objects versus images containing up to ~20 objects.  The random-vs-trained weight slowdown was the same for real images containing objects and for random-noise images (and the model didn't find any objects in the latter).  

- I got a result of 0.019 s/img with random weights and 0.155 s/image with trained weights on a V100 GPU (Azure AML NC6_v3).  That is almost exactly the same as the result you cited for the Faster-RCNN 101-layer model.  Therefore I agree that there is nothing wrong with the model or the platform.  I guess I just need to apply more horsepower.

- Could you please explain what you mean by "Loading a FPN-based config will be more efficient and the speed will not vary this much."  
Do you mean TridentNet could be built on different backbone?  The Model Zoo page says "For Faster/Mask R-CNN, we provide baselines based on 3 different backbone combinations...FPN, C4, and DC5," where C4 is "ResNet conv4 backbone with conv5 head", and FPN is "ResNet+FPN backbone with...FC heads for box prediction."  If I understand the TridentNet paper and code correctly, it uses a C4 backbone (with tridentconv blocks replacing resnet blocks in the conv4 stage) and an FPN head.  I can't quite picture what you mean.

**Comment by ppwwyyxx** [comment] 2020-11-01 11:53
If you don't know what to choose, it's recommended to use FPN models from model zoo. I don't know if tridentnet works with FPN.

**Comment by Ademord** [comment] 2020-11-14 03:09
@jcpayne I came here looking for an explanation to this as well. Since the metrics say that [R50-FPN ](https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml) runs at 0.043 (s/im) but on my tests its running at 119-180 ms, and I am really trying to push for a way to run as close to real-time as possible. Anything we could tune to make it run faster? I am running the cluster with more than enough GPU, RAM, etc.

**Comment by jcpayne** [comment] 2020-11-14 07:30
I haven't found any solution except using machines with more powerful GPUs.  In my own project I'm working on ways to reduce the number of images that I have to push through the model, but to be honest I don't see why such a large performance gap between random and trained weights should be considered "expected behavior." My experience is limited, but I haven't heard of such a thing with other models.

**Comment by Ademord** [comment] 2020-11-14 14:25
@jcpayne Is there a way to reduce the resolution inside detectron2? In maskrcnn we could modify this, I dont know how to do it here, and it would speed up significantly. On a side note when i try to predict on low resolution `images` it doesnt show the mask, no idea why. But first question is my biggest concern.

**Comment by jcpayne** [comment] 2020-11-18 04:04
There is an ImageResizeTransform() method that I think is called both in training and inference, by default.  See class detectron2.data.transforms.Resize in [the docs](https://detectron2.readthedocs.io/modules/data_transforms.html?highlight=resize#detectron2.data.transforms.Resize).  I believe it uses bilinear interpolation by default.
