### ISSUE TITLE
How to get both keypoints and masks at the same time in a video?

### ISSUE THREAD

**Issue by deveshreddy** [facebookresearch/detectron2#1845] opened 2020-07-30 21:44 UTC
I truly appreciate the work of Facebook research team in building detectron2. I have used detectron2 for different applications and I am thankful for making it available.

Description: I am trying to get both masks and key points in the video. 
1. Is it possible to train such parallel model is possible using detection? 
2. If we can build such model with detectron, how do we do it? 
3. Is there any demo available for this?

**Comment by ppwwyyxx** [comment] 2020-07-31 03:15
Duplicate of #17. We don't have such demo

**Closed by ppwwyyxx** 2020-07-31 03:15 UTC
