### ISSUE TITLE
Not able to setup detectron2

### ISSUE THREAD

**Issue by Mayank187** [facebookresearch/detectron2#4958] opened 2023-05-17 10:11 UTC
## Instructions To Reproduce the Issue:

I ran the following code on the system.
```pip install 'git+https://github.com/facebookresearch/detectron2.git'```

## Issue Faced:

Following error pops up
```The detected CUDA version (10.1) mismatches the version that was used to compile PyTorch (11.7). Please make sure to use the same CUDA versions.```

## Environment:

```NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7```
```
torch                     2.0.1
torchaudio                2.0.2
torchvision               0.15.2
```

Paste the output of the following command:
```
wget -nc -nv https://github.com/facebookresearch/detectron2/raw/main/detectron2/utils/collect_env.py && python collect_env.py
```

## Output:
```
sys.platform                     linux
Python                           3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]
numpy                            1.24.3
detectron2                       failed to import
detectron2._C                    not built correctly: No module named 'detectron2'
Compiler ($CXX)                  c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
CUDA compiler                    Cuda compilation tools, release 10.1, V10.1.243
DETECTRON2_ENV_MODULE            <not set>
PyTorch                          2.0.1+cu117 @/home/techvamp/anaconda3/envs/semseg/lib/python3.11/site-packages/torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    Yes
GPU 0                            NVIDIA A100-SXM4-40GB (arch=8.0)
Driver version                   515.105.01
CUDA_HOME                        /usr
Pillow                           9.5.0
torchvision                      0.15.2+cu117 @/home/techvamp/anaconda3/envs/semseg/lib/python3.11/site-packages/torchvision
torchvision arch flags           3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                           0.1.5.post20221221
iopath                           0.1.9
cv2                              4.7.0
```

**Comment by Lunatik00** [comment] 2023-05-22 17:31
Currently there are problems with newer versions of python, try using python 3.9, 3.10 doesn't work out of the box, I just tried, I think the problem is the pytorch versions that are supported, they go up to pytorch 1.10, that version is only compiled for up to python 3.9, I tried using python 3.10 and pytorch 1.11 and it doesn't compile. I see you are using a remote server (the A100 card), I would recommend to generate a container with whatever you need, test it locally and use that image in the server, there are base containers for pytorch with cuda. Welcome to dependency hell.

**Comment by ppwwyyxx** [comment] 2023-05-26 02:27
The message is from pytorch and not related to detectron2. Closing.

**Closed by ppwwyyxx** 2023-05-26 02:27 UTC

**Comment by Lunatik00** [comment] 2023-05-29 19:18
The lack of .whl that are compatible are a problem with detectron compatibility.
