### ISSUE TITLE
Incorrect python version error when building docker.

### ISSUE THREAD

**Issue by Abanoub-G** [facebookresearch/detectron2#3935] opened 2022-02-02 22:59 UTC
I am using Ubuntu 20.04. 
I have git cloned the detectron2 repository and I executed these commands below as outlined in the docker installation readme https://github.com/facebookresearch/detectron2/tree/main/docker : 
- cd docker
- docker build --build-arg USER_ID=$UID -t detectron2:v0 .

The latter command output the logs below:

```
Sending build context to Docker daemon  9.728kB
Step 1/21 : FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
 ---> cab9d5b66568
Step 2/21 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 7d32eeaeed90
Step 3/21 : RUN apt-get update && apt-get install -y 	python3-opencv ca-certificates python3-dev git wget sudo ninja-build
 ---> Using cache
 ---> d6274c259961
Step 4/21 : RUN ln -sv /usr/bin/python3 /usr/bin/python
 ---> Using cache
 ---> bc5da3e9bac2
Step 5/21 : ARG USER_ID=1000
 ---> Using cache
 ---> b361de0304dc
Step 6/21 : RUN useradd -m --no-log-init --system  --uid ${USER_ID} appuser -g sudo
 ---> Using cache
 ---> 519b14eb1cc7
Step 7/21 : RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 ---> Using cache
 ---> 0c605d41753f
Step 8/21 : USER appuser
 ---> Using cache
 ---> 67cba7900e93
Step 9/21 : WORKDIR /home/appuser
 ---> Using cache
 ---> f41a32ffeb26
Step 10/21 : ENV PATH="/home/appuser/.local/bin:${PATH}"
 ---> Using cache
 ---> 454f8d766973
Step 11/21 : RUN wget https://bootstrap.pypa.io/get-pip.py && 	python3 get-pip.py --user && 	rm get-pip.py
 ---> Running in c0b623c509ae
--2022-02-02 22:41:50--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.16.175, 2a04:4e42:4::175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.16.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2609829 (2.5M) [text/x-python]
Saving to: 'get-pip.py'

     0K .......... .......... .......... .......... ..........  1% 2.05M 1s
    50K .......... .......... .......... .......... ..........  3% 2.86M 1s
   100K .......... .......... .......... .......... ..........  5% 13.9M 1s
   150K .......... .......... .......... .......... ..........  7% 5.28M 1s
   200K .......... .......... .......... .......... ..........  9% 12.9M 1s
   250K .......... .......... .......... .......... .......... 11% 3.66M 1s
   300K .......... .......... .......... .......... .......... 13% 2.84M 1s
   350K .......... .......... .......... .......... .......... 15%  299M 0s
   400K .......... .......... .......... .......... .......... 17% 8.37M 0s
   450K .......... .......... .......... .......... .......... 19% 4.03M 0s
   500K .......... .......... .......... .......... .......... 21% 2.71M 0s
   550K .......... .......... .......... .......... .......... 23% 12.1M 0s
   600K .......... .......... .......... .......... .......... 25%  295M 0s
   650K .......... .......... .......... .......... .......... 27% 4.45M 0s
   700K .......... .......... .......... .......... .......... 29% 6.11M 0s
   750K .......... .......... .......... .......... .......... 31% 4.06M 0s
   800K .......... .......... .......... .......... .......... 33% 4.64M 0s
   850K .......... .......... .......... .......... .......... 35% 77.8M 0s
   900K .......... .......... .......... .......... .......... 37% 5.03M 0s
   950K .......... .......... .......... .......... .......... 39% 4.58M 0s
  1000K .......... .......... .......... .......... .......... 41% 8.47M 0s
  1050K .......... .......... .......... .......... .......... 43%  214K 1s
  1100K .......... .......... .......... .......... .......... 45% 72.0M 1s
  1150K .......... .......... .......... .......... .......... 47% 73.3M 0s
  1200K .......... .......... .......... .......... .......... 49% 86.2M 0s
  1250K .......... .......... .......... .......... .......... 51% 8.36M 0s
  1300K .......... .......... .......... .......... .......... 52%  182M 0s
  1350K .......... .......... .......... .......... .......... 54%  328M 0s
  1400K .......... .......... .......... .......... .......... 56%  391M 0s
  1450K .......... .......... .......... .......... .......... 58%  319M 0s
  1500K .......... .......... .......... .......... .......... 60%  399M 0s
  1550K .......... .......... .......... .......... .......... 62%  429M 0s
  1600K .......... .......... .......... .......... .......... 64%  333M 0s
  1650K .......... .......... .......... .......... .......... 66%  414M 0s
  1700K .......... .......... .......... .......... .......... 68%  431M 0s
  1750K .......... .......... .......... .......... .......... 70%  331M 0s
  1800K .......... .......... .......... .......... .......... 72% 5.85M 0s
  1850K .......... .......... .......... .......... .......... 74% 18.4M 0s
  1900K .......... .......... .......... .......... .......... 76% 3.70M 0s
  1950K .......... .......... .......... .......... .......... 78% 12.6M 0s
  2000K .......... .......... .......... .......... .......... 80% 3.45M 0s
  2050K .......... .......... .......... .......... .......... 82%  290M 0s
  2100K .......... .......... .......... .......... .......... 84% 3.33M 0s
  2150K .......... .......... .......... .......... .......... 86% 1.34M 0s
  2200K .......... .......... .......... .......... .......... 88% 71.9M 0s
  2250K .......... .......... .......... .......... .......... 90% 5.05M 0s
  2300K .......... .......... .......... .......... .......... 92% 11.0M 0s
  2350K .......... .......... .......... .......... .......... 94%  455M 0s
  2400K .......... .......... .......... .......... .......... 96%  209K 0s
  2450K .......... .......... .......... .......... .......... 98% 1.21M 0s
  2500K .......... .......... .......... .......... ........  100% 2.31M=0.8s

2022-02-02 22:41:51 (2.94 MB/s) - 'get-pip.py' saved [2609829/2609829]

ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
The command '/bin/sh -c wget https://bootstrap.pypa.io/get-pip.py && 	python3 get-pip.py --user && 	rm get-pip.py' returned a non-zero code: 1

```
It says the minimum supported Python version is 3.6. My python version is 3.8.10, which I have checked by running python3 on the same terminal window.

I would really appreciate any help or guidance please. 

Thanks

**Comment by ppwwyyxx** [comment] 2022-02-03 00:26
Duplicate of #3933

**Closed by ppwwyyxx** 2022-02-03 00:26 UTC
