### ISSUE TITLE
Please read & provide the following

### ISSUE THREAD

**Issue by linmengnan** [facebookresearch/detectron2#960] opened 2020-02-27 09:49 UTC
1. 、when i train my custom data，code(test.py) as follows：

<img width="1440" alt="屏幕快照 2020-02-27 下午5 51 46" src="https://user-images.githubusercontent.com/51906636/75432750-d9f00980-5989-11ea-991d-e67b5de482af.png">

2. I use python test.py run my code 
 
3. after  run my code ,it occurs:

![Uploading 屏幕快照 2020-02-27 下午5.52.48.png…]()

Thank you!

**Comment by ppwwyyxx** [comment] 2020-02-27 21:08
Duplicate of #959

**Closed by ppwwyyxx** 2020-02-27 21:08 UTC
