### ISSUE TITLE
"Ignored Region" class implementation

### ISSUE THREAD

**Issue by Mstfakts** [facebookresearch/detectron2#2639] opened 2021-02-19 22:15 UTC
## 🚀 Feature
Some of the datasets (VisDrone is one of them) have 'ignored region' class. It means if the model detects an object that falls into the 'ignored region', it is not included in the loss calculation. Let's say that the model detected a car in the given image. If the car's region labeled as 'ignored region' I do not want the model to learn anything here. However, current detectron2 pretends like it was an 'ignored region' not a car for an example case. In some frameworks, you label ignored region as -1 and proceed with the training.

## Motivation & Examples

![image](https://i.ibb.co/vwH2VXD/ignored.png)
(This image was taken from VisDrone-2019 dataset!: http://2019.aiskyeye.com/)
This is an example case. There are many cars in the 'ignored region', but I do not care whether the model detects them or not since these cars are really small. So, I do not want them to affect my loss. Another undesired thing is that the model tries to learn 'ignored region' which leads to very poor results.

- If it takes a long time to implement this feature, could you please lead a way for me? I need to overcome this issue as soon as possible.

**Comment by ppwwyyxx** [comment] 2021-02-19 22:24
Duplicate of #1909

**Closed by ppwwyyxx** 2021-02-19 22:24 UTC
Labels: enhancement
