### ISSUE TITLE
Issues running 'Training and Evaluating in Command Line' example

### ISSUE THREAD

**Issue by jlamborn324** [facebookresearch/detectron2#2940] opened 2021-04-20 17:53 UTC
Trying to run the example provided in the docs to train a model from the command line. Using the COCO dataset. 

## Instructions To Reproduce the Issue:

1. DETECTRON_DATASETS directory
```
coco 
   - annotations 
         - captions_train2017.json 
         -  deprecated-challenge2017 
         -  image_info_test-dev2017.json
         - instances_train2017.json  
         - person_keypoints_train2017.json 
         -  stuff_train2017.json	
         -  stuff_val2017.json
         - captions_val2017.json	
         - image_info_test2017.json 
         - image_info_unlabeled2017.json  
         - instances_val2017.json    
         - person_keypoints_val2017.json    
         - stuff_train2017_pixelmaps.zip  
         - stuff_val2017_pixelmaps.zip
   -  images 
   -  test2017 
        # image files
   -  train2017 
         # image files
   -  unlabeled2017 
         # image files
   - val2017
         # image files
```
2. Running:
```
python3 ./train_net.py   --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml   --num-gpus 1 SOLVER.IMS_PER_BATCH 2 SOLVER.BASE_LR 0.0025
```

3. __Full logs__ or other relevant observations:
```
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
ERROR [04/18 23:17:57 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 495, in run_step
    self._trainer.run_step()
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 157, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 471, in forward
    gt_labels, gt_boxes = self.label_and_sample_anchors(anchors, gt_instances)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 340, in label_and_sample_anchors
    matched_idxs, gt_labels_i = retry_if_cuda_oom(self.anchor_matcher)(match_quality_matrix)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/utils/memory.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/matcher.py", line 88, in __call__
    assert torch.all(match_quality_matrix >= 0)
RuntimeError: CUDA error: device-side assert triggered
[04/18 23:17:57 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
[04/18 23:17:57 d2.utils.events]:  iter: 2  total_loss: 6.434  loss_cls: 5.39  loss_box_reg: 0.01032  loss_mask: 0.6935  loss_rpn_cls: 0.2097  loss_rpn_loc: 0.1306  data_time: 0.1331  lr: 4.9975e-06  max_mem: 2279M
Traceback (most recent call last):
  File "./train_net.py", line 167, in <module>
    args=(args,),
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "./train_net.py", line 155, in main
    return trainer.train()
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 485, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 149, in train
    self.run_step()
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/defaults.py", line 495, in run_step
    self._trainer.run_step()
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/engine/train_loop.py", line 273, in run_step
    loss_dict = self.model(data)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/meta_arch/rcnn.py", line 157, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 471, in forward
    gt_labels, gt_boxes = self.label_and_sample_anchors(anchors, gt_instances)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/proposal_generator/rpn.py", line 340, in label_and_sample_anchors
    matched_idxs, gt_labels_i = retry_if_cuda_oom(self.anchor_matcher)(match_quality_matrix)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/utils/memory.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/jlamborn/.local/lib/python3.6/site-packages/detectron2/modeling/matcher.py", line 88, in __call__
    assert torch.all(match_quality_matrix >= 0)
RuntimeError: CUDA error: device-side assert triggered

```

## Environment:

```
sys.platform            linux
Python                  3.6.12 (default, Oct 23 2020, 13:36:31) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
numpy                   1.19.5
detectron2              0.4 @/home/jlamborn/.local/lib/python3.6/site-packages/detectron2
Compiler                GCC 9.3
CUDA compiler           CUDA 11.1
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.1+cu111 @/home/jlamborn/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3,4,5,6,7     Tesla V100-SXM2-32GB (arch=7.0)
CUDA_HOME               /usr/local/cuda-11.1
Pillow                  8.1.2
torchvision             0.9.1+cu111 @/home/jlamborn/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20210330
iopath                  0.1.7
cv2                     4.5.1
----------------------  -------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```

I have built Detectron2 from source. 

Can't seem to track down the root cause of this issue! Any help would be greatly appreciated!

**Comment by ppwwyyxx** [comment] 2021-04-21 00:41
Duplicate of #2837

**Closed by ppwwyyxx** 2021-04-21 00:41 UTC
