### ISSUE TITLE
No instances of object detected using a COCO-pretrained model on a custom dataset ran on Demo.py

### ISSUE THREAD

**Issue by CBJ16** [facebookresearch/detectron2#1956] opened 2020-08-25 09:58 UTC
Hi,

Following training a model on a custom dataset I was hoping that reloading the saved model into demo.py would produce a detecable instances on an image, however the result did not yield any results. Below are what was being done.

1. full code you wrote or full changes you made 
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("my_dataset_train",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = 'detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl'  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.02  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4 #your number of classes + 1
#The next four lines of code create an output directory, a trainer, and start training.
os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()

#saving the model
cfg.MODEL.WEIGHTS = os.path.join(cfg.OUTPUT_DIR, "model_final.pth")
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg.DATASETS.TEST = ("my_dataset_val", )
predictor = DefaultPredictor(cfg)

from detectron2.modeling import build_model
model = build_model(cfg)

checkpointer = DetectionCheckpointer(model, save_dir="/content/drive/My Drive/outputs/")
checkpointer.save("model_999")  




```
2. what exact command you run:
!python demo.py --config-file /content/detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml --input /content/drive/My\ Drive/test/TEST.jpg --output /content/drive/My\ Drive/outputs/ --opts MODEL.WEIGHTS /content/drive/My\ Drive/outputs/model_999.pth

3. __full logs__ you observed:
```
[08/25 09:38:06 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='/content/detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml', input=['/content/drive/My Drive/test/TEST.jpg'], opts=['MODEL.WEIGHTS', '/content/drive/My Drive/outputs/model_999.pth'], output='/content/drive/My Drive/outputs/', video_input=None, webcam=False)
[08/25 09:38:11 fvcore.common.checkpoint]: Loading checkpoint from /content/drive/My Drive/outputs/model_999.pth
WARNING [08/25 09:38:12 fvcore.common.checkpoint]: Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (5, 1024) in the checkpoint but (81, 1024) in the model! You might want to double check if this is expected.
WARNING [08/25 09:38:12 fvcore.common.checkpoint]: Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (5,) in the checkpoint but (81,) in the model! You might want to double check if this is expected.
WARNING [08/25 09:38:12 fvcore.common.checkpoint]: Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (16, 1024) in the checkpoint but (320, 1024) in the model! You might want to double check if this is expected.
WARNING [08/25 09:38:12 fvcore.common.checkpoint]: Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (16,) in the checkpoint but (320,) in the model! You might want to double check if this is expected.
[08/25 09:38:12 fvcore.common.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
  roi_heads.box_predictor.bbox_pred.{weight, bias}
  roi_heads.box_predictor.cls_score.{bias, weight}
  0% 0/1 [00:00<?, ?it/s][08/25 09:38:13 detectron2]: /content/drive/My Drive/test/TEST.jpg: detected 0 instances in 0.30s
100% 1/1 [00:01<00:00,  1.08s/it]

## Expected behavior:
Expected to detected >0 instances in the TEST.jpg.  During the Colab inference phase detection was possible with no errors.

**Comment by CBJ16** [comment] 2020-08-25 12:18
I managed to fix (remove) the WARNING by adjusting the command I ran 

!python demo.py --config-file /content/detectron2/configs/COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x.yaml --input /content/drive/My\ Drive/test/Wood\ 016_jpg.rf.929108cdca15a848016b12693b04570a.jpg --output /content/drive/My\ Drive/outputs/ --opts MODEL.WEIGHTS /content/drive/My\ Drive/outputs/model_999.pth MODEL.ROI_HEADS.NUM_CLASSES 4

added the MODEL.ROI_HEADS.NUM_CLASSES 4

However, the demo.py was still unable to detect any instance of the classes in the image. Where could be the issue?

**Comment by ppwwyyxx** [comment] 2020-08-26 06:19
Duplicate of #1963

**Closed by ppwwyyxx** 2020-08-26 06:19 UTC
