### ISSUE TITLE
LVIS **v1.0** Instance Segmentation Baselines with Mask R-CNN

### ISSUE THREAD

**Issue by Yuxin-CV** [facebookresearch/detectron2#2409] opened 2020-12-22 14:01 UTC
## 🚀 Feature
A clear and concise description of the feature proposal.

Hello~
Will you provide LVIS **v1.0** instance segmentation baselines with Mask R-CNN in the Model Zoo in the near future?

**Comment by ppwwyyxx** [comment] 2020-12-23 10:56
Duplicate of #2349.

**Closed by ppwwyyxx** 2020-12-23 10:56 UTC
