### ISSUE TITLE
Is my detectron2 even training?

### ISSUE THREAD

**Issue by sarmientoj24** [facebookresearch/detectron2#2215] opened 2020-11-01 07:46 UTC
There seems to be no logs for training available in here:

```
     (box_head): FastRCNNConvFCHead(
      (fc1): Linear(in_features=12544, out_features=1024, bias=True)
      (fc2): Linear(in_features=1024, out_features=1024, bias=True)
    )
    (box_predictor): FastRCNNOutputLayers(
      (cls_score): Linear(in_features=1024, out_features=18, bias=True)
      (bbox_pred): Linear(in_features=1024, out_features=68, bias=True)
    )
  )
)
WARNING [11/01 07:40:22 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[11/01 07:40:22 d2.data.datasets.coco]: Loaded 1128 images in COCO format from /content/train_coco.json
[11/01 07:40:22 d2.data.build]: Removed 0 images with no usable annotations. 1128 images left.
[11/01 07:40:22 d2.data.common]: Serializing 1128 elements to byte tensors and concatenating them all ...
[11/01 07:40:22 d2.data.common]: Serialized dataset takes 0.31 MiB
[11/01 07:40:22 d2.data.build]: Using training sampler TrainingSampler
Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (18, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (18,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (68, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (68,) in the model! You might want to double check if this is expected.
[11/01 07:40:22 d2.engine.train_loop]: Starting training from iteration 0
WARNING [11/01 07:40:24 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[11/01 07:40:24 d2.data.datasets.coco]: Loaded 180 images in COCO format from /content/test_coco.json
[11/01 07:40:24 d2.data.common]: Serializing 180 elements to byte tensors and concatenating them all ...
[11/01 07:40:24 d2.data.common]: Serialized dataset takes 0.04 MiB
[11/01 07:40:24 d2.evaluation.evaluator]: Start inference on 180 images
[11/01 07:40:25 d2.evaluation.evaluator]: Inference done 11/180. 0.1191 s / img. ETA=0:00:20
[11/01 07:40:30 d2.evaluation.evaluator]: Inference done 53/180. 0.1201 s / img. ETA=0:00:15
[11/01 07:40:35 d2.evaluation.evaluator]: Inference done 94/180. 0.1208 s / img. ETA=0:00:10
[11/01 07:40:40 d2.evaluation.evaluator]: Inference done 135/180. 0.1213 s / img. ETA=0:00:05
[11/01 07:40:46 d2.evaluation.evaluator]: Inference done 176/180. 0.1217 s / img. ETA=0:00:00
[11/01 07:40:46 d2.evaluation.evaluator]: Total inference time: 0:00:21.678221 (0.123876 s / img per device, on 1 devices)
[11/01 07:40:46 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:21 (0.121769 s / img per device, on 1 devices)
[11/01 07:40:46 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[11/01 07:40:46 d2.evaluation.coco_evaluation]: Saving results to coco_eval/coco_instances_results.json
[11/01 07:40:46 d2.evaluation.coco_evaluation]: Evaluating predictions ...
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.84s).
Accumulating evaluation results...
DONE (t=0.21s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.002
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.018
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.018
[11/01 07:40:47 d2.evaluation.coco_evaluation]: Evaluation results for bbox: 
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl  |
|:-----:|:------:|:------:|:-----:|:-----:|:-----:|
| 0.012 | 0.043  | 0.003  | 0.000 | 0.000 | 0.017 |
[11/01 07:40:47 d2.evaluation.coco_evaluation]: Per-category bbox AP: 
| category            | AP    | category               | AP    | category              | AP    |
|:--------------------|:------|:-----------------------|:------|:----------------------|:------|
| Alligator_Crack_FP  | 0.000 | Block_Crack_FP         | 0.211 | Bumps_Sags_FP         | 0.000 |
| Corner_Break_RP     | 0.000 | Divided_Slab_Crack_RP  | 0.000 | Edge_Crack_FP         | 0.000 |
| Joint_RP            | 0.000 | Linear_Crack_RP        | 0.000 | Longitudinal_Crack_FP | 0.000 |
| Manhole_Cover       | 0.000 | Miscellanious_Crack_FP | 0.000 | Patch_Utility_Cut_FP  | 0.000 |
| Pothole_FP          | 0.000 | Rutting_FP             | 0.000 | Slippage_Crack_FP     | 0.000 |
| Transverse_Crack_FP | 0.000 | Weather_Raveling_FP    | 0.000 |                       |       |
[11/01 07:40:47 d2.engine.defaults]: Evaluation results for dataset_val in csv format:
[11/01 07:40:47 d2.evaluation.testing]: copypaste: Task: bbox
[11/01 07:40:47 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[11/01 07:40:47 d2.evaluation.testing]: copypaste: 0.0124,0.0431,0.0026,0.0000,0.0000,0.0168
WARNING [11/01 07:40:49 d2.data.datasets.coco]: 
Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.

[11/01 07:40:49 d2.data.datasets.coco]: Loaded 180 images in COCO format from /content/test_coco.json
[11/01 07:40:49 d2.data.common]: Serializing 180 elements to byte tensors and concatenating them all ...
[11/01 07:40:49 d2.data.common]: Serialized dataset takes 0.04 MiB

```

I am not sure if it is even training at this point.

**Comment by ppwwyyxx** [comment] 2020-11-01 12:02
It's not training.
If you need help to solve an unexpected issue you observed, please include details following the ["Unexpected behaviors" issue template](https://github.com/facebookresearch/detectron2/issues/new/choose).

**Comment by ppwwyyxx** [comment] 2020-11-01 17:40
Duplicate of #2217

**Closed by ppwwyyxx** 2020-11-01 17:40 UTC
