### ISSUE TITLE
Installing Detectron2 on MAC

### ISSUE THREAD

**Issue by Dhimant404** [facebookresearch/detectron2#3791] opened 2021-12-14 14:05 UTC
Instructions To Reproduce the Issue and Full Logs:
1. Full runnable code or full changes you made:

Made no changes, had trouble installing detectron2

2. What exact command you run:
git clone https://github.com/facebookresearch/detectron2.git
Worked fine 

Then I tried:
CC=clang CXX=clang++ ARCHFLAGS="-arch x86_64" python -m pip install -e detectron2

3. __Full logs__ or other relevant observations:
(detectron) DHIMANTs-MacBook-Pro:detectron2 dhimant$ cd desktop
-bash: cd: desktop: No such file or directory
(detectron) DHIMANTs-MacBook-Pro:detectron2 dhimant$ cd
(detectron) DHIMANTs-MacBook-Pro:~ dhimant$ cd desktop
(detectron) DHIMANTs-MacBook-Pro:desktop dhimant$ CC=clang CXX=clang++ ARCHFLAGS="-arch x86_64" python -m pip install -e detectron2
Obtaining file:///Users/dhimant/Desktop/detectron2
Requirement already satisfied: Pillow>=7.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (8.4.0)
Requirement already satisfied: matplotlib in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (3.5.1)
Requirement already satisfied: pycocotools>=2.0.2 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (2.0.3)
Requirement already satisfied: termcolor>=1.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (1.1.0)
Requirement already satisfied: yacs>=0.1.8 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (0.1.8)
Requirement already satisfied: tabulate in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (0.8.9)
Requirement already satisfied: cloudpickle in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (2.0.0)
Requirement already satisfied: tqdm>4.29.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (4.62.3)
Requirement already satisfied: tensorboard in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (2.7.0)
Requirement already satisfied: fvcore<0.1.6,>=0.1.5 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (0.1.5.post20211023)
Requirement already satisfied: iopath<0.1.10,>=0.1.7 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (0.1.9)
Requirement already satisfied: future in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (0.18.2)
Requirement already satisfied: pydot in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (1.4.2)
Requirement already satisfied: omegaconf>=2.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (2.1.1)
Requirement already satisfied: hydra-core>=1.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (1.1.1)
Requirement already satisfied: black==21.4b2 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from detectron2==0.6) (21.4b2)
Requirement already satisfied: pathspec<1,>=0.8.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (0.9.0)
Requirement already satisfied: click>=7.1.2 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (8.0.3)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (0.4.3)
Requirement already satisfied: typing-extensions>=3.7.4 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (3.10.0.2)
Requirement already satisfied: regex>=2020.1.8 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (2021.11.10)
Requirement already satisfied: toml>=0.10.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (0.10.2)
Requirement already satisfied: typed-ast>=1.4.2 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (1.5.1)
Requirement already satisfied: appdirs in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from black==21.4b2->detectron2==0.6) (1.4.4)
Requirement already satisfied: importlib-metadata in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from click>=7.1.2->black==21.4b2->detectron2==0.6) (4.8.2)
Requirement already satisfied: pyyaml>=5.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (6.0)
Requirement already satisfied: numpy in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (1.21.2)
Requirement already satisfied: importlib-resources in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from hydra-core>=1.1->detectron2==0.6) (5.4.0)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from hydra-core>=1.1->detectron2==0.6) (4.8)
Requirement already satisfied: portalocker in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from iopath<0.1.10,>=0.1.7->detectron2==0.6) (2.3.2)
Requirement already satisfied: setuptools>=18.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from pycocotools>=2.0.2->detectron2==0.6) (58.0.4)
Requirement already satisfied: cython>=0.27.3 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from pycocotools>=2.0.2->detectron2==0.6) (0.29.25)
Requirement already satisfied: cycler>=0.10 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from matplotlib->detectron2==0.6) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from matplotlib->detectron2==0.6) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from matplotlib->detectron2==0.6) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from matplotlib->detectron2==0.6) (3.0.6)
Requirement already satisfied: fonttools>=4.22.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from matplotlib->detectron2==0.6) (4.28.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from matplotlib->detectron2==0.6) (1.3.2)
Requirement already satisfied: six>=1.5 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from python-dateutil>=2.7->matplotlib->detectron2==0.6) (1.16.0)
Requirement already satisfied: zipp>=0.5 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from importlib-metadata->click>=7.1.2->black==21.4b2->detectron2==0.6) (3.6.0)
Requirement already satisfied: protobuf>=3.6.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (3.19.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (0.6.1)
Requirement already satisfied: grpcio>=1.24.3 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (1.42.0)
Requirement already satisfied: absl-py>=0.4 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (1.0.0)
Requirement already satisfied: wheel>=0.26 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (0.37.0)
Requirement already satisfied: werkzeug>=0.11.15 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (2.0.2)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (2.26.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (2.3.3)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (0.4.6)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (1.8.0)
Requirement already satisfied: markdown>=2.6.8 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from tensorboard->detectron2==0.6) (3.3.6)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from google-auth<3,>=1.6.3->tensorboard->detectron2==0.6) (4.8)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from google-auth<3,>=1.6.3->tensorboard->detectron2==0.6) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from google-auth<3,>=1.6.3->tensorboard->detectron2==0.6) (4.2.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.6) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->detectron2==0.6) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.6) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.6) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.6) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard->detectron2==0.6) (2.0.9)
Requirement already satisfied: oauthlib>=3.0.0 in /Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->detectron2==0.6) (3.1.1)
Installing collected packages: detectron2
  Running setup.py develop for detectron2
    ERROR: Command errored out with exit status 1:
     command: /Users/dhimant/opt/anaconda3/envs/detectron/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/dhimant/Desktop/detectron2/setup.py'"'"'; __file__='"'"'/Users/dhimant/Desktop/detectron2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/dhimant/Desktop/detectron2/
    Complete output (24 lines):
    running develop
    running egg_info
    writing detectron2.egg-info/PKG-INFO
    writing dependency_links to detectron2.egg-info/dependency_links.txt
    writing requirements to detectron2.egg-info/requires.txt
    writing top-level names to detectron2.egg-info/top_level.txt
    reading manifest file 'detectron2.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'detectron2.egg-info/SOURCES.txt'
    running build_ext
    building 'detectron2._C' extension
    Emitting ninja build file /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/build.ninja...
    Compiling objects...
    Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
    [1/5] clang++ -MMD -MF /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o.d -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dhimant/opt/anaconda3/envs/detectron/include -I/Users/dhimant/opt/anaconda3/envs/detectron/include -arch x86_64 -arch x86_64 -I/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/TH -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/THC -I/Users/dhimant/opt/anaconda3/envs/detectron/include/python3.7m -c -c /Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.cpp -o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [2/5] clang++ -MMD -MF /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o.d -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dhimant/opt/anaconda3/envs/detectron/include -I/Users/dhimant/opt/anaconda3/envs/detectron/include -arch x86_64 -arch x86_64 -I/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/TH -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/THC -I/Users/dhimant/opt/anaconda3/envs/detectron/include/python3.7m -c -c /Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.cpp -o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [3/5] clang++ -MMD -MF /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o.d -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dhimant/opt/anaconda3/envs/detectron/include -I/Users/dhimant/opt/anaconda3/envs/detectron/include -arch x86_64 -arch x86_64 -I/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/TH -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/THC -I/Users/dhimant/opt/anaconda3/envs/detectron/include/python3.7m -c -c /Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.cpp -o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [4/5] clang++ -MMD -MF /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o.d -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dhimant/opt/anaconda3/envs/detectron/include -I/Users/dhimant/opt/anaconda3/envs/detectron/include -arch x86_64 -arch x86_64 -I/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/TH -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/THC -I/Users/dhimant/opt/anaconda3/envs/detectron/include/python3.7m -c -c /Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.cpp -o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    [5/5] clang++ -MMD -MF /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/vision.o.d -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dhimant/opt/anaconda3/envs/detectron/include -I/Users/dhimant/opt/anaconda3/envs/detectron/include -arch x86_64 -arch x86_64 -I/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/TH -I/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/include/THC -I/Users/dhimant/opt/anaconda3/envs/detectron/include/python3.7m -c -c /Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/vision.cpp -o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_clang"' '-DPYBIND11_STDLIB="_libcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1002"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    clang++ -bundle -undefined dynamic_lookup -L/Users/dhimant/opt/anaconda3/envs/detectron/lib -L/Users/dhimant/opt/anaconda3/envs/detectron/lib -arch x86_64 -arch x86_64 /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/vision.o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/cocoeval/cocoeval.o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/ROIAlignRotated/ROIAlignRotated_cpu.o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/box_iou_rotated/box_iou_rotated_cpu.o /Users/dhimant/Desktop/detectron2/build/temp.macosx-10.7-x86_64-3.7/Users/dhimant/Desktop/detectron2/detectron2/layers/csrc/nms_rotated/nms_rotated_cpu.o -L/Users/dhimant/opt/anaconda3/envs/detectron/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.macosx-10.7-x86_64-3.7/detectron2/_C.cpython-37m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: library not found for -lstdc++
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang++' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/dhimant/opt/anaconda3/envs/detectron/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/dhimant/Desktop/detectron2/setup.py'"'"'; __file__='"'"'/Users/dhimant/Desktop/detectron2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

## Expected behavior:
Detectron2 to install 
## Environment:
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/gz/b3vm3h8d029c654z8yntjkw00000gn/T/
CONDA_SHLVL=2
CONDA_PROMPT_MODIFIER=(detectron) 
TERM_PROGRAM_VERSION=440
OLDPWD=/Users/dhimant/desktop
TERM_SESSION_ID=93BCE59D-1F9C-40A7-9B43-FEE2D66B371D
USER=dhimant
CONDA_EXE=/Users/dhimant/opt/anaconda3/bin/conda
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.JV2ConOWJt/Listeners
_CE_CONDA=
CONDA_PREFIX_1=/Users/dhimant/opt/anaconda3
PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/bin:/Users/dhimant/opt/anaconda3/envs/detectron/bin:/Users/dhimant/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
CONDA_PREFIX=/Users/dhimant/opt/anaconda3/envs/detectron
__CFBundleIdentifier=com.apple.Terminal
PWD=/Users/dhimant/desktop/detectron2
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
XPC_FLAGS=0x0
_CE_M=
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/dhimant
CONDA_PYTHON_EXE=/Users/dhimant/opt/anaconda3/bin/python
LOGNAME=dhimant
LC_CTYPE=UTF-8
CONDA_DEFAULT_ENV=detectron
DISPLAY=/private/tmp/com.apple.launchd.Sxsjkop9Mv/org.xquartz:0
_=/usr/bin/env

**Comment by ppwwyyxx** [comment] 2021-12-15 00:40
Duplicate of #2828

**Closed by ppwwyyxx** 2021-12-15 00:40 UTC
