### ISSUE TITLE
Undefined Symbol Build Failing in ArchLinux 5.15.11-arch2-1

### ISSUE THREAD

**Issue by hsakbo** [facebookresearch/detectron2#3830] opened 2021-12-27 07:04 UTC
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
None. Build Error, mangled name is absent.

2. What exact command you run:
```
conda activate torch110  # env containing pytorch 1.10 and other relevant packages
git clone https://github.com/facebookresearch/detectron2
cd detectron2
pip install -e .
```

Note that I already installed it with `python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'` followed by an uninstall due to the same build error. 

3. __Full logs__ or other relevant observations:
python demo.py -h output:
```
Traceback (most recent call last):
  File "/home/someuser/Documents/secret/pose-detect/detectron2/demo/demo.py", line 14, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/someuser/Documents/secret/pose-detect/detectron2/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/someuser/Documents/secret/pose-detect/detectron2/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/someuser/Documents/secret/pose-detect/detectron2/detectron2/structures/__init__.py", line 3, in <module>
    from .image_list import ImageList
  File "/home/someuser/Documents/secret/pose-detect/detectron2/detectron2/structures/image_list.py", line 8, in <module>
    from detectron2.layers.wrappers import shapes_to_tensor
  File "/home/someuser/Documents/secret/pose-detect/detectron2/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/someuser/Documents/secret/pose-detect/detectron2/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: /home/someuser/Documents/secret/pose-detect/detectron2/detectron2/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
```

No stderr output from pip during installation.

4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:

Build correctly.

## Environment:

```
----------------------  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
numpy                   1.20.1
detectron2              0.6 @/home/secret/Documents/secret/pose-detect/detectron2/detectron2
detectron2._C           not built correctly: /home/secret/Documents/secret/pose-detect/detectron2/detectron2/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
Compiler ($CXX)         c++ (GCC) 11.1.0
CUDA compiler           Build cuda_11.5.r11.5/compiler.30672275_0
detectron2 arch flags   6.1
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.10.1 @/home/secret/miniconda3/envs/torch110/lib/python3.9/site-packages/torch
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce MX330 (arch=6.1)
Driver version          495.46
CUDA_HOME               /opt/cuda
Pillow                  8.3.2
torchvision             0.11.2 @/home/secret/miniconda3/envs/torch110/lib/python3.9/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20211023
iopath                  0.1.9
cv2                     4.5.4
----------------------  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

```

Does this output imply I need a lower gcc version?

**Comment by ppwwyyxx** [comment] 2021-12-27 08:16
Duplicate of https://github.com/facebookresearch/detectron2/issues/3117. Yes, using an older gcc (one that's compatible with anaconda's runtime) will likely solve the issue.

**Closed by ppwwyyxx** 2021-12-27 08:16 UTC
