### ISSUE TITLE
Can Perform Rotation Mask-Rcnn using this Repo? if yes Can you tell me the Instructions how can i use this for that?

### ISSUE THREAD

**Issue by yashwant07** [facebookresearch/detectron2#2623] opened 2021-02-15 08:06 UTC
I Need this to explore more using the Decetron 2
how can I train the model on XYWHA?
I have a data in instance segmentation with coco-fromat

**Comment by ppwwyyxx** [comment] 2021-02-15 15:43
Duplicate of #21

**Closed by ppwwyyxx** 2021-02-15 15:43 UTC
