### ISSUE TITLE
Compilation Error on CUDA 11.0

### ISSUE THREAD

**Issue by Ze-Yang** [facebookresearch/detectron2#2359] opened 2020-12-09 07:00 UTC
## Instructions To Reproduce the Issue:
I just want to build detectron2 from source on CUDA 11.0 since RTX 3090 only support CUDA 11.x, but I end up running into an error describled below. Note that I try with detectron2 v0.1 originally with failure, so intuitively I guess that perhap this version is too outdated that it cannot be compiled under CUDA 11.0. However, even after I clone the newest version, it still throws out the same error. Any help would be appreciated. Thanks.

1. Full runnable code or full changes you made:
no change

2. What exact command you run:
python -m pip install -e detectron2

3. __Full logs__ you observed:
[build.log](https://github.com/facebookresearch/detectron2/files/5664001/build.log)

## Environment:
```
----------------------  -------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.3 @/home/zeyang/tmp/detectron2/detectron2
detectron2._C           not built correctly: No module named 'detectron2._C'
Compiler                c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CUDA compiler           Build cuda_11.0_bu.TC445_37.28540450_0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.0 @/home/zeyang/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch
PyTorch debug build     True
GPU available           True
GPU 0,1                 GeForce RTX 3090 (arch=8.6)
CUDA_HOME               /home/zeyang/cuda-11.0
Pillow                  8.0.1
torchvision             0.8.1 @/home/zeyang/anaconda3/envs/detectron2/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0
fvcore                  0.1.2.post20201209
cv2                     Not found
----------------------  -------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

**Comment by banzhuan37** [comment] 2020-12-09 14:36
I have the same problem when rebuilt the environment, previous successfully built detectron2 does not has  detectron2._C  as a install requirement, I dont know what is this file about?

**Comment by ppwwyyxx** [comment] 2020-12-10 00:58
Duplicate of #2225

**Closed by ppwwyyxx** 2020-12-10 00:58 UTC
