### ISSUE TITLE
AR and AP is -1 for medium and large objects

### ISSUE THREAD

**Issue by Ghul-huan** [facebookresearch/detectron2#574] opened 2019-12-24 06:04 UTC
In my validation set ,both the width and height of the objects to be detected are greater than 200   (the data  in validation set only  made the default  augmentation  ,and generally the objects  to be detected accounts for nearly half the size of the image, but the AP and AR of the large objects  are both -1 ，why ( what I mean is most of the objects to be detected are large objects ,so the AP and AR cannot be -1  )?

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.506
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.926
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.461
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.614
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.601
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.616
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.616
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.616
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
[12/23 18:27:16 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs   |   APm    |   APl    |
|:------:|:------:|:------:|:------:|:--------:|:--------:|
| 50.629 | 92.602 | 46.090 | 61.386 | -100.000 | -100.000 |

**Comment by Ghul-huan** [comment] 2019-12-24 06:27
Where is the big guy  @ppwwyyxx

**Comment by ppwwyyxx** [comment] 2019-12-24 06:36
Maybe try visualizing its predictions to see whether it's doing anything reasonable.

If yes, then it sounds odd but we cannot investigate this issue if we cannot reproduce it.

**Comment by hungthanhpham94** [comment] 2020-01-01 00:37
I also have encountered this issue. In my experiment, APs = -100.00, and I try to count the number of small objects (area < 1024). Thus, the number of small objects is zero. I think this explain why APs = -1 in my experiment.
Hope that my idea will help you. Please tell me, if you find out other reasons!

**Comment by a8252525** [comment] 2020-01-15 11:34
I visualize the picture and it is normal and predict quit well, but get -1 in AP, AP50... etc. 
I believed that original point was in down left, but it's in the top left. I got wrong bbox for sure.
Get the right AP value after I fix the bbox.

**Comment by ppwwyyxx** [comment] 2020-01-19 09:00
Closing as there is no information how to reproduce the issue.

**Closed by ppwwyyxx** 2020-01-19 09:00 UTC
