### ISSUE TITLE
each AP for per-category segmentation

### ISSUE THREAD

**Issue by arnaldododo** [facebookresearch/detectron2#2804] opened 2021-03-24 10:06 UTC
Hi, thank you for such an amazing framework.

My question is, how to display all AP (AP0.5 AP.0.75 AP) for each category in instance segmentation inference?
the current output is only showing the main AP for per-category segmentation.
I can't find this on the documentation.

**Comment by ppwwyyxx** [comment] 2021-03-24 22:38
Duplicate of #1877,#1050

**Closed by ppwwyyxx** 2021-03-24 22:38 UTC
