### ISSUE TITLE
How to use human pose keypoint detection and instance segmentation using the same backbone?

### ISSUE THREAD

**Issue by lyshuga** [facebookresearch/detectron2#590] opened 2019-12-28 13:00 UTC
Hi, I was wondering how to use simultaneously human pose keypoint detection and instance segmentation using the same backbone (but obviously different heads) so that it would increase performance? 

The approach is shown in Detectron2 presentation 
![image](https://user-images.githubusercontent.com/4839500/71544018-a6413500-2982-11ea-8de0-85df3e6051c3.png)
https://ai.facebook.com/blog/-detectron2-a-pytorch-based-modular-object-detection-library-/

**Comment by ppwwyyxx** [comment] 2019-12-28 18:59
duplicate of #17

**Closed by ppwwyyxx** 2019-12-28 18:59 UTC
