### ISSUE TITLE
Test Time Augmentation (TTA) support for Keypoints

### ISSUE THREAD

**Issue by jackkwok** [facebookresearch/detectron2#2436] opened 2020-12-31 22:17 UTC
I see inverse transform called on the output bboxes but I don't see it being called on the keypoints.

Code that calls inverse() on the output bboxes:
https://github.com/facebookresearch/detectron2/blob/master/detectron2/modeling/test_time_augmentation.py#L238

Is keypoints TTA not implemented?

**Comment by ppwwyyxx** [comment] 2021-01-03 22:03
The file says: https://github.com/facebookresearch/detectron2/blob/f71d8458e7fb9a45bf46518e8371bef5a8afb93e/detectron2/modeling/test_time_augmentation.py#L108

**Comment by ppwwyyxx** [comment] 2021-02-27 03:43
Duplicate of #1246

**Closed by ppwwyyxx** 2021-02-27 03:43 UTC
Labels: enhancement

**Comment by eaedk** [comment] 2021-09-13 11:25
PLEASE I WOULD LIKE TO KNOW HOW TO FINETUNE THE KEYPOINT PART ON MY OWN CUSTOM DATASET ... IT DOESN'T WORK. I HAVE A DATASET WITH 4 KEYPOINTS
