### ISSUE TITLE
When will detectron2go release ???

### ISSUE THREAD

**Issue by hoangtubatu123** [facebookresearch/detectron2#903] opened 2020-02-19 07:20 UTC
Detectron2 is the best framework to detection object. 
I need to run model in mobile. When will detectron deploy for production???/
Thanks

**Comment by ppwwyyxx** [comment] 2020-02-19 07:36
Duplicate of #448.
You can already do so through caffe2: https://detectron2.readthedocs.io/tutorials/deployment.html

**Closed by ppwwyyxx** 2020-02-19 07:36 UTC
