### ISSUE TITLE
how to get AP50 each object? 

### ISSUE THREAD

**Issue by leesangjoon1** [facebookresearch/detectron2#2249] opened 2020-11-10 13:50 UTC
How to get AP50 each object??

It is too hard to make code

so I find coco codes in folder. and try to fix it to get ap 50 each object

but It was failed

so I want to know how to get that please

**Comment by ppwwyyxx** [comment] 2020-11-10 20:12
Duplicate of #1877, #1050

**Closed by ppwwyyxx** 2020-11-10 20:12 UTC

**Comment by leesangjoon1** [comment] 2020-11-11 05:53
There is not any other way? Only make that code?? 

yesterday I try to change cocoeval.py code other ways but it fail. too hard to change

I think detectron2 AP50 accuracy per claass is too hard

**Comment by ppwwyyxx** [comment] 2020-11-11 06:26
Added in #1877 how to change it.

**Comment by leesangjoon1** [comment] 2020-11-12 01:30
Thank you for your reply

It is so helpful to me!!!!!!!!!!! very very Thanks a lot!!!!!!!

and I wonder why precision[0, :, idx: 0, -1] is ap 50??? I changed -1 to 0 but it was not. 

can you explain that? 

Thank you!
