### ISSUE TITLE
I wanna know what's the differents between the MaskRCNN's R-50-FPN in maskrcnn-benchmark and detectron2

### ISSUE THREAD

**Issue by BIYTC** [facebookresearch/detectron2#1310] opened 2020-04-27 12:04 UTC
I noticed in maskrcnn-benchmark, the size of the model "mask R-50-FPN" is 338M, while in detectron2,this size is 170M, why?

**Comment by pvtien96** [comment] 2020-04-27 15:41
I think the docs explained, have a look at this:
https://detectron2.readthedocs.io/notes/compatibility.html#compatibility-with-detectron-and-maskrcnn-benchmark

**Comment by ppwwyyxx** [comment] 2020-04-28 07:18
Sounds like a duplicate of #1154. If not, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md): how do you get "the model" and how do you tell its size.

**Closed by ppwwyyxx** 2020-04-28 07:18 UTC
