### ISSUE TITLE
need SoftmaxFocalLoss

### ISSUE THREAD

**Issue by shiyongde** [facebookresearch/detectron2#90] opened 2019-10-16 08:59 UTC
## 🚀 Feature
The detectron has SoftmaxFocalLoss , I think It's useful for some cases. 

The pytorch already has the code : 
https://github.com/pytorch/pytorch/blob/821b5f138a987807032a2fd908fe10a5be5439d9/modules/detectron/softmax_focal_loss_op.cu

Could you merge this ?

**Comment by ppwwyyxx** [comment] 2019-10-16 16:39
duplicate of https://github.com/facebookresearch/fvcore/issues/5

**Closed by ppwwyyxx** 2019-10-16 16:39 UTC
