### ISSUE TITLE
torch.cuda.amp.autocast causes CPU Memory Leak during inference

### ISSUE THREAD

**Issue by danielgordon10** [facebookresearch/detectron2#2381] opened 2020-12-12 19:18 UTC
I have a bug where when using `torch.cuda.amp.autocast` on float32 inputs causes some sort of CPU (not GPU) memory leak. There seem to be a few conditions to make this happen:
  - I must be using torch.cuda.amp.autocast
  - I must use real images (random noise does not cause the issue)
  - I cannot use the same image over and over (hence the image augmentation here), and weak augmentation like fliplr sometimes, but not always, causes the issue.
  - The data must be converted to float32 before feeding it into the model, feeding in uint8 does not cause the issue.
  - Some batch sizes do not seem to cause the issue, others cause it to happen faster. Batch size of 1 does not cause the issue, batch size of 3 causes the issue faster than batch size of 5.
  - I must wait 1100 batches (of size 3) before the CPU RAM changes at all, after that point, it climbs by about 100MB/s or 100MB/18 images.

## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```python

import copy
import glob
import os

import detectron_utils  # Package for loading pretrained model

import cv2
import imgaug.augmenters as iaa
import numpy as np
import torch
import tqdm

data_jpg = sorted(glob.glob("*.jpg")))[:3]
images = np.asarray([cv2.imread(path) for path in data_jpg])

model, cfg = detectron_utils.get_detectron2_model()  # Loads a pretrained model
model.cuda()
model.eval()

augmenter = iaa.Sequential(
    [
        iaa.Fliplr(0.5),
        iaa.Sometimes(0.25, iaa.OneOf([iaa.Grayscale(alpha=(0.0, 1.0)), iaa.Grayscale(alpha=1)])),
        iaa.Sometimes(0.5, iaa.Crop(percent=(0, 0.25))),
    ]
)

for _ in tqdm.trange(100000):
    batch = augmenter(images=copy.deepcopy(images), return_batch=True).images_aug
    with torch.no_grad():
        image_list = [{"image": torch.as_tensor(im.transpose(2, 0, 1), dtype=torch.float32)} for im in batch]
        with torch.cuda.amp.autocast():
            outputs = model(image_list)
```

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
```

```
----------------------  ---------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.19.1
detectron2              failed to import
detectron2._C           not built correctly: No module named 'detectron2'
Compiler                c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CUDA compiler           Cuda compilation tools, release 10.2, V10.2.89
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.7.0 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201009
cv2                     4.4.0
----------------------  ---------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment] 2020-12-13 22:33
Thanks, could you make the instructions reproducible by replacing `detectron_utils` with some code others can run?

**Comment by danielgordon10** [comment] 2020-12-14 00:28
```python

import copy
import pdb

import cv2
import imgaug.augmenters as iaa
import numpy as np
import torch
import tqdm

from detectron2 import model_zoo
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.config import get_cfg
from detectron2.data import MetadataCatalog
from detectron2.modeling import build_model
from detectron2.utils.visualizer import Visualizer

VISUALIZE = False

image_path = "input.jpg"
images = np.asarray([cv2.imread(image_path)] * 3)
print("num images", len(images))

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
model = build_model(cfg)
DetectionCheckpointer(model).load(cfg.MODEL.WEIGHTS)
model.cuda()
model.eval()

augmenter = iaa.Sequential(
    [
        iaa.Fliplr(0.5),
        iaa.Sometimes(0.25, iaa.OneOf([iaa.Grayscale(alpha=(0.0, 1.0)), iaa.Grayscale(alpha=1)])),
        iaa.Sometimes(0.5, iaa.Crop(percent=(0, 0.25))),
        iaa.Sometimes(0.5, iaa.Rotate((-20, 20), fit_output=False, mode="constant")),
    ]
)

for _ in tqdm.trange(100000):
    batch = augmenter(images=copy.deepcopy(images), return_batch=True).images_aug
    with torch.no_grad():
        image_list = [{"image": torch.as_tensor(im.transpose(2, 0, 1), dtype=torch.float32)} for im in batch]
        with torch.cuda.amp.autocast():
            outputs = model(image_list)

        if VISUALIZE:
            for ii in range(len(images)):
                output = outputs[ii]
                v = Visualizer(batch[ii][:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
                out = v.draw_instance_predictions(output["instances"].to("cpu"))
                cv2.imwrite(f"third_party/detectron2/output_{ii}.jpg", out.get_image()[:, :, ::-1])
```

**Comment by ppwwyyxx** [comment] 2020-12-14 02:45
This is still not reproducible to me. Running the above code I did not observe memory leak after 5000 iterations.

**Comment by danielgordon10** [comment] 2020-12-14 17:43
That's odd. I installed torch 1.8 nightly to see if I got the same behavior and I still do. I changed one line above to make it leak even faster. 

`image_list = [{"image": torch.as_tensor(im.transpose(2, 0, 1), dtype=torch.int64)} for im in batch]`

Letting it run a bit longer, it seems to slow down how much it leaks/changes the CPU memory, but it still increases over time. That's why I feel like it may be some sort of caching issue where the cache builds up, and then builds up more.


<img width="984" alt="Screen Shot 2020-12-14 at 9 36 17 AM" src="https://user-images.githubusercontent.com/7245472/102115444-6a4feb80-3df0-11eb-887f-b0066ca07e0e.png">
<img width="984" alt="Screen Shot 2020-12-14 at 9 36 50 AM" src="https://user-images.githubusercontent.com/7245472/102115450-6ae88200-3df0-11eb-852d-9d6e661d2da3.png">
<img width="984" alt="Screen Shot 2020-12-14 at 9 37 24 AM" src="https://user-images.githubusercontent.com/7245472/102115451-6b811880-3df0-11eb-8390-8e5ca37cee1c.png">
<img width="984" alt="Screen Shot 2020-12-14 at 9 37 37 AM" src="https://user-images.githubusercontent.com/7245472/102115452-6b811880-3df0-11eb-82ea-40a1c75d3e44.png">
<img width="984" alt="Screen Shot 2020-12-14 at 9 37 43 AM" src="https://user-images.githubusercontent.com/7245472/102115453-6c19af00-3df0-11eb-9e99-2ce786e44ac3.png">
<img width="984" alt="Screen Shot 2020-12-14 at 9 38 30 AM" src="https://user-images.githubusercontent.com/7245472/102115454-6c19af00-3df0-11eb-9929-c391ad24398a.png">
<img width="984" alt="Screen Shot 2020-12-14 at 9 39 42 AM" src="https://user-images.githubusercontent.com/7245472/102115455-6c19af00-3df0-11eb-8538-2ae63c3aaa6d.png">
<img width="984" alt="Screen Shot 2020-12-14 at 9 41 57 AM" src="https://user-images.githubusercontent.com/7245472/102115676-bdc23980-3df0-11eb-875f-f784fbd8d2e6.png">


```
----------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.19.1
detectron2              0.3 @/home/daniel/.cache/bazel/_bazel_daniel/e129a4068b9959ee94dd107d8776cc1f/execroot/com_github_thirdwave_ai_thirdwave/bazel-out/k8-opt/bin/experimental/daniel/collect_env.runfiles/twa_pip_detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.2
detectron2 arch flags   7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.0.dev20201210 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.9.0.dev20201210 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201213
cv2                     4.4.0
----------------------  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
```

**Comment by ppwwyyxx** [comment] 2020-12-15 09:10
Since the issue is probably related to the environment, you may need to provide a full environment (e.g. docker, colab) to reproduce it.

**Comment by danielgordon10** [comment] 2020-12-15 18:38
It appears older versions of Numpy (1.18.5) do not have the issue, but newer versions (1.19.1) do. I'd like to keep the issue open here until we figure out exactly what causes the issue, because I haven't seen other issues with Numpy and detectron.

**Comment by danielgordon10** [comment] 2020-12-15 22:30
I made a conda env where I was able to get the issue as well. I tried making a colab but could not observe the issue.
Conda env:
```
name: temp-env
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2020.12.8=h06a4308_0
  - certifi=2020.12.5=py36h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - dataclasses=0.7=py36_0
  - freetype=2.10.4=h5ab3b9f_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.2=heb0550a_3
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.2.0=py36h23d657b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py36hff7bd54_0
  - olefile=0.46=py36_0
  - openssl=1.1.1i=h27cfd23_0
  - pillow=8.0.1=py36he98fc37_0
  - pip=20.3.1=py36h06a4308_0
  - python=3.6.12=hcff3b4d_2
  - pytorch=1.7.1=py3.6_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=h7b6447c_0
  - setuptools=51.0.0=py36h06a4308_2
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.2=py36
  - torchvision=0.8.2=py36_cu101
  - typing_extensions=3.7.4.3=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.21
    - decorator==4.4.2
    - detectron2==0.3
    - future==0.18.2
    - grpcio==1.34.0
    - idna==2.10
    - imgaug==0.4.0
    - importlib-metadata==3.3.0
    - iopath==0.1.2
    - kiwisolver==1.3.1
    - matplotlib==3.3.3
    - numpy==1.19.1
    - protobuf==3.14.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - requests==2.25.0
    - shapely==1.7.1
    - urllib3==1.26.2
    - zipp==3.4.0
prefix: /home/daniel/miniconda3/envs/temp-env
```

**Comment by bpfliegel** [comment] 2020-12-17 15:16
Hi Daniel,

two things worth trying (helped me with PyTorch related memleaks):

1) using libjemalloc
sudo apt-get update && apt-get -y install libjemalloc-dev
and preloading it:
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 python your_app.py
Reference: https://github.com/pytorch/vision/issues/984#issuecomment-498603088

2) setting LRU_CACHE_CAPACITY
import os
os.environ["LRU_CACHE_CAPACITY"] = "1"
Reference: https://github.com/pytorch/pytorch/issues/27971

I don't face any leaks lately with using these two as default.
Curious to know if that helped you!
Thanks, Bálint

**Comment by danielgordon10** [comment] 2020-12-19 23:12
The change to `libjemalloc` seems to fix the issue, but I don't like this as a solution. Is the claim for this fix that the default malloc has a bug, that pytorch has a bug but libjemalloc fixes it, or something else entirely?

**Comment by ppwwyyxx** [comment] 2020-12-23 11:04
I don't, but maybe pytorch uses it under the hood for me.

Closing as evidence so far points to problems outside of detectron2.

**Closed by ppwwyyxx** 2020-12-23 11:04 UTC
