### ISSUE TITLE
Integrating other types of backbone networks

### ISSUE THREAD

**Issue by dhaivat666** [facebookresearch/detectron2#752] opened 2020-01-24 19:30 UTC
I want to experiment with different backbone networks other than Resnet 50 and Resnet 101. I was wondering what exactly is different in resnet implementation of detectron2 from that of pytorch. And is there any easy way to get other resnets like 18,34,152 or resnext/wider resnets into the system. 
The pytorch repo has other resnets available but I am not sure how to use them within detectron2 system to have different backbone configurations. Any hint in this direction would be apprecitated. Thank you.

**Comment by ppwwyyxx** [comment] 2020-01-24 20:03
Duplicate of #450

**Comment by dhaivat666** [comment] 2020-01-24 20:08
@ppwwyyxx thanks will have a look. I was wondering if there is any significant difference between torchvision resnet and detectron2 resnet implementation? Is there any serious downside for using torchvision resnet?

**Comment by ppwwyyxx** [comment] 2020-01-25 08:30
Architecture-wise torchvision uses `STRIDE_IN_1X1=False` and different input preprocessing.

There is no major downside except that the models won't be comparable with existing papers that are based on the MSRA ResNet.

**Closed** 2020-01-28 15:55 UTC
