### ISSUE TITLE
Have you encountered unstable mAP when training one-stage models in 800x1333?

### ISSUE THREAD

**Issue by poodarchu** [facebookresearch/detectron2#457] opened 2019-12-04 03:27 UTC
## ❓ Questions and Help

General questions about detectron2.

NOTE:

If you met any unexpected issue when using detectron2 and wish to know why,
please use the "Unexpected Problems / Bugs" issue template.
I found that when running retinanet in 800x1333 multiple times, the mAP can vary from 35.8 - 36.3, but this is not the same when training using multi scale.

**Comment by ppwwyyxx** [comment] 2019-12-04 03:46
The variance seems a bit larger than normal but not too large. Closing as this is not a bug, a feature request, or about how to do something detectron2.
If you wish lower variance (but higher bias), you can fix `cfg.SEED`.

**Closed by ppwwyyxx** 2019-12-04 03:46 UTC

**Comment by xmyqsh** [comment] 2019-12-12 04:54
@poodarchu SSD, RPN这套东西，cls的区分度都不够好(同一个object的positive proposal，哪个更重要)，分辨率大了，框多了，cls就有点儿懵逼了
