### ISSUE TITLE
[Docs] Getting error while running: Run panoptic segmentation on a video

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [facebookresearch/detectron2#2899] opened 2021-04-12 06:28 UTC
## 📚 Documentation

* Link to the relevant documentation/comment:

https://detectron2.readthedocs.io/en/latest/tutorials/install.html#installation-inside-specific-environments
https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5

* What is missing or inaccurate?

Getting error while running `Run panoptic segmentation on a video`:
```
ModuleNotFoundError: No module named 'cv2'
```

**Comment by script-hacker** [comment] 2021-04-12 10:59
the library is missing try to import cv2 by using this command "import cv2"

**Comment by ShubhamTatvamasi** [comment] 2021-04-12 19:07
> the library is missing try to import cv2 by using this command "import cv2"

It is already installed

**Comment by ppwwyyxx** [comment] 2021-04-14 09:47
Duplicate of #2901

**Closed by ppwwyyxx** 2021-04-14 09:47 UTC
Labels: documentation
