### ISSUE TITLE
More than 100 Objects as maximum

### ISSUE THREAD

**Issue by ChristophNeuner** [facebookresearch/detectron2#1164] opened 2020-04-06 12:11 UTC
Hello everybody,

I am using detectron2 to achieve instance segmentation of nuclei.
I have noticed during inference and have also read here:
https://medium.com/@hirotoschwert/digging-into-detectron-2-47b2e794fabd

that the ROI Head (Box Head) only outputs a maximum of 100 Objects in the end.
Unfortunately, in my pictures there are far more than 100 nuclei.
I have already managed to increase the number of region proposals, but cannot find the right place in the code to output more than 100 objects.
I hope someone can help me with that or hint me in the right direction.

If necessary, my code can be found here:
https://github.com/ChristophNeuner/nuclei_detection

Thanks in advance,

Christoph

**Comment by bendidi** [comment] 2020-04-06 12:59
Hi @ChristophNeuner, 

during inference, you only need to modify `cfg.TEST.DETECTIONS_PER_IMAGE` to whatever number you want to have more than 100 detections per image

**Comment by ChristophNeuner** [comment] 2020-04-06 14:21
Thanks a lot!
I guess during training the library can adapt automatically?

**Comment by ppwwyyxx** [comment] 2020-04-06 18:01
Duplicate of #1045 

> during training there is no upper bound to the number of objects that are predicted?

during training the model does not predict objects.

**Closed by ppwwyyxx** 2020-04-06 18:01 UTC

**Comment by emilhovad** [comment] 2020-10-21 15:21
> Hi @ChristophNeuner,
> 
> during inference, you only need to modify `cfg.TEST.DETECTIONS_PER_IMAGE` to whatever number you want to have more than 100 detections per image

I have done this and I still am only getting 100 outputs?
