### ISSUE TITLE
MODEL.TENSOR_MASK

### ISSUE THREAD

**Issue by woshiwoyali** [facebookresearch/detectron2#622] opened 2020-01-04 07:16 UTC
I am trying to run a pre-trained TensorMask model, but encounter the following error:
KeyError: 'Non-existent config key: MODEL.TENSOR_MASK'

**Comment by ppwwyyxx** [comment] 2020-01-04 07:40
Github already tells you the answer:
![DeepinScreenshot_select-area_20200103233945](https://user-images.githubusercontent.com/1381301/71762287-5ed70f00-2e82-11ea-8ae3-4e3e4c861cb5.png)

Duplicate of #616

**Closed by ppwwyyxx** 2020-01-04 07:40 UTC
