### ISSUE TITLE
Fail to load opencl runtime when import detectron2

### ISSUE THREAD

**Issue by lixincn2015** [facebookresearch/detectron2#123] opened 2019-10-19 10:56 UTC
I have built a docker image with the provided Dockerfile.
But when I import detectron2 in the docker container,  it reports "Failed to load OpenCL runtime".
I have googled this problem and have installed ocl-icd-opencl-dev , but this do not solve the problem.
Any help?

**Comment by ppwwyyxx** [comment] 2019-10-19 18:48
duplicate of #87

**Closed by ppwwyyxx** 2019-10-19 18:48 UTC
