### ISSUE TITLE
Two rotated boxes are nearly identical to very high precision, but do not yield an iou of 1.0

### ISSUE THREAD

**Issue by alekseynp** [facebookresearch/detectron2#2167] opened 2020-10-22 05:27 UTC
Two rotated boxes are nearly identical to very high precision, but do not yield an IoU of 1.0
This is probably some strange edge case in the calculation.
How do I come upon this? Some of my data has been partially labelled by a model and the rotated COCO evaluation is giving me unstable results if I submit boxes that are again created with the same model.

## Instructions To Reproduce the 🐛 Bug:
```
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from detectron2.layers.rotated_boxes import pairwise_iou_rotated
>>> pairwise_iou_rotated(torch.tensor([[2563.74462890625000000000, 1436.79016113281250000000, 2174.70336914062500000000,  214.09500122070312500000, 115.11834716796875000000]]), torch.tensor([[2563.74462890625000000000, 1436.79028320312500000000, 2174.70288085937500000000,  214.09495544433593750000, 115.11835479736328125000]]))
tensor([[0.5848]])
```

## Expected behaviour:
```
tensor([[1.0000]])
```

## Environment:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py
----------------------  --------------------------------------------------------------------------------
sys.platform            linux
Python                  3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
numpy                   1.19.1
detectron2              0.2.1 @/host_home/code/detectron2/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   7.0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0 @/home/user/.conda/envs/detectron2/lib/python3.7/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   Quadro GV100 (arch=7.0)
GPU 1                   GeForce RTX 2080 Ti (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  7.1.2
torchvision             0.7.0 @/home/user/.conda/envs/detectron2/lib/python3.7/site-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201020
cv2                     4.2.0
----------------------  --------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

```

**Comment by ppwwyyxx** [comment] 2020-10-22 09:47
Duplicate of #2154

**Closed by ppwwyyxx** 2020-10-22 09:47 UTC
