### ISSUE TITLE
TorchScript support?

### ISSUE THREAD

**Issue by coder-james** [facebookresearch/detectron2#113] opened 2019-10-18 07:51 UTC
I used jit.trace with DefaultPredictor.model to converting my pytorch model, but encountered some problems, e.g. input/output tensor wrong type and '_ROIAlign' could not export. Any suggestion for torchscript?

**Comment by zxf8665905** [comment] 2019-10-18 07:55
Duplicate of #46

**Closed** 2019-10-18 07:58 UTC
Labels: duplicate
