### ISSUE TITLE
In TridentNet, is Scale-aware Training Scheme Supported?

### ISSUE THREAD

**Issue by Leeehow** [facebookresearch/detectron2#515] opened 2019-12-12 06:19 UTC
## ❓ How to use **scale-aware training scheme** in Detectron2?

It seems that **scale-aware training scheme** has not be included in **TridentNet** project. Is there any suggestions to apply it to TridentNet?

**Comment by ppwwyyxx** [comment] 2019-12-12 07:04
duplicate of #413 . you need to implement it yourself if you want.

**Closed by ppwwyyxx** 2019-12-12 07:04 UTC
