### ISSUE TITLE
Start training from scratch

### ISSUE THREAD

**Issue by WellDL** [facebookresearch/detectron2#1737] opened 2020-07-08 11:19 UTC
Hello,

I have read older threads about this topic however I do not understand quite.

I want to start a training from scratch for:

1) RetinaNet
2) Faster R-CNN

What do I need to note when starting training from scratch except of `cfg.MODEL.WEIGHTS = ""` to distinguish training between faster rcnn and retinanet?

**Comment by ppwwyyxx** [comment] 2020-07-09 01:30
Duplicate of #558

**Closed by ppwwyyxx** 2020-07-09 01:30 UTC
Labels: duplicate

**Comment by WellDL** [comment] 2020-07-09 15:02
Yes I read that too. Do I understand it right that **RetinaNet and Faster R-CNN** can't be trained from scratch?

Only these are mentioned for training from scratch however these are configurations for **Mask R-CNN**.

Baseline R50-FPN | 3x
GN | 3x 
SyncBN | 3x 
GN (from scratch) | 3x 
GN (from scratch) | 9x 
SyncBN (from scratch) | 9x

**Comment by ppwwyyxx** [comment] 2020-07-09 19:45
They can all be trained from scratch with similar configurations.
