### ISSUE TITLE
About v0.1 release feature: Support training with segmentation annotations in binary mask format.

### ISSUE THREAD

**Issue by pvtien96** [facebookresearch/detectron2#972] opened 2020-03-02 14:32 UTC
## 🚀 Feature
Hi, I've read that v0.1 will "Support training with segmentation annotations in binary mask format."
So may I ask that when will this feature be developed/released? 
## Motivation
To implement detectron2 on many available binary-mask datasets!
## Pitch
By the time waiting for that feature, I was wondering about the code to convert binary-mask to coco-format, is there any source available? Can you tell me weather the code in this [link](https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch)  is true?
If not, what should I do? 
Many thanks!

**Comment by ppwwyyxx** [comment] 2020-03-02 18:21
The feature is included in the v0.1 release, released  25 days ago.
Duplicate of #200.

**Closed by ppwwyyxx** 2020-03-02 18:21 UTC
