### ISSUE TITLE
Running detectron2 docker without GPU 

### ISSUE THREAD

**Issue by vipinvijay1986** [facebookresearch/detectron2#2047] opened 2020-09-19 02:47 UTC
Hi Team , 
I want to run detectron2 cpu image on docker. But it's giving Segmentation fault error on import
`from detectron2.engine import DefaultPredictor`

## Instructions To Reproduce the Issue:

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. I used the following steps to create a docker file 
```

FROM python:3.8-slim-buster

RUN apt-get update -y

# gcc compiler and opencv prerequisites
RUN apt-get -y install nano git build-essential libglib2.0-0 libsm6 libxext6 libxrender-dev sudo cmake ninja-build

# Detectron2 prerequisites
RUN pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install cython
RUN pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

RUN pip install -U 'git+https://github.com/facebookresearch/fvcore'

# Detectron2 - CPU copy
#RUN python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/index.html
#RUN python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cpu/torch1.6/index.html
# Development packages
RUN git clone https://github.com/facebookresearch/detectron2 detectron2_repo 
RUN pip install -e detectron2_repo
RUN pip install flask flask-cors requests opencv-python
```
2. what exact command you run:
```
# version inspection
import detectron2
print(f"Detectron2 version is {detectron2.__version__}")

# import some common detectron2 utilities
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.data import MetadataCatalog
import cv2
import requests
import numpy as np

# load an image of Lionel Messi with a ball
image_reponse = requests.get("https://upload.wikimedia.org/wikipedia/commons/4/41/Leo_Messi_v_Almeria_020314_%28cropped%29.jpg")
image_as_np_array = np.frombuffer(image_reponse.content, np.uint8)
image = cv2.imdecode(image_as_np_array, cv2.IMREAD_COLOR)


# create config
cfg = get_cfg()
# below path applies to current installation location of Detectron2
cfgFile = "/usr/local/lib/python3.8/site-packages/detectron2/model_zoo/configs/COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"
cfg.merge_from_file(cfgFile)
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
cfg.MODEL.WEIGHTS = "detectron2://COCO-Detection/faster_rcnn_R_101_FPN_3x/137851257/model_final_f6e8b1.pkl"
cfg.MODEL.DEVICE = "cpu" # we use a CPU Detectron copy

# create predictor
predictor = DefaultPredictor(cfg)

# make prediction
output = predictor(image)
print(output)
```

3. __full logs__ you observed:
```
Detectron2 version is 0.2.1
Segmentation fault  
```

## Expected behavior:

Ideally, the example should work and I followed the link [Detectron2 : The bare basic end to end tutorial](https://towardsdatascience.com/detectron2-the-basic-end-to-end-tutorial-5ac90e2f90e3)

## Environment:

Provide your environment information using the following command:
```
wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py

---------------------  -------------------------------------------------------------
sys.platform           linux
Python                 3.8.5 (default, Sep 10 2020, 16:58:22) [GCC 8.3.0]
numpy                  1.19.2
detectron2             0.2.1 @/detectron2_repo/detectron2
Compiler               GCC 8.3
CUDA compiler          not available
DETECTRON2_ENV_MODULE  <not set>
PyTorch                1.6.0+cpu @/usr/local/lib/python3.8/site-packages/torch
PyTorch debug build    False
GPU available          False
Pillow                 7.2.0
torchvision            0.7.0+cpu @/usr/local/lib/python3.8/site-packages/torchvision
fvcore                 0.1.2
---------------------  -------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=0, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
```

**Comment by ppwwyyxx** [comment] 2020-09-19 09:27
Duplicate of https://github.com/pytorch/pytorch/issues/43834. Please install `opencv-python-headless` in container to avoid this issue.

**Closed by ppwwyyxx** 2020-09-19 09:27 UTC
