### ISSUE TITLE
Weight initialization for cutom backbone

### ISSUE THREAD

**Issue by dhaivat666** [facebookresearch/detectron2#755] opened 2020-01-27 01:10 UTC
## ❓ How to use initialize weights for non-standard architecture?

I have added ResNet-200 and other custom ResNets for my purpose. However, there are no weights to initialize. I was wondering how to initialize weights to avoid NaN loss. Currently, I am just defining the model but loss becomes infinite/NaN right at iteration 0. Is there any easy way to get rid of this issue through any weight initialization procedure? Apologies if this issue has been raised, since I couldn't find anything, hence the issue.

**Comment by ppwwyyxx** [comment] 2020-01-27 14:35
Duplicate of #558.

**Closed by ppwwyyxx** 2020-01-27 14:35 UTC
