### ISSUE TITLE
'NoneType' object has no attribute 'missing_keys' in detection_checkpoint.py

### ISSUE THREAD

**Issue by rezamirshahi** [facebookresearch/detectron2#1274] opened 2020-04-21 17:06 UTC
**after running the following code on google colab:**
`from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file("/content/detectron2_repo/configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("Atypical",)
cfg.DATASETS.TEST = ()   # no metrics implemented for this dataset
cfg.DATALOADER.FILTER_EMPTY_ANNOTATIONS=False
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"  # initialize from model zoo
#cfg.MODEL.WEIGHTS = "/content/data/model_final.pth"
cfg.SOLVER.IMS_PER_BATCH = 4
cfg.SOLVER.BASE_LR = 0.005
cfg.SOLVER.MAX_ITER = 500    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 512   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1  # 1 class (Atypical)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg)
trainer.resume_or_load(resume=False)
trainer.train()  `

**I get the following error on "trainer.resume_or_load(resume=False)":**

> 

 AttributeError                            Traceback (most recent call last)
<ipython-input-8-0674e5ebb88e> in <module>()
     19 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
     20 trainer = DefaultTrainer(cfg)
---> 21 trainer.resume_or_load(resume=False)
     22 trainer.train()

3 frames
/content/detectron2_repo/detectron2/checkpoint/detection_checkpoint.py in _load_model(self, checkpoint)
     66             if k in model_buffers:
     67                 try:
---> 68                     incompatible.missing_keys.remove(k)
     69                 except ValueError:
     70                     pass

AttributeError: 'NoneType' object has no attribute 'missing_keys'

> 

**The code was working till yesterday**

**Comment by ppwwyyxx** [comment] 2020-04-21 17:21
Duplicate of #1267

**Closed by ppwwyyxx** 2020-04-21 17:21 UTC
