### ISSUE TITLE
setup fails with `ArgumentInfo is to be a POD struct`

### ISSUE THREAD

**Issue by jshtok** [facebookresearch/detectron2#401] opened 2019-11-26 15:04 UTC
Hi,

Thank you for the great product. I have attempted to run the setup.py, after setting up an environment according to the instructions. After a while of compilation, the compiler failed with the error 

/opt/share/cuda-8.0/x86_64/bin/nvcc -DWITH_CUDA -I/dccstor/jsdata1/dev/2019_projects/SSL/ssdetron2/detectron2/layers/csrc -I/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include -I/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/TH -I/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/THC -I/opt/share/cuda-8.0/x86_64/include -I/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/include/python3.6m -c /dccstor/jsdata1/dev/2019_projects/SSL/ssdetron2/detectron2/layers/csrc/deformable/deform_conv_cuda.cu -o build/temp.linux-x86_64-3.6/dccstor/jsdata1/dev/2019_projects/SSL/ssdetron2/detectron2/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_35,code=sm_35 -std=c++11
/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/c10/core/TensorTypeSet.h(44): warning: integer conversion resulted ina change of sign

/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/torch/csrc/jit/argument_spec.h(68): error: static assertion failed with "ArgumentInfo is to be a POD struct"

/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/profiler.h(97): warning: attribute "__visibility__" does not apply here

/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/torch/csrc/autograd/profiler.h(112): warning: attribute "__visibility__" does not apply here

/dccstor/jsdata1/Anaconda3_x86_64/envs/pytorch_dtron2/lib/python3.6/site-packages/torch/include/pybind11/cast.h(1889): warning: nonstandard use of "auto" to both deduce the type from an initializer and to announce a trailing return type

1 error detected in the compilation of "/tmp/tmpxft_0000684a_00000000-7_deform_conv_cuda.cpp1.ii".
error: command '/opt/share/cuda-8.0/x86_64/bin/nvcc' failed with exit status 2

================================================================

The output of `python detectron2/utils/collect_env.py` is

Traceback (most recent call last):
  File "detectron2/utils/collect_env.py", line 10, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

Any help would be appreciated.

Regards,
Joseph

**Comment by ppwwyyxx** [comment] 2019-11-26 16:54
duplicate of https://github.com/pytorch/pytorch/issues/16257

**Closed by ppwwyyxx** 2019-11-26 16:54 UTC
