### ISSUE TITLE
new pillow version breaks tutorial 

### ISSUE THREAD

**Issue by BisratM** [facebookresearch/detectron2#614] opened 2020-01-02 22:56 UTC
The colab notebook tutorial appears to have been broken over night as it now attempts to use pillow version 7.0.0. Reverting to pillow version 6.2.1 appears to fix all issues.

**Comment by ppwwyyxx** [comment] 2020-01-02 23:07
duplicate of #612

**Closed by ppwwyyxx** 2020-01-02 23:07 UTC
