### ISSUE TITLE
bug in voc_eval() when using custom datasets

### ISSUE THREAD

**Issue by coolermzb3** [facebookresearch/detectron2#1618] opened 2020-06-17 13:04 UTC
## Codes To Reproduce the 🐛 Bug:
```python
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.evaluation import inference_on_dataset, PascalVOCDetectionEvaluator
from detectron2.data import build_detection_test_loader

mymodelpath = './output/model_final.pth'

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 2
cfg.MODEL.WEIGHTS = mymodelpath

dsname = 'face_tiny'  # any custom dataset
evaluator = PascalVOCDetectionEvaluator(dsname)
data_loader = build_detection_test_loader(cfg, dsname)
predictor = DefaultPredictor(cfg)
inference_on_dataset(predictor.model, data_loader, evaluator)
```
I use my custom dataset, but I guess things will happen on any pascal voc style custom dataset. You can try with your own datasets.
## What I get:
The inference process is ok:
```
[06/17 12:56:08 d2.data.common]: Serializing 10 elements to byte tensors and concatenating them all ...
[06/17 12:56:08 d2.data.common]: Serialized dataset takes 0.00 MiB
[06/17 12:56:09 d2.evaluation.evaluator]: Start inference on 10 images
[06/17 12:56:10 d2.evaluation.evaluator]: Total inference time: 0:00:00.396116 (0.079223 s / img per device, on 1 devices)
[06/17 12:56:10 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.065842 s / img per device, on 1 devices)
[06/17 12:56:10 d2.evaluation.pascal_voc_evaluation]: Evaluating face_tiny using 2007 metric. Note that results do not use the official Matlab API.
```
But the evaluation process will raise a Keyerror:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-45-e54d3e4071a6> in <module>()
     20 data_loader = build_detection_test_loader(cfg, dsname)
     21 predictor = DefaultPredictor(cfg)
---> 22 inference_on_dataset(predictor.model, data_loader, evaluator)

2 frames
/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/evaluator.py in inference_on_dataset(model, data_loader, evaluator)
    174     )
    175 
--> 176     results = evaluator.evaluate()
    177     # An evaluator may return None when not in main process.
    178     # Replace it by an empty dict instead to make it easier for downstream code to handle

/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/pascal_voc_evaluation.py in evaluate(self)
    100                         cls_name,
    101                         ovthresh=thresh / 100.0,
--> 102                         use_07_metric=self._is_2007,
    103                     )
    104                     aps[thresh].append(ap * 100)

/usr/local/lib/python3.6/dist-packages/detectron2/evaluation/pascal_voc_evaluation.py in voc_eval(detpath, annopath, imagesetfile, classname, ovthresh, use_07_metric)
    246     fp = np.zeros(nd)
    247     for d in range(nd):
--> 248         R = class_recs[image_ids[d]]
    249         # R = class_recs[imagenames[int(image_ids[d])]]
    250         bb = BB[d, :].astype(float)

KeyError: '6'
```
line 249 above is my fix code:)
## Explanation
I tried to explain in PR #1608 why there will be such a bug:

> Based on the definition in line 226, the key of class_recs should be imagename, instead of image_id.
> Actually, image_id should be the index of imagename in imagenames , but it can be seen from line 231~234 that the type of image_id is string, and need to be converted into int.

After fixing the code and reloading, it can work fine:
```
[06/17 13:00:19 d2.data.common]: Serializing 10 elements to byte tensors and concatenating them all ...
[06/17 13:00:19 d2.data.common]: Serialized dataset takes 0.00 MiB
[06/17 13:00:20 d2.evaluation.evaluator]: Start inference on 10 images
[06/17 13:00:21 d2.evaluation.evaluator]: Total inference time: 0:00:00.401136 (0.080227 s / img per device, on 1 devices)
[06/17 13:00:21 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:00 (0.066796 s / img per device, on 1 devices)
[06/17 13:00:21 d2.evaluation.pascal_voc_evaluation]: Evaluating face_tiny using 2007 metric. Note that results do not use the official Matlab API.
OrderedDict([('bbox',
              {'AP': 65.91453818369455,
               'AP50': 98.98677174218972,
               'AP75': 79.03409090909092})])
```

**Comment by ppwwyyxx** [comment] 2020-06-17 23:12
`PascalVOCDetectionEvaluator` is not meant to support a "pascal voc style" dataset. In fact, it's not clear what is a "pascal voc style" dataset.

That said, if there is a tiny change that can remove some assumptions of the evaluation code, it's OK to add it. However, currently the change in #1608 causes the evaluation to fail for the true pascal voc dataset, which is apparently not acceptable.

**Comment by coolermzb3** [comment] 2020-06-19 01:58
Thank you and I think I find what the problem is~
In detectron2/data/datasets/pascal_voc.py:
```python
with PathManager.open(os.path.join(dirname, "ImageSets", "Main", split + ".txt")) as f:
        fileids = np.loadtxt(f, dtype=np.str)
    ...
    for fileid in fileids:
        anno_file = os.path.join(annotation_dirname, fileid + ".xml")
        jpeg_file = os.path.join(dirname, "JPEGImages", fileid + ".jpg")
    ...
        r = {
            "file_name": jpeg_file,
            "image_id": fileid,
```
`image_id` is defined as the file name(without extension name), so when evaluating the `image_id` and the `image_name` are the same key, so the offical code works fine.

And my project meets error because I defined `image_id` as a number, something like
```python
for idx, fileid in enumerate(fileids):
    "image_id": idx
```
I think maybe I have a misunderstanding of the document of 'Use Custom Datasets'
>`image_id` (str or int): a unique id that identifies this image. Used during evaluation to identify the images, but a dataset may use it for different purposes.

Maybe some more instructions will help others, such as:
>`image_id` (str or int): a unique id that identifies this image. Used during evaluation to identify the images, but a dataset may use it for different purposes. 
>>For pascal voc evaluation, it's recommended to use the filename as image_id. 
>>For coco evaluation, it's recommended to use ...

Thank you again~

**Comment by ppwwyyxx** [comment] 2020-06-19 02:08
Like I said, `PascalVOCDetectionEvaluator` is meant to work for the true pascal voc dataset only. It's not expected to work for a custom dataset, so there are no requirements on what "image_id" should be.

Maybe with #1603 we can expect `PascalVOCDetectionEvaluator` to work for any dataset loaded by `load_voc_instances`.

Closing as this is not a bug or unexpected behavior.

**Closed by ppwwyyxx** 2020-06-19 02:08 UTC
