### ISSUE TITLE
How to fix the mask with fixed color instead of random color

### ISSUE THREAD

**Issue by xiaoxierui** [facebookresearch/detectron2#2169] opened 2020-10-22 09:12 UTC

**Comment by ppwwyyxx** [comment] 2020-10-22 19:41
Unfortunately I could not understand what you attempt to do. Please provide information according to the issue template.

**Comment by xiaoxierui** [comment] 2020-10-23 11:38
> Unfortunately I could not understand what you attempt to do. Please provide information according to the issue template.

I'm a learner of detectron2. When i train my datasats by Pointrend，I trained five categories. But when i validate my dataset， every category in different picture fix different color. I try hard to make a category have same color but i failed，can u help me or just give me some ideas？ Thank u so much。
您好，当我使用Pointrend训练我的数据集时，我标注了5个类别的目标，当我使用训练好的权重预测目标时，在不同的图片中，同一个类别的目标被填充了不同的颜色，我希望预测出的图片中，每一个类别都能使用同一个颜色，但是我查了很多资料也没能实现，但是我知道这可以被实现。您可以帮助我，或者给我几个建议吗？非常感谢您，这对我很重要

**Comment by ppwwyyxx** [comment] 2020-10-23 18:18
Duplicate of #1843

**Closed by ppwwyyxx** 2020-10-23 18:18 UTC
