### ISSUE TITLE
custom Coco dataset evaluation fails 

### ISSUE THREAD

**Issue by shahidul56** [facebookresearch/detectron2#784] opened 2020-02-02 08:13 UTC
name 'unicode' is not defined showing for  custom cocodataset

![fewff](https://user-images.githubusercontent.com/11449967/73605216-a78b0080-45c5-11ea-964e-07d4fb8fe2dd.PNG)

**Comment by ppwwyyxx** [comment] 2020-02-02 09:05
Duplicate of #320.

**Closed by ppwwyyxx** 2020-02-02 09:05 UTC
