### ISSUE TITLE
Define "segmentation" in COCO’s RLE format.

### ISSUE THREAD

**Issue by tema7707** [facebookresearch/detectron2#573] opened 2019-12-23 20:20 UTC
## ❓ How to define "segmentation" in COCO’s RLE format.

Hi!
I am trying to train a model with a custom dataset. I am changing example from google colab. I can successfully visualize my images, but when I try to train the model I get this error:
```
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/content/detectron2/detectron2/data/common.py", line 130, in __iter__
    for d in self.dataset:
  File "/content/detectron2/detectron2/data/common.py", line 102, in __iter__
    yield self.dataset[idx]
  File "/content/detectron2/detectron2/data/common.py", line 39, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/content/detectron2/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/content/detectron2/detectron2/data/dataset_mapper.py", line 128, in __call__
    for obj in dataset_dict.pop("annotations")
  File "/content/detectron2/detectron2/data/dataset_mapper.py", line 129, in <listcomp>
    if obj.get("iscrowd", 0) == 0
  File "/content/detectron2/detectron2/data/detection_utils.py", line 169, in transform_instance_annotations
    polygons = [np.asarray(p).reshape(-1, 2) for p in annotation["segmentation"]]
  File "/content/detectron2/detectron2/data/detection_utils.py", line 169, in <listcomp>
    polygons = [np.asarray(p).reshape(-1, 2) for p in annotation["segmentation"]]
ValueError: cannot reshape array of size 1 into shape (2)
```

I parsed the custom dataset to a dict like in example. And I found the following error is in this block of code: 
```
obj = {
    "bbox": [top_x,top_y,bot_x,bot_y],
    "bbox_mode": BoxMode.XYXY_ABS,
    "segmentation": {'counts': poly, 'size': [height, width]},
    "category_id": int(line["ClassId"]),
    "iscrowd": 0
}
```
Where 'poly' is an array of float.

Could you tell me if I define "segmentation" correctly using the dictionary? I try to define segmentation like the per-pixel segmentation mask in COCO’s RLE format. 
I got beautiful results in visualisation using Visualizer, but I can’t train the model.

Thanks very much!

**Comment by ppwwyyxx** [comment] 2019-12-24 05:55
duplicate of #200

**Closed by ppwwyyxx** 2019-12-24 05:55 UTC
