### ISSUE TITLE
On NVIDIA Jetson AGX Xavier  use Detectron2 

### ISSUE THREAD

**Issue by Kevinstiff** [facebookresearch/detectron2#1234] opened 2020-04-16 09:50 UTC
##

1.Deploy detectron2 .pkl model on NVIDIA Jetson AGX Xavier to accelerate with TensorRT, what should I do?

**Comment by ppwwyyxx** [comment] 2020-04-19 01:06
Duplicate of #192 #915

**Closed by ppwwyyxx** 2020-04-19 01:06 UTC
