### ISSUE TITLE
Train models with background only images

### ISSUE THREAD

**Issue by pkhigh** [facebookresearch/detectron2#203] opened 2019-10-30 20:38 UTC
## 🚀 Feature

I want to train images with no object along with images with multiple objects. Specifically for training instance segmentation models.
## Motivation
I need improve precision of the model. 

## Pitch
a simple parameter like INCLUDE_BKG_IMAGES in default conifg file which can be used to train images with no objects along with images with multiple objects.

**Comment by ppwwyyxx** [comment] 2019-10-31 00:05
duplicate of #80

**Closed by ppwwyyxx** 2019-10-31 00:05 UTC
