### ISSUE TITLE
Exporting Model to Onnx: F.interpolate Keyword argument size unknown

### ISSUE THREAD

**Issue by XDynames** [facebookresearch/detectron2#2906] opened 2021-04-14 04:40 UTC
## Instructions To Reproduce the 🐛 Bug:
1. Full runnable code or full changes you made:
```
diff detectron2/tools/deploy/export_model.py local_script.py 
> from local_package.modeling DatasetMapper, builtin
> from local_package.modeling import KRCNNConvHead 
31a35
>     builtin.register_data(args.dataset_dir)
33a38,39
>     # a dirty fix for the keypoint resolution config
>     cfg.MODEL.ROI_KEYPOINT_HEAD.POOLER_RESOLUTION = (14, 14)
37a44
>     cfg.MODEL.DEVICE = "cpu"
175a184
>     parser.add_argument("--dataset-dir", default="datasets")
```
2. What exact command you run:
```
python ./tools/caffe2_converter.py \
    --dataset-dir datasets/samples \
    --format onnx \
    --config-file configs/mask_rcnn.yaml \
    --run-eval \
    --output ./output/onnx/mask_rcnn_v4/ \
    MODEL.WEIGHTS ./weights.pth'''
```
3. __Full logs__ or other relevant observations:
```
Traceback (most recent call last):
  File "/home/james/Documents/tool/./tools/caffe2_converter.py", line 205, in <module>
    exported_model = export_caffe2_tracing(cfg, torch_model, first_batch)
  File "/home/james/Documents/tool/./tools/caffe2_converter.py", line 58, in export_caffe2_tracing
    onnx_model = tracer.export_onnx()
  File "/home/james/Documents/detectron2/detectron2/export/api.py", line 121, in export_onnx
    return export_onnx_model_impl(self.traceable_model, (self.traceable_inputs,))
  File "/home/james/Documents/detectron2/detectron2/export/caffe2_export.py", line 56, in export_onnx_model
    torch.onnx.export(
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/onnx/utils.py", line 676, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/onnx/utils.py", line 445, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args,
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/onnx/utils.py", line 409, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/onnx/utils.py", line 373, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/jit/_trace.py", line 1158, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/jit/_trace.py", line 125, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1003, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/james/Documents/detectron2/detectron2/export/caffe2_modeling.py", line 274, in forward
    detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1003, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/james/Documents/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 743, in forward
    pred_instances = self.forward_with_given_boxes(features, pred_instances)
  File "/home/james/Documents/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 770, in forward_with_given_boxes
    instances = self._forward_keypoint(features, instances)
  File "/home/james/Documents/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 870, in _forward_keypoint
    return self.keypoint_head(features, instances)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1003, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/james/Documents/tool/modeling/head.py", line 232, in forward
    keypoint_rcnn_inference(x, instances)
  File "/home/james/Documents/detectron2/detectron2/modeling/roi_heads/keypoint_head.py", line 121, in keypoint_rcnn_inference
    keypoint_results = heatmaps_to_keypoints(pred_keypoint_logits, bboxes_flat.detach())
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/jit/_trace.py", line 1112, in wrapper
    compiled_fn = script(wrapper.__original_fn)  # type: ignore
  File "/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch/jit/_script.py", line 1048, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 

(Tensor self, ...) -> (Tensor 0):
Keyword argument size unknown.
:
  File "/home/james/Documents/detectron2/detectron2/structures/keypoints.py", line 196
    for i in range(num_rois):
        outsize = (int(heights_ceil[i]), int(widths_ceil[i]))
        roi_map = F.interpolate(
                  ~~~~~~~~~~~~~ <--- HERE
            maps[[i]], size=outsize, mode="bicubic", align_corners=False
        ).squeeze(
```
4. please simplify the steps as much as possible so they do not require additional resources to
   run, such as a private dataset.

## Expected behavior:
The model would export to onnx

## Environment:
```
---------------------------------
sys.platform            linux
Python                  3.9.2 (default, Mar  3 2021, 20:02:32) [GCC 7.3.0]
numpy                   1.19.2
detectron2              0.4 @/home/james/Documents/detectron2/detectron2
Compiler                GCC 9.3
CUDA compiler           CUDA 11.2
detectron2 arch flags   8.6
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.9.0a0+gitbc05867 @/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 GeForce RTX 3090 (arch=8.6)
CUDA_HOME               /usr/local/cuda
Pillow                  8.2.0
torchvision             0.10.0a0+e79a74e @/home/james/miniconda3/envs/detectron-export/lib/python3.9/site-packages/torchvision-0.10.0a0+e79a74e-py3.9-linux-x86_64.egg/torchvision
torchvision arch flags  8.6
fvcore                  0.1.5.post20210402
iopath                  0.1.7
cv2                     4.5.1
----------------------  ----------------------------------------------------------------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.2
  - NVCC architecture flags: -gencode;arch=compute_86,code=sm_86
  - CuDNN 8.1.1
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.2, CUDNN_VERSION=8.1.1, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```

**Comment by ppwwyyxx** [comment] 2021-04-14 06:21
```
./export_model.py --config-file ../../configs/COCO-Keypoints/keypoint_rcnn_R_50_FPN_1x.yaml \                                                                             
    --output ./krcnn_onnx --format onnx --export-method caffe2_tracing MODEL.WEIGHTS https://dl.fbaipublicfiles.com/detectron2/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x/137849621/model_final_a6e10b.pkl MODEL.DEVICE cpu
```
This command runs without problems on my end, using today's detectron2 from github. If it fails for you, please provide an environment (e.g. docker) that reproduces it.

**Comment by XDynames** [comment] 2021-04-14 08:17
Do you have any sense of what it could be?
I don't really want to release the research code yet but have been hitting my head against a wall trying to get this model out if detectron for weeks

**Comment by ppwwyyxx** [comment] 2021-04-14 08:44
We would only investigate issues that we can reproduce

**Comment by XDynames** [comment] 2021-04-15 01:20
Do you know of any other deployment methods that don't use tracing? I suppose that would be a whole other issue

I'll try to make a container with a minimum bug for you

**Comment by ppwwyyxx** [comment] 2021-04-15 01:44
Please first try if the command given above in https://github.com/facebookresearch/detectron2/issues/2906#issuecomment-819261032 works with unmodified source code. If it works, then this is likely an issue in your custom code but not detectron2.

**Comment by ppwwyyxx** [comment] 2021-05-07 00:07
Closing since it's unclear how to reproduce the issue

**Closed by ppwwyyxx** 2021-05-07 00:07 UTC
