### ISSUE TITLE
How To Train On Multi-Category Keypoint Dataset (COCO Format)

### ISSUE THREAD

**Issue by cm107** [facebookresearch/detectron2#2203] opened 2020-10-28 06:11 UTC
I am familiar with how to train a keypoint model with a single category.
Single Category Example:
<details>
<summary>Show Single Category Example ('categories' value in COCO dataset)</summary>

```json
'categories': [
  {
    "id": 0,
    "supercategory": "primary",
    "name": "object0",
    "keypoints": [
      "a",
      "b",
      "c",
      "d"
    ],
    "skeleton": [
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ]
    ]
  }
]
```

</details>

The documents explain how to setup metadata for a single category. [(ref.)](https://detectron2.readthedocs.io/tutorials/datasets.html#metadata-for-datasets)
```python
kpt_label_list, kpt_skeleton, class_name_list = _get_kpt_info()
MetadataCatalog.get(instance_name).thing_classes = ['object0']
MetadataCatalog.get(instance_name).keypoint_names = ['a', 'b', 'c', 'd']
MetadataCatalog.get(instance_name).keypoint_flip_map = []
MetadataCatalog.get(instance_name).keypoint_connection_rules = [
    ['a', 'b', (0, 0, 255)], ['b', 'c', (0, 0, 255)], ['c', 'd', (0, 0, 255)],
    ['b', 'd', (0, 0, 255)], ['a', 'd', (0, 0, 255)]
]
```

But how would I setup the metadata for multiple objects, each with a different set of keypoints?
Multi-Category Example:
<details>
<summary>Show Multiple Category Example ('categories' value in COCO dataset)</summary>

'categories': [
  {
    "id": 0,
    "supercategory": "primary",
    "name": "object0",
    "keypoints": [
      "a",
      "b",
      "c",
      "d"
    ],
    "skeleton": [
      [
        0,
        1
      ],
      [
        1,
        2
      ],
      [
        2,
        3
      ],
      [
        1,
        3
      ],
      [
        0,
        3
      ]
    ]
  },
  {
    "id": 1,
    "supercategory": "secondary",
    "name": "object1",
    "keypoints": [
      "v",
      "w",
      "x",
      "y",
      "z"
    ],
    "skeleton": [
      [
        0,
        3
      ],
      [
        1,
        3
      ],
      [
        2,
        4
      ],
      [
        1,
        2
      ]
    ]
  }
]

</details>

In the above example, object0 and object1 have different keypoint names and a different skeleton. The total number of keypoints is also different.
It seems to me like it is possible to define multiple thing_classes, but there can only be one keypoint_connection_rules.
Is there a way to define multiple keypoint_connection_rules for the same model?

**Comment by ppwwyyxx** [comment] 2020-10-28 06:54
`keypoint_connection_rules` is the last thing to worry about since it only affects visualization of results.

Duplicate of #1415

**Closed by ppwwyyxx** 2020-10-28 06:54 UTC
