### ISSUE TITLE
How do i select certain classes?

### ISSUE THREAD

**Issue by Eloi-14855** [facebookresearch/detectron2#2172] opened 2020-10-22 17:24 UTC
## ❓ How to do something using detectron2

how can i filter de predictions after the predictions and before he writes it?, i want the code to only print the "pred_classes==0", it can detect all classes, but i only want to visual see the some classes, is there anyway to do it?

**Comment by ppwwyyxx** [comment] 2020-10-22 19:49
Duplicate of #1746

**Closed by ppwwyyxx** 2020-10-22 19:49 UTC
