### ISSUE TITLE
SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 1.

### ISSUE THREAD

**Issue by morganOliveira2018** [facebookresearch/detectron2#2278] opened 2020-11-17 22:30 UTC
## ❓ Is there any implementation that solves this problem when the uploaded image has a difference in width / height compared to the annotation?

I made notes using the "Labelme" tool, but the error below is occurring when I tried to train the dataset:

````
SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.6/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/dataset_mapper.py", line 126, in __call__
    utils.check_image_size(dataset_dict, image)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/data/detection_utils.py", line 200, in check_image_size
    expected_wh,
detectron2.data.detection_utils.SizeMismatchError: Mismatched (W,H) for image /content/fish_segmentation_instance/fish segmentation instance/train/ariaco19.JPEG, got (3024, 4032), expect (2048, 1536)
````

## ❓ The ideal would be to scale the width and height of the image with the same proportions of 600x600, before labeling?

**Comment by morganOliveira2018** [comment] 2020-11-17 22:33
@ppwwyyxx have you been through this kind of situation that could help me?

**Comment by ppwwyyxx** [comment] 2020-11-17 22:58
Duplicate of #863 and https://github.com/facebookresearch/detectron2/issues?q=SizeMismatchError%3A+Caught+SizeMismatchError

**Closed by ppwwyyxx** 2020-11-17 22:58 UTC

**Comment by CarlBhy** [comment] 2021-03-19 10:58
hi,i have solved this problem.This bad code is in the detectron2-master/detectron2/data/detection_utils.py line 186 to 209,I will post my modified code later.I think this error will not affect our training model, so I commented out part of the code and successfully solved the problem.

`def check_image_size(dataset_dict, image):
    """
    Raise an error if the image does not match the size specified in the dict.
    """
    if "width" in dataset_dict or "height" in dataset_dict:
        image_wh = (image.shape[1], image.shape[0])
        # expected_wh = (dataset_dict["width"], dataset_dict["height"])
        # if not image_wh == expected_wh:
        #     raise SizeMismatchError(
        #         "Mismatched image shape{}, got {}, expect {}.".format(
        #             " for image " + dataset_dict["file_name"]
        #             if "file_name" in dataset_dict
        #             else "",
        #             image_wh,
        #             expected_wh,
        #         )
        #         + " Please check the width/height in your annotation."
        #     )

    # To ensure bbox always remap to original image size
    if "width" not in dataset_dict:
        dataset_dict["width"] = image.shape[1]
    if "height" not in dataset_dict:
        dataset_dict["height"] = image.shape[0]`
Hope my answer is useful for you！

**Comment by Priyabrata017** [comment] 2021-03-24 07:04
Hi @CarlBhy @ppwwyyxx , I have commented the line in detectron2-master/detectron2/data/detection_utils.py line 186 to 209 but still getting the same error. Is there any issue with Pillow that is used to read images. Here is the error I am getting

```
SizeMismatchError                         Traceback (most recent call last)
<ipython-input-9-bc9f59a27ec0> in <module>()
     18 trainer = DefaultTrainer(cfg)
     19 trainer.resume_or_load(resume=True)
---> 20 trainer.train()

8 frames
/usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self)
    427             # have message field
    428             #raise self.exc_type(message=msg)
--> 429         #raise self.exc_type(msg)
    430 
    431 

SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.7/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
[    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/dataset_mapper.py", line 126, in __call__
    #utils.check_image_size(dataset_dict, image)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/detection_utils.py", line 202, in check_image_size
    #+ "](`url`) Please check the width/height in your annotation."
detectron2.data.detection_utils.SizeMismatchError: Mismatched image shape for image ./Filtered_images/pm36.jpg, got (1600, 1157), expect (800, 533). Please check the width/height in your annotation.
```

**Comment by Priyabrata017** [comment] 2021-03-24 07:08
Hi @CarlBhy @ppwwyyxx , I have commented the line in detectron2-master/detectron2/data/detection_utils.py line 186 to 209 but still getting the same error. Is there any issue with Pillow that is used to read images. Here is the error I am getting:

```
SizeMismatchError                         Traceback (most recent call last)
<ipython-input-9-bc9f59a27ec0> in <module>()
     18 trainer = DefaultTrainer(cfg)
     19 trainer.resume_or_load(resume=True)
---> 20 trainer.train()

8 frames
/usr/local/lib/python3.7/dist-packages/torch/_utils.py in reraise(self)
    427             # have message field
    428             #raise self.exc_type(message=msg)
--> 429         #raise self.exc_type(msg)
    430 
    431 

SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/common.py", line 43, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/usr/local/lib/python3.7/dist-packages/detectron2/utils/serialize.py", line 23, in __call__
    return self._obj(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/dataset_mapper.py", line 126, in __call__
    #utils.check_image_size(dataset_dict, image)
  File "/usr/local/lib/python3.7/dist-packages/detectron2/data/detection_utils.py", line 202, in check_image_size
    #+ " Please check the width/height in your annotation."
detectron2.data.detection_utils.SizeMismatchError: Mismatched image shape for image ./Filtered_images/pm36.jpg, got (1600, 1157), expect (800, 533). Please check the width/height in your annotation.
```

**Comment by raj-4444** [comment] 2021-08-20 08:28
@Priyabrata017 please remove the custom image height and width..it will take automatically
