### ISSUE TITLE
how to handle no proposal when inference at the second stage( after rpn )?

### ISSUE THREAD

**Issue by miraclebiu** [facebookresearch/detectron2#705] opened 2020-01-16 03:18 UTC
## ❓ How to use Detectron2

Questions like:

1. How to do X with detectron2?
2. How detectron2 does X?

NOTE:

1. If you met any unexpected issue when using detectron2 and wish to know why,
   please use the "Unexpected Problems / Bugs" issue template.

2. We do not answer general machine learning / computer vision questions that are not specific to
	 detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be
	 used to achieve X.

**Comment by miraclebiu** [comment] 2020-01-16 07:05
the inference behavior is different when using demo.py and train_net.py(eval_only)

**Comment by ppwwyyxx** [comment] 2020-01-16 07:08
I believe there will always be some proposals.
(Maybe it's not when the input image is like 10x10, but I don't think it's necessary to support such cases

**Comment by miraclebiu** [comment] 2020-01-16 07:34
> I believe there will always be some proposals.
> (Maybe it's not when the input image is like 10x10, but I don't think it's necessary to support such cases

the main reason why i ask this question is the code has different behavior when using demo.py and train_net.py(eval_only).
in my case , using demo I can get one image while using eval_only, the model cannot get right output

**Comment by miraclebiu** [comment] 2020-01-16 09:08
> I believe there will always be some proposals.
> (Maybe it's not when the input image is like 10x10, but I don't think it's necessary to support such cases

for example, my model only train on car and person, when **rpn doesn't output a proposa**l but when you use **batchnorm** in the follow roi_heads, the model will raise an error : RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

**Comment by miraclebiu** [comment] 2020-01-16 09:29
When you set MODEL.ROI_HEADS.SCORE_THRESH_TEST=0.0 cannot solve the problem, because all the proposals will predict to class(classid=num_class, i.d.2 background in this case), and no proposal will survive

**Comment by ppwwyyxx** [comment] 2020-01-16 14:56
Since you're seeing an unexpected issue, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md). Otherwise I could not understand what you're describing. The words currently don't make much sense to me, for example, our batchnorm doesn't even use cudnn, and `ROI_HEADS.SCORE_THRESH_TEST` has nothing to do with proposals.

**Comment by miraclebiu** [comment] 2020-01-17 01:45
> Since you're seeing an unexpected issue, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md). Otherwise I could not understand what you're describing. The words currently don't make much sense to me, for example, our batchnorm doesn't even use cudnn, and `ROI_HEADS.SCORE_THRESH_TEST` has nothing to do with proposals.

Sorry, my mistake, the previous comments are wrong since i misunderstand the process of mask rcnn.
And the really problem is that when testing, **mask branch only infer on box output** from **roi_head._forward_box()** which may have **zero** box for mask branch, and at the same time you use batchnorm in the mask branch, you may get the error CUDNN_STATUS_BAD_PARAM. Current codes do not consider this abnormal situation

**Comment by ppwwyyxx** [comment] 2020-01-17 02:02
Again, if you met any unexpected issues, please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md) and let others reproduce it.

And again, our batchnorm doesn't even use cudnn when there are zero boxes. If you met unexpected issues, please first describe the issue itself before speculating why it happens.

**Comment by ppwwyyxx** [comment] 2020-01-24 09:17
Closing as no valid issue is provided

**Closed by ppwwyyxx** 2020-01-24 09:17 UTC
